export const PROMPT_CONTEXT_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  'html,body{height:100%;margin:0;overflow:hidden}',
  'body{display:flex;flex-direction:column;background:#0d1117;color:#e6e6ef;',
  'font:13px/1.5 system-ui,"Segoe UI","Microsoft YaHei",sans-serif}',
  '.bar{flex:none;padding:8px 14px;border-bottom:1px solid #262634;display:flex;gap:8px;align-items:center}',
  'h1{font:600 14px system-ui;margin:0}',
  '.ghost{margin-left:auto;background:transparent;border:1px solid #333;color:#a8a8bd;border-radius:8px;',
  'padding:4px 10px;font:12px system-ui;cursor:pointer}',
  '.ghost:disabled{opacity:.4}',
  '.meta{color:#8b949e;font-size:11px}',
  '.cols{flex:1;min-height:0;display:flex}',
  '.col{flex:1;min-width:0;display:flex;flex-direction:column;border-right:1px solid #262634}',
  '.col:last-child{border-right:none}',
  '.col h2{flex:none;margin:0;padding:8px 12px;font:600 12px system-ui;color:#a8a8bd;border-bottom:1px solid #262634}',
  '.list{flex:1;min-height:0;overflow:auto;padding:8px 10px 16px;scrollbar-width:none}',
  '.list::-webkit-scrollbar{display:none}',
  '.item{padding:8px 8px 9px;border-bottom:1px solid #1c1c28;cursor:pointer}',
  '.item:hover{background:#16161e}',
  '.item.open .body{display:block}',
  '.hd{display:flex;gap:6px;align-items:baseline;flex-wrap:wrap}',
  '.k{font:600 12px system-ui;color:#79c0ff}',
  '.item[data-kind="section"] .k{color:#79c0ff}',
  '.item[data-kind="context"] .k{color:#d2a8ff}',
  '.item[data-kind="variable"] .k{color:#7ee787}',
  '.item[data-kind="tools"] .k{color:#ffa657}',
  '.item[data-kind="persona"] .k{color:#e6c07b}',
  '.tag{font-size:10px;color:#8b949e;border:1px solid #30363d;border-radius:999px;padding:0 6px}',
  '.line{color:#c9d1d9;font-size:12px;margin-top:3px;word-break:break-word}',
  '.body{display:none;margin-top:6px;padding:8px;background:#16161e;border:1px solid #262634;border-radius:8px;',
  'white-space:pre-wrap;word-break:break-word;font:11px/1.5 ui-monospace,Consolas,monospace;color:#a8a8bd;max-height:220px;overflow:auto}',
  '.empty{color:#8b949e;padding:18px 12px;line-height:1.6}',
  '.err{color:#ffb4ae;padding:12px}',
  '</style></head><body>',
  '<div class="bar"><h1>Prompt Context</h1>',
  '<span class="meta" id="stat">—</span>',
  '<button class="ghost" id="try" type="button">试拼</button></div>',
  '<div class="cols">',
  '<section class="col"><h2>可获取素材</h2><div class="list" id="src"></div></section>',
  '<section class="col"><h2>拼接成品</h2><div class="list" id="out"></div></section>',
  '</div>',
  '<script>',
  'function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;");}',
  'const KIND={section:"系统段",context:"运行时",variable:"变量",tools:"工具",persona:"人设"};',
  'function clock(t){if(!t)return "";try{return new Date(t).toLocaleTimeString("zh-CN",{hour12:false});}catch(e){return "";}}',
  'function card(kind,name,tags,line,body){',
  'return \'<div class="item" data-kind="\'+esc(kind)+\'"><div class="hd"><span class="k">\'+esc(KIND[kind]||kind)+\'</span>\'+',
  '\'<span>\'+esc(name)+\'</span>\'+tags+\'</div><div class="line">\'+esc(line||"（空）")+\'</div>\'+',
  '(body?\'<pre class="body">\'+esc(body)+\'</pre>\':"")+"</div>";}',
  'function tags(arr){return arr.filter(Boolean).map(function(t){return \'<span class="tag">\'+esc(t)+\'</span>\';}).join("");}',
  'function renderSrc(el,sources){',
  'if(!sources||!sources.length){el.innerHTML=\'<div class="empty">还没有登记。其它插件调用 section / context / tools / variable 后会出现在这里。</div>\';return;}',
  'el.innerHTML=sources.map(function(s){',
  'return card(s.kind,s.name,tags([s.layer,s.live?"动态":"",s.order!=null?"#"+s.order:""]),s.preview,s.preview);',
  '}).join("");}',
  'function renderOut(el,snap){',
  'const asm=snap&&snap.assembly,applied=snap&&snap.applied;',
  'if(!asm&&!applied){el.innerHTML=\'<div class="empty">尚未 assemble。跑一轮对话，或点右上角「试拼」。点开条目看全文。</div>\';return;}',
  'var html="";',
  'if(asm){',
  'html+=\'<div class="empty" style="padding:8px 8px 4px">assemble \'+esc(clock(snap.assembledAt))+\' · \'+asm.sections.length+\' 段 · \'+asm.tools.length+\' 工具</div>\';',
  '(asm.sections||[]).forEach(function(s){html+=card("section",s.name,tags(["成品","#"+s.order]),s.text,s.text);});',
  '(asm.contexts||[]).forEach(function(s){html+=card("context",s.name,tags(["成品","#"+s.order]),s.text,s.text);});',
  '(asm.tools||[]).forEach(function(t){html+=card("tools",t.name,[],t.description||"",t.description||"");});',
  'html+=card("section","systemText",tags(["拼接"]),asm.systemText||"（空）",asm.systemText);',
  'html+=card("context","contextText",tags(["拼接"]),asm.contextText||"（无快照）",asm.contextText);',
  'var vars=asm.variables||{},vk=Object.keys(vars);',
  'if(vk.length)html+=card("variable","variables",[],vk.map(function(k){return k+"="+vars[k];}).join(" · "),JSON.stringify(vars,null,2));',
  '}',
  'if(applied){',
  'html+=\'<div class="empty" style="padding:10px 8px 4px">已 apply → session \'+esc(String(applied.sessionId).slice(0,8))+\' · \'+esc(clock(applied.at))+"</div>";',
  'html+=card("section","system（已写入）",[],applied.systemText||"（空）",applied.systemText);',
  'html+=card("context","snapshot（已写入）",[],applied.contextText||"（无）",applied.contextText);',
  '}',
  'el.innerHTML=html;}',
  'let lastKey="";',
  'async function refresh(force){',
  'const src=document.getElementById("src"),out=document.getElementById("out"),stat=document.getElementById("stat");',
  'if(!window.wh||!window.wh.call){src.innerHTML=\'<div class="empty">窗口桥未就绪</div>\';return;}',
  'try{',
  'const r=await window.wh.call("promptContext","inspect",[]);',
  'if(!r.ok){src.innerHTML=\'<div class="err">\'+esc(r.error||"读取失败")+"</div>";return;}',
  'const snap=r.result||{};',
  'const n=(snap.sources||[]).length;',
  'const key=n+":"+(snap.assembledAt||"")+":"+(snap.applied&&snap.applied.at||"");',
  'if(!force&&key===lastKey)return;',
  'lastKey=key;',
  'stat.textContent=n+" 条素材"+(snap.assembly?" · 有成品":"");',
  'renderSrc(src,snap.sources);',
  'renderOut(out,snap);',
  '}catch(e){src.innerHTML=\'<div class="err">\'+esc(e)+"</div>";}}',
  'document.getElementById("src").onclick=document.getElementById("out").onclick=function(ev){',
  'const item=ev.target.closest(".item"); if(item) item.classList.toggle("open");};',
  'document.getElementById("try").onclick=async function(){',
  'this.disabled=true;',
  'try{',
  'const r=await window.wh.call("promptContext","assemble",[{}]);',
  'if(!r.ok) alert(r.error||"试拼失败");',
  '}catch(e){alert(String(e));}',
  'this.disabled=false; lastKey=""; refresh(true);};',
  'refresh(true);setInterval(function(){refresh(false);},800);',
  '</script></body></html>',
].join('');
