export const POMODORO_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  'html,body{height:100%;margin:0;overflow:hidden}',
  'body{display:flex;flex-direction:column;background:#0f0f14;color:#e6e6ef;',
  'font:14px/1.5 system-ui,"Segoe UI","Microsoft YaHei",sans-serif}',
  '.bar{flex:none;padding:14px 16px 10px;border-bottom:1px solid #262634;background:#16161e}',
  'h1{font:600 16px system-ui;margin:0 0 4px}',
  '.desc{margin:0;font-size:12px;color:#8b949e}',
  '.main{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:16px;gap:12px}',
  '.phase{font-size:13px;letter-spacing:.12em;text-transform:uppercase;color:#79c0ff}',
  '.phase.break{color:#ffa657}.phase.idle{color:#8b949e}',
  '.clock{font:700 56px/1 ui-monospace,Consolas,monospace;letter-spacing:.04em}',
  '.count{font-size:12px;color:#8b949e}',
  '.controls{display:flex;flex-wrap:wrap;gap:8px;justify-content:center;margin-top:8px}',
  'button{border-radius:10px;border:1px solid #30363d;background:#21262d;color:#e6e6ef;',
  'padding:8px 14px;font:13px system-ui;cursor:pointer}',
  'button.primary{background:rgba(46,160,67,.18);border-color:rgba(46,160,67,.45);color:#7ee787}',
  'button:disabled{opacity:.45;cursor:default}',
  '.cfg{flex:none;border-top:1px solid #262634;padding:12px 16px;display:grid;gap:8px;grid-template-columns:1fr 1fr}',
  '.cfg label{font-size:11px;color:#8b949e;display:flex;flex-direction:column;gap:4px}',
  '.cfg input{background:#0d1117;border:1px solid #30363d;border-radius:8px;color:#e6e6ef;padding:6px 8px;font:12px ui-monospace}',
  '.err{flex:none;padding:8px 16px;color:#ff7b72;font-size:12px;display:none}',
  '</style></head><body>',
  '<div class="bar"><h1>番茄钟</h1><p class="desc">专注 · 短休 · 长休。托盘右键可快速打开。</p></div>',
  '<div class="main">',
  '<div class="phase idle" id="phase">待机</div>',
  '<div class="clock" id="clock">25:00</div>',
  '<div class="count" id="count">已完成 0 个番茄</div>',
  '<div class="controls">',
  '<button type="button" class="primary" id="btnStart">开始</button>',
  '<button type="button" id="btnPause" disabled>暂停</button>',
  '<button type="button" id="btnResume" disabled>继续</button>',
  '<button type="button" id="btnSkip" disabled>跳过</button>',
  '<button type="button" id="btnReset">重置</button>',
  '</div></div>',
  '<div class="cfg">',
  '<label>专注（分）<input id="cfgFocus" type="number" min="1" max="120" value="25" /></label>',
  '<label>短休（分）<input id="cfgShort" type="number" min="1" max="60" value="5" /></label>',
  '<label>长休（分）<input id="cfgLong" type="number" min="1" max="60" value="15" /></label>',
  '<label>长休间隔（个）<input id="cfgEvery" type="number" min="1" max="12" value="4" /></label>',
  '</div>',
  '<div class="err" id="err"></div>',
  '<script>',
  'var PHASE_LABEL={idle:"待机",focus:"专注",shortBreak:"短休",longBreak:"长休"};',
  'function fmt(ms){var t=Math.max(0,Math.ceil(ms/1000));var m=Math.floor(t/60);var s=t%60;return String(m).padStart(2,"0")+":"+String(s).padStart(2,"0");}',
  'async function call(m,a){var r=await window.wh.call("pomodoro",m,a||[]);if(!r.ok)throw new Error(r.error||"失败");return r.result;}',
  'function showErr(msg){var el=document.getElementById("err");if(!msg){el.style.display="none";el.textContent="";return;}el.style.display="block";el.textContent=msg;}',
  'function readCfg(){return {',
  'focusMinutes:Number(document.getElementById("cfgFocus").value)||25,',
  'shortBreakMinutes:Number(document.getElementById("cfgShort").value)||5,',
  'longBreakMinutes:Number(document.getElementById("cfgLong").value)||15,',
  'longBreakEvery:Number(document.getElementById("cfgEvery").value)||4};}',
  'function applyCfgInputs(cfg){',
  'document.getElementById("cfgFocus").value=cfg.focusMinutes;',
  'document.getElementById("cfgShort").value=cfg.shortBreakMinutes;',
  'document.getElementById("cfgLong").value=cfg.longBreakMinutes;',
  'document.getElementById("cfgEvery").value=cfg.longBreakEvery;}',
  'function render(s){',
  'var ph=document.getElementById("phase");ph.textContent=PHASE_LABEL[s.phase]||s.phase;',
  'ph.className="phase"+(s.phase==="idle"?" idle":(s.phase==="focus"?"":" break"));',
  'document.getElementById("clock").textContent=s.phase==="idle"?fmt(s.config.focusMinutes*60000):fmt(s.remainingMs);',
  'document.getElementById("count").textContent="已完成 "+s.completedFocus+" 个番茄";',
  'applyCfgInputs(s.config);',
  'document.getElementById("btnStart").disabled=s.running&&!s.paused;',
  'document.getElementById("btnPause").disabled=!s.running||s.paused||s.phase==="idle";',
  'document.getElementById("btnResume").disabled=!s.paused;',
  'document.getElementById("btnSkip").disabled=s.phase==="idle";',
  '}',
  'async function refresh(){try{render(await call("snapshot"));showErr("");}catch(e){showErr(String(e.message||e));}}',
  'document.getElementById("btnStart").onclick=async function(){try{render(await call("start"));showErr("");}catch(e){showErr(String(e.message||e));}};',
  'document.getElementById("btnPause").onclick=async function(){try{render(await call("pause"));showErr("");}catch(e){showErr(String(e.message||e));}};',
  'document.getElementById("btnResume").onclick=async function(){try{render(await call("resume"));showErr("");}catch(e){showErr(String(e.message||e));}};',
  'document.getElementById("btnSkip").onclick=async function(){try{render(await call("skip"));showErr("");}catch(e){showErr(String(e.message||e));}};',
  'document.getElementById("btnReset").onclick=async function(){try{render(await call("reset"));showErr("");}catch(e){showErr(String(e.message||e));}};',
  '["cfgFocus","cfgShort","cfgLong","cfgEvery"].forEach(function(id){',
  'document.getElementById(id).onchange=async function(){try{render(await call("configure",[readCfg()]));showErr("");}catch(e){showErr(String(e.message||e));}};});',
  'refresh();setInterval(refresh,1000);',
  '</script></body></html>',
].join('');
