export const TOOLBOX_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  'html,body{height:100%;margin:0;overflow:hidden}',
  'body{display:flex;flex-direction:column;background:#0d1117;color:#e6e6ef;',
  'font:13px/1.5 system-ui,"Segoe UI","Microsoft YaHei",sans-serif}',
  '.bar{flex:none;padding:10px 14px;border-bottom:1px solid #262634;background:#161b22}',
  'h1{font:600 15px system-ui;margin:0 0 4px}',
  '.desc{margin:0;font-size:12px;color:#8b949e;line-height:1.5}',
  '.ws{flex:none;padding:10px 14px;border-bottom:1px solid #262634;display:flex;gap:8px;align-items:center}',
  '.ws label{font-size:12px;color:#8b949e;white-space:nowrap}',
  '.ws input{flex:1;min-width:0;background:#0d1117;border:1px solid #30363d;border-radius:8px;color:#e6e6ef;',
  'padding:7px 10px;font:12px ui-monospace,Consolas,monospace}',
  '.ws input:focus{outline:none;border-color:#388bfd}',
  '.grid{flex:1;min-height:0;overflow:auto;padding:12px 14px;display:grid;gap:10px;',
  'grid-template-columns:repeat(auto-fill,minmax(240px,1fr));align-content:start;scrollbar-width:thin}',
  '.card{background:#161b22;border:1px solid #30363d;border-radius:10px;padding:12px 12px 10px}',
  '.card h2{margin:0 0 4px;font:600 14px system-ui}',
  '.card .sub{font:11px ui-monospace,Consolas,monospace;color:#79c0ff;margin-bottom:6px}',
  '.card .line{font-size:12px;color:#8b949e;margin:0 0 8px;line-height:1.45}',
  '.field{margin:6px 0}',
  '.field label{display:block;font-size:11px;color:#8b949e;margin-bottom:3px}',
  '.field input{width:100%;box-sizing:border-box;background:#0d1117;border:1px solid #30363d;border-radius:6px;',
  'color:#e6e6ef;padding:6px 8px;font:12px ui-monospace,Consolas,monospace}',
  '.run{width:100%;margin-top:8px;background:rgba(46,160,67,.18);border:1px solid rgba(46,160,67,.45);',
  'color:#7ee787;border-radius:8px;padding:7px 10px;font:12px system-ui;cursor:pointer}',
  '.run:hover{background:rgba(46,160,67,.28)}',
  '.run:disabled{opacity:.45;cursor:default}',
  '.foot{flex:none;border-top:1px solid #262634;background:#161b22;padding:8px 14px}',
  '.foot .meta{font-size:11px;color:#8b949e;margin-bottom:6px}',
  '.out{margin:0;max-height:120px;overflow:auto;background:#0d1117;border:1px solid #30363d;border-radius:8px;',
  'padding:8px 10px;font:11px/1.45 ui-monospace,Consolas,monospace;color:#c9d1d9;white-space:pre-wrap;word-break:break-word}',
  '.out.err{color:#ff7b72}',
  '.empty{padding:24px;color:#8b949e;text-align:center}',
  '</style></head><body>',
  '<div class="bar"><h1>工具盒子</h1><p class="desc">点按即可执行配置脚本。工作区路径可改；agent 仍通过 box.* 工具调用。</p></div>',
  '<div class="ws"><label for="ws">工作区</label><input id="ws" spellcheck="false" autocomplete="off" /></div>',
  '<div class="grid" id="grid"><div class="empty">加载中…</div></div>',
  '<div class="foot"><div class="meta" id="meta">—</div><pre class="out" id="out">（执行结果）</pre></div>',
  '<script>',
  'function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;");}',
  'var scripts=[],busy=false;',
  'function wsInput(){return document.getElementById("ws");}',
  'function saveWs(){try{localStorage.setItem("wh-toolbox-ws",wsInput().value);}catch(e){}}',
  'function loadWs(def){var v=def;try{var s=localStorage.getItem("wh-toolbox-ws");if(s)v=s;}catch(e){}wsInput().value=v;}',
  'function collectArgs(card){var args={},fields=card.querySelectorAll("[data-param]");',
  'for(var i=0;i<fields.length;i++){var k=fields[i].getAttribute("data-param");if(k)args[k]=fields[i].value;}return args;}',
  'function render(){',
  'var grid=document.getElementById("grid"),meta=document.getElementById("meta");',
  'if(!scripts.length){grid.innerHTML=\'<div class="empty">暂无脚本。在 toolbox.config.scripts 里配置。</div>\';meta.textContent="0 个工具";return;}',
  'meta.textContent=scripts.length+" 个快捷工具";',
  'grid.innerHTML=scripts.map(function(s){',
  'var fields=(s.params||[]).map(function(p){',
  'return \'<div class="field"><label>\'+esc(p.label||p.key)+\'</label><input data-param="\'+esc(p.key)+\'" placeholder="\'+esc(p.placeholder||"")+\'" value="\'+esc(p.default||"")+\'" /></div>\';',
  '}).join("");',
  'return \'<div class="card" data-name="\'+esc(s.name)+\'"><h2>\'+esc(s.label||s.name)+\'</h2>\'',
  '+\'<div class="sub">\'+esc(s.tool)+\'</div>\'',
  '+\'<p class="line">\'+esc(s.description||"")+\'</p>\'+fields',
  '+\'<button type="button" class="run">运行</button></div>\';',
  '}).join("");',
  '}',
  'async function runCard(card){',
  'if(busy||!window.wh||!window.wh.call)return;',
  'var name=card.getAttribute("data-name"),btn=card.querySelector(".run"),out=document.getElementById("out");',
  'busy=true;if(btn)btn.disabled=true;out.className="out";out.textContent="执行中…";saveWs();',
  'var r=await window.wh.call("toolbox","run",[name,collectArgs(card),{workspace:wsInput().value.trim()}]);',
  'busy=false;if(btn)btn.disabled=false;',
  'if(!r.ok){out.className="out err";out.textContent=r.error||"失败";return;}',
  'out.className="out";out.textContent=r.result&&r.result.content!=null?r.result.content:JSON.stringify(r.result,null,2);',
  '}',
  'async function boot(){',
  'if(!window.wh||!window.wh.call)return;',
  'var r=await window.wh.call("toolbox","info",[]);',
  'if(!r.ok){document.getElementById("grid").innerHTML=\'<div class="empty">\'+esc(r.error||"加载失败")+"</div>";return;}',
  'scripts=r.result.scripts||[];loadWs(r.result.cwd||"");render();',
  'document.getElementById("grid").addEventListener("click",function(e){',
  'var btn=e.target.closest(".run");if(!btn)return;var card=btn.closest(".card");if(card)runCard(card);});',
  '}',
  'boot();',
  '</script></body></html>',
].join('');
