export const GIT_TOOLS_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  'html,body{height:100%;margin:0;overflow:hidden}',
  'body{display:flex;flex-direction:column;background:#0d1117;color:#e6e6ef;',
  'font:13px/1.5 system-ui,"Segoe UI","Microsoft YaHei",sans-serif}',
  '.bar{flex:none;padding:10px 14px;border-bottom:1px solid #262634;background:#161b22}',
  'h1{font:600 15px system-ui;margin:0 0 4px}',
  '.desc{margin:0;font-size:12px;color:#8b949e}',
  '.meta{flex:none;padding:8px 14px;border-bottom:1px solid #262634;font:11px ui-monospace,Consolas,monospace;color:#8b949e}',
  '.meta.ok{color:#7ee787}.meta.warn{color:#d29922}',
  '.ws{flex:none;padding:8px 14px;border-bottom:1px solid #262634;display:flex;gap:8px;align-items:center}',
  '.ws label{font-size:12px;color:#8b949e}',
  '.ws input{flex:1;background:#0d1117;border:1px solid #30363d;border-radius:8px;color:#e6e6ef;padding:6px 8px;font:12px ui-monospace,Consolas,monospace}',
  '.grid{flex:1;min-height:0;overflow:auto;padding:12px;display:grid;gap:10px;grid-template-columns:repeat(auto-fill,minmax(220px,1fr))}',
  '.card{background:#161b22;border:1px solid #30363d;border-radius:10px;padding:12px}',
  '.card h2{margin:0 0 4px;font:600 13px system-ui}',
  '.card .sub{font:10px ui-monospace;color:#79c0ff;margin-bottom:6px}',
  '.card .line{font-size:11px;color:#8b949e;margin:0 0 8px}',
  '.field input{width:100%;box-sizing:border-box;background:#0d1117;border:1px solid #30363d;border-radius:6px;color:#e6e6ef;padding:5px 7px;font:11px ui-monospace;margin-top:4px}',
  '.run{width:100%;margin-top:8px;background:rgba(46,160,67,.15);border:1px solid rgba(46,160,67,.4);color:#7ee787;border-radius:8px;padding:6px;cursor:pointer;font:12px system-ui}',
  '.run:disabled{opacity:.4;cursor:default}',
  '.foot{flex:none;border-top:1px solid #262634;padding:8px 12px}',
  '.out{margin:0;max-height:140px;overflow:auto;font:11px/1.45 ui-monospace,Consolas,monospace;white-space:pre-wrap}',
  '</style></head><body>',
  '<div class="bar"><h1>Git 工具</h1><p class="desc">本地 git 探测 + 工作区内执行。Agent 使用 git.status / git.diff 等。</p></div>',
  '<div class="meta" id="probe">探测中…</div>',
  '<div class="ws"><label>工作区</label><input id="ws" /></div>',
  '<div class="grid" id="grid"></div>',
  '<div class="foot"><pre class="out" id="out">（结果）</pre></div>',
  '<script>',
  'var ACTIONS=[{id:"status",label:"状态",need:[]},{id:"diff",label:"差异",need:["path"]},{id:"log",label:"日志",need:[]},',
  '{id:"pull",label:"拉取",need:[]},{id:"add",label:"暂存",need:["path"]},{id:"commit",label:"提交",need:["message"]},{id:"push",label:"推送",need:[]}];',
  'function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;");}',
  'async function call(m,a){var r=await window.wh.call("gitTools",m,a||[]);if(!r.ok)throw new Error(r.error||"失败");return r.result;}',
  'function ws(){return document.getElementById("ws").value.trim();}',
  'async function refreshProbe(){',
  '  var info=await call("infoAsync",[ws()]);',
  '  var el=document.getElementById("probe");',
  '  if(!info.probe.available){el.className="meta warn";el.textContent=info.probe.hint||"git 不可用";return false;}',
  '  el.className="meta ok";',
  '  el.textContent="git "+(info.probe.version||"")+(info.isRepo?" · 分支 "+(info.branch||"?"):" · 非仓库");',
  '  return info.probe.available;',
  '}',
  'function renderGrid(){',
  '  document.getElementById("grid").innerHTML=ACTIONS.map(function(a){',
  '    var fields=(a.need||[]).map(function(k){return \'<input data-k="\'+k+\'" placeholder="\'+k+\'" />\';}).join("");',
  '    return \'<div class="card"><h2>\'+esc(a.label)+\'</h2><div class="sub">git.\'+esc(a.id)+\'</div>\'',
  '      +fields+\'<button type="button" class="run" data-id="\'+esc(a.id)+\'">运行</button></div>\';}).join("");',
  '}',
  'document.getElementById("grid").onclick=async function(e){',
  '  var btn=e.target.closest("button.run");if(!btn)return;',
  '  var card=btn.closest(".card");var args={};',
  '  card.querySelectorAll("input[data-k]").forEach(function(inp){args[inp.getAttribute("data-k")]=inp.value;});',
  '  try{var r=await call("run",[btn.getAttribute("data-id"),{root:ws(),args:args}]);',
  '    document.getElementById("out").textContent=(r.stdout||"")+(r.stderr?("\\n"+r.stderr):"")||("(code "+r.code+")");',
  '  }catch(err){document.getElementById("out").textContent=String(err.message||err);}',
  '};',
  'renderGrid();',
  'call("info").then(function(i){document.getElementById("ws").value=i.root;refreshProbe();}).catch(function(e){document.getElementById("probe").textContent=e.message;});',
  'document.getElementById("ws").onchange=function(){refreshProbe();};',
  '</script></body></html>',
].join('');
