export const MEMORY_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  'html,body{height:100%;margin:0;overflow:hidden}',
  'body{display:flex;flex-direction:column;background:#0d1117;color:#e6e6ef;',
  'font:13px/1.5 system-ui,"Segoe UI","Microsoft YaHei",sans-serif}',
  '.bar{flex:none;padding:8px 14px;border-bottom:1px solid #262634;display:flex;gap:8px;align-items:center;flex-wrap:wrap}',
  'h1{font:600 14px system-ui;margin:0}',
  '.meta{color:#8b949e;font-size:11px}',
  '.ghost,.pri{border-radius:8px;padding:4px 10px;font:12px system-ui;cursor:pointer}',
  '.ghost{background:transparent;border:1px solid #333;color:#a8a8bd}',
  '.ghost:hover{border-color:#4a6aa0;color:#79c0ff}',
  '.pri{background:linear-gradient(135deg,#2ea043,#238636);border:none;color:#fff}',
  '.cols{flex:1;min-height:0;display:flex}',
  '.col{flex:1;min-width:0;display:flex;flex-direction:column;border-right:1px solid #262634}',
  '.col:last-child{border-right:none}',
  '.col h2{flex:none;margin:0;padding:8px 12px;font:600 12px system-ui;color:#a8a8bd;border-bottom:1px solid #262634}',
  '.pad{flex:1;min-height:0;overflow:auto;padding:10px 12px 16px}',
  'label{display:block;font-size:11px;color:#8b949e;margin:8px 0 4px}',
  'input,textarea{width:100%;box-sizing:border-box;background:#16161e;border:1px solid #2c2c3e;border-radius:8px;',
  'color:#e6e6ef;padding:7px 10px;font:13px/1.5 system-ui;outline:none}',
  'textarea{min-height:72px;resize:vertical}',
  'input:focus,textarea:focus{border-color:#4a6aa0}',
  '.row{display:flex;gap:6px;margin-top:8px}',
  '.row input{flex:1}',
  '.card{padding:10px 0;border-bottom:1px solid #1c1c28}',
  '.card .t{color:#c9d1d9;font-weight:600}',
  '.card .b{color:#8b949e;margin-top:4px;white-space:pre-wrap;word-break:break-word;font-size:12px}',
  '.card .ops{margin-top:6px;display:flex;gap:6px;flex-wrap:wrap}',
  '.tiny{background:transparent;border:1px solid #333;color:#8b949e;border-radius:6px;padding:2px 8px;font:11px system-ui;cursor:pointer}',
  '.tiny.on{color:#e6c07b;border-color:rgba(230,192,123,.4)}',
  '.preview{flex:none;max-height:32%;overflow:auto;border-top:1px solid #262634;padding:8px 12px;background:#16161e;',
  'white-space:pre-wrap;word-break:break-word;font:11px/1.5 ui-monospace,Consolas,monospace;color:#a8a8bd}',
  '.empty,.err{color:#8b949e;padding:12px 0}',
  '.toast{position:fixed;left:50%;bottom:16px;transform:translateX(-50%);background:#21262d;border:1px solid #30363d;',
  'color:#7ee787;border-radius:8px;padding:6px 12px;font:12px system-ui;opacity:0;pointer-events:none;transition:opacity .15s}',
  '.toast.on{opacity:1}',
  '</style></head><body>',
  '<div class="bar"><h1>记忆</h1><span class="meta" id="meta">—</span>',
  '<button class="ghost" type="button" id="reload">刷新</button>',
  '<button class="ghost" type="button" id="breathBtn">breath</button>',
  '<button class="pri" type="button" id="holdBtn">记下</button></div>',
  '<div class="cols">',
  '<section class="col"><h2>写入</h2><div class="pad">',
  '<label>标题（可选）</label><input id="name" placeholder="一句话标题" />',
  '<label>正文</label><textarea id="body" placeholder="我记得……"></textarea>',
  '<label>domain</label><input id="domain" value="未分类" />',
  '<div class="row"><label style="margin:0;align-self:center">importance</label>',
  '<input id="importance" type="number" min="1" max="10" value="5" style="width:64px;flex:none" />',
  '<label style="margin:0;align-self:center">钉住</label><input id="pinned" type="checkbox" style="width:auto" /></div>',
  '<label>检索</label><div class="row"><input id="q" placeholder="关键词" /><button class="ghost" type="button" id="searchBtn">搜</button></div>',
  '</div></section>',
  '<section class="col"><h2>桶列表</h2><div class="pad" id="list"></div></section>',
  '</div>',
  '<pre class="preview" id="preview">breath 预览…</pre>',
  '<div class="toast" id="toast"></div>',
  '<script>',
  'function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;");}',
  'let toastTimer;let includeArchive=false;',
  'function toast(msg,ok){var el=document.getElementById("toast");el.textContent=msg;el.style.color=ok===false?"#ffb4ae":"#7ee787";',
  'el.className="toast on";clearTimeout(toastTimer);toastTimer=setTimeout(function(){el.className="toast";},1200);}',
  'async function call(method,args){',
  'if(!window.wh||!window.wh.call)return {ok:false,error:"窗口桥未就绪"};',
  'return window.wh.call("memory",method,args||[]);}',
  'function paintList(buckets){',
  'var el=document.getElementById("list");',
  'if(!buckets||!buckets.length){el.innerHTML=\'<div class="empty">还没有记忆桶。记下跨会话经历（不等同于人格短记忆）。</div>\';return;}',
  'el.innerHTML=buckets.map(function(b){',
  'return \'<div class="card" data-id="\'+esc(b.id)+\'"><div class="t">\'+(b.pinned?"📌 ":"")+esc(b.name)+',
  '\' <span style="color:#8b949e;font-weight:400">\'+esc(b.type)+" · "+esc(b.domain)+"</span></div>"+',
  '\'<div class="b">\'+esc((b.body||"").slice(0,180))+"</div><div class=\\"ops\\">"+',
  '\'<button class="tiny\'+(b.pinned?" on":"")+\'" data-act="pin">\'+(b.pinned?"已钉":"钉住")+"</button>"+',
  '\'<button class="tiny" data-act="resolve">\'+(b.resolved?"取消解决":"标记解决")+"</button>"+',
  '\'<button class="tiny" data-act="archive">\'+(b.type==="archived"?"恢复":"归档")+"</button>"+',
  '\'<button class="tiny" data-act="reinforce">强化</button></div></div>\';}).join("");}',
  'function paint(snap){',
  'var p=snap.pulse||{};',
  'document.getElementById("meta").textContent=p.active+" 活跃 / "+p.archived+" 归档 / 钉 "+p.pinned;',
  'paintList((snap.buckets||[]).filter(function(b){return includeArchive||b.type!=="archived";}));',
  'document.getElementById("preview").textContent=(snap.preview&&snap.preview.breath)||"（空：组装时不占用 token）";}',
  'async function load(){var r=await call("snapshot");if(!r.ok){toast(r.error||"读取失败",false);return;}paint(r.result);}',
  'document.getElementById("reload").onclick=load;',
  'document.getElementById("breathBtn").onclick=async function(){var r=await call("breath");if(!r.ok){toast(r.error||"失败",false);return;}',
  'document.getElementById("preview").textContent=r.result.text||"（空）";toast("已 breath");};',
  'document.getElementById("holdBtn").onclick=async function(){',
  'var body=document.getElementById("body").value.trim();if(!body){toast("请填写正文",false);return;}',
  'var r=await call("hold",[{content:body,name:document.getElementById("name").value,domain:document.getElementById("domain").value,',
  'importance:Number(document.getElementById("importance").value||5),pinned:document.getElementById("pinned").checked}]);',
  'if(!r.ok){toast(r.error||"失败",false);return;}document.getElementById("body").value="";document.getElementById("name").value="";toast("已记下");load();};',
  'document.getElementById("searchBtn").onclick=async function(){',
  'var q=document.getElementById("q").value.trim();if(!q){load();return;}',
  'var r=await call("search",[{query:q,includeArchive:true}]);if(!r.ok){toast(r.error||"失败",false);return;}',
  'paintList((r.result||[]).map(function(h){return h.bucket;}));toast("命中 "+(r.result||[]).length);};',
  'document.getElementById("list").addEventListener("click",async function(e){',
  'var btn=e.target.closest("[data-act]");var row=e.target.closest(".card");if(!btn||!row)return;',
  'var id=row.getAttribute("data-id");var act=btn.getAttribute("data-act");var patch={};',
  'if(act==="pin")patch.pinned=btn.className.indexOf("on")<0;',
  'if(act==="resolve")patch.resolved=btn.textContent.indexOf("取消")<0;',
  'if(act==="archive"){if(btn.textContent.indexOf("恢复")>=0)patch.restore=true;else patch.archive=true;}',
  'if(act==="reinforce")patch.reinforce=true;',
  'var r=await call("trace",[id,patch]);if(!r.ok){toast(r.error||"失败",false);return;}toast("已更新");load();});',
  'load();',
  '</script></body></html>',
].join('');
