import { TREE_PANEL_CSS, TREE_PANEL_HTML } from './page-tree.js';

export const TIMER_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  'html,body{height:100%;margin:0;overflow:hidden}',
  'body{display:flex;flex-direction:column;background:#0d1117;color:#e6e6ef;',
  'font:13px/1.5 system-ui,"Segoe UI","Microsoft YaHei",sans-serif}',
  '.bar{flex:none;padding:10px 14px;border-bottom:1px solid #262634;background:#161b22;display:flex;gap:10px;align-items:center}',
  'h1{font:600 15px system-ui;margin:0}',
  '.meta{margin-left:auto;font-size:11px;color:#8b949e}',
  '.acts{display:flex;gap:6px;flex-wrap:wrap}',
  '.btn{background:#21262d;border:1px solid #30363d;color:#e6e6ef;border-radius:8px;padding:5px 10px;font:12px system-ui;cursor:pointer}',
  '.btn:hover{background:#30363d}',
  '.btn.primary{border-color:rgba(46,160,67,.5);color:#7ee787}',
  '.btn.danger{border-color:rgba(248,81,73,.45);color:#ff7b72}',
  '.main{flex:1;min-height:0;display:grid;grid-template-columns:1fr 340px;gap:0}',
  '.left{min-height:0;display:flex;flex-direction:column;border-right:1px solid #262634}',
  '.form{flex:none;padding:10px 14px;border-bottom:1px solid #262634;display:grid;gap:8px;grid-template-columns:1fr 1fr}',
  '.form label{font-size:11px;color:#8b949e;display:block;margin-bottom:3px}',
  '.form input,.form select{width:100%;box-sizing:border-box;background:#0d1117;border:1px solid #30363d;border-radius:6px;color:#e6e6ef;padding:6px 8px;font:12px ui-monospace,Consolas,monospace}',
  '.jobs{flex:1;min-height:0;overflow:auto;padding:8px 10px}',
  'table{width:100%;border-collapse:collapse;font-size:12px}',
  'th,td{padding:6px 8px;border-bottom:1px solid #21262d;text-align:left;vertical-align:middle}',
  'th{color:#8b949e;font-weight:600;position:sticky;top:0;background:#0d1117}',
  '.st{padding:2px 8px;border-radius:999px;font-size:10px;font-weight:600}',
  '.st.run{color:#7ee787;background:rgba(46,160,67,.15)}',
  '.st.stop{color:#8b949e;background:rgba(139,148,158,.12)}',
  '.st.pause{color:#d29922;background:rgba(210,153,34,.12)}',
  '.row-acts{display:flex;gap:4px;flex-wrap:wrap}',
  '.row-acts button{font-size:10px;padding:2px 6px}',
  '.right{min-height:0;display:flex;flex-direction:column}',
  '.tabs{flex:none;display:flex;border-bottom:1px solid #262634}',
  '.tab{flex:1;background:transparent;border:none;color:#8b949e;padding:8px;cursor:pointer;font:12px system-ui}',
  '.tab.on{color:#79c0ff;border-bottom:2px solid #388bfd}',
  '.panel{flex:1;min-height:0;overflow:auto;padding:10px 12px;font:11px/1.45 ui-monospace,Consolas,monospace;display:none}',
  '.panel.on{display:flex;flex-direction:column;min-height:0}',
  '.log{margin:0;white-space:pre-wrap;word-break:break-word}',
  '.log .err{color:#ff7b72}.log .warn{color:#d29922}',
  '.empty{color:#8b949e;text-align:center;padding:24px}',
  TREE_PANEL_CSS,
  '</style></head><body>',
  '<div class="bar"><h1>定时器</h1><div class="acts">',
  '<button type="button" class="btn primary" id="add">新建</button>',
  '<button type="button" class="btn" id="refresh">刷新</button>',
  '<button type="button" class="btn danger" id="stopAll">全部停止</button>',
  '</div><div class="meta" id="meta">—</div></div>',
  '<div class="main"><div class="left">',
  '<div class="form">',
  '<div><label>名称</label><input id="label" placeholder="heartbeat" /></div>',
  '<div><label>调度</label><select id="kind"><option value="interval">interval</option><option value="once">once</option><option value="cron">cron</option></select></div>',
  '<div><label>间隔/延迟(ms) 或 cron</label><input id="sched" value="60000" /></div>',
  '<div><label>模式</label><select id="mode"><option value="simple">单动作</option><option value="chain">事件链条</option><option value="tree">决策树</option></select></div>',
  '<div style="grid-column:1/-1"><label>动作/flow（JSON）</label><input id="payload" spellcheck="false" />',
  '</div></div>',
  '<div class="jobs"><table><thead><tr><th>任务</th><th>状态</th><th>下次</th><th>操作</th></tr></thead>',
  '<tbody id="rows"><tr><td colspan="4" class="empty">加载中…</td></tr></tbody></table></div>',
  '</div><div class="right">',
  '<div class="tabs">',
  '<button type="button" class="tab on" data-tab="logs">日志</button>',
  '<button type="button" class="tab" data-tab="runs">运行</button>',
  '<button type="button" class="tab" data-tab="tree">链路树</button>',
  '</div>',
  '<pre class="panel log on" id="logs">（日志）</pre>',
  '<pre class="panel log" id="runs">（运行记录）</pre>',
  '<div class="panel on" id="treePanel" style="padding:0">', TREE_PANEL_HTML, '</div>',
  '</div></div>',
  '<script>',
  '  var selectedFlow="";',
  '  function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;");}',
  '  function fmtTs(n){if(!n)return "—";return new Date(n).toLocaleTimeString();}',
  '  async function call(m,a){if(!window.wh||!window.wh.call)throw new Error("无 RPC");var r=await window.wh.call("timer",m,a||[]);if(!r.ok)throw new Error(r.error||"失败");return r.result;}',
  '  function stClass(s){return s==="running"?"run":s==="paused"?"pause":"stop";}',
  '  function parseJson(raw,fallback){try{return JSON.parse(raw);}catch(e){return fallback;}}',
  '  function defaultPayload(mode){',
  '    if(mode==="chain")return JSON.stringify({flow:{kind:"chain",steps:[',
  '      {id:"a",label:"心跳",action:{kind:"event",action:"timer/heartbeat",target:"a"}},',
  '      {id:"b",label:"汇总",delayMs:500,action:{kind:"event",action:"timer/summary",target:"b"}}',
  '    ]}});',
  '    if(mode==="tree")return JSON.stringify({flow:{kind:"tree",rootLabel:"检查",action:{kind:"event",action:"timer/check"},',
  '      branches:[{when:"ok",label:"成功路径",steps:[{label:"通知",action:{kind:"event",action:"timer/ok"}}]},',
  '      {when:"error",label:"失败兜底",action:{kind:"event",action:"timer/fallback"}}]}});',
  '    return JSON.stringify({action:"timer/heartbeat",target:"demo"});',
  '  }',
  '  document.getElementById("mode").onchange=function(){document.getElementById("payload").value=defaultPayload(this.value);};',
  '  document.getElementById("payload").value=defaultPayload("simple");',
  '  function isBranch(n){return /-br-\\d+-/.test(n.nodeKey);}',
  '  function isStep(n){return /-step-/.test(n.nodeKey)||/^chain-/.test(n.nodeKey);}',
  '  function renderTree(tree){',
  '    var wrap=document.getElementById("treeWrap"); if(!tree||!tree.nodes||!tree.nodes.length){wrap.innerHTML=\'<div class="empty">无追踪节点</div>\';return;}',
  '    var byId={}; tree.nodes.forEach(function(n){byId[n.id]=n;});',
  '    function nodeHtml(id){var n=byId[id]; if(!n)return "";',
  '      var kids=(n.childIds||[]).map(function(cid){return byId[cid];}).filter(Boolean);',
  '      var branches=kids.filter(isBranch), steps=kids.filter(isStep), rest=kids.filter(function(c){return !isBranch(c)&&!isStep(c);});',
  '      var meta=[]; if(n.scheduledAt)meta.push("计划 "+fmtTs(n.scheduledAt));',
  '      if(n.startedAt)meta.push("开始 "+fmtTs(n.startedAt)); if(n.endedAt)meta.push("结束 "+fmtTs(n.endedAt));',
  '      if(n.summary)meta.push(esc(n.summary)); if(n.error)meta.push(esc(n.error));',
  '      var body=\'<div class="t-node \'+esc(n.state)+\'"><div><b>\'+esc(n.label)+\'</b> <span class="t-meta">\'+esc(n.state)+\'</span></div>\'',
  '        +(meta.length?\'<div class="t-meta">\'+meta.join(" · ")+\'</div>\':"")+\'</div>\';',
  '      var kidsHtml="";',
  '      if(steps.length)kidsHtml+=\'<div class="t-kids t-seq">\'+steps.map(function(c){return nodeHtml(c.id);}).join("")+\'</div>\';',
  '      if(branches.length)kidsHtml+=\'<div class="t-fork">\'+branches.map(function(c){return nodeHtml(c.id);}).join("")+\'</div>\';',
  '      if(rest.length)kidsHtml+=\'<div class="t-kids">\'+rest.map(function(c){return nodeHtml(c.id);}).join("")+\'</div>\';',
  '      return body+kidsHtml;}',
  '    var root=tree.flowRun.rootTraceId; wrap.innerHTML=nodeHtml(root)||\'<div class="empty">无根节点</div>\';',
  '  }',
  '  async function loadTree(flowId){',
  '    if(!flowId){document.getElementById("treeWrap").innerHTML=\'<div class="empty">选择执行实例</div>\';return;}',
  '    var tree=await call("getTrace",[flowId]); renderTree(tree);',
  '  }',
  '  async function refresh(){',
  '    var inspect=await call("inspect"),jobs=await call("list"),logs=await call("logs",[{limit:120}]),',
  '      runs=await call("runs",[undefined,40]),flowRuns=await call("flowRuns",[undefined,40]);',
  '    document.getElementById("meta").textContent="任务 "+inspect.jobCount+" · 运行 "+inspect.runningJobs+" · 执行中 "+inspect.activeRuns;',
  '    var tb=document.getElementById("rows");',
  '    if(!jobs.length)tb.innerHTML=\'<tr><td colspan="4" class="empty">暂无任务</td></tr>\';',
  '    else tb.innerHTML=jobs.map(function(j){',
  '      var flowTag=j.flow?(j.flow.kind==="chain"?"链":"树"):"";',
  '      return "<tr><td><b>"+esc(j.label)+"</b> <span style=\\"color:#79c0ff;font-size:10px\\">"+flowTag+"</span>"',
  '        +"<div style=\\"color:#8b949e;font-size:10px\\">"+esc(j.id)+"</div></td>"',
  '        +"<td><span class=\\"st "+stClass(j.state)+"\\">"+esc(j.state)+"</span></td><td>"+fmtTs(j.nextFireAt)+"</td>"',
  '        +"<td><div class=\\"row-acts\\">"',
  '        +\'<button type="button" class="btn" data-a="start" data-id="\'+esc(j.id)+\'">启</button>\'',
  '        +\'<button type="button" class="btn" data-a="stop" data-id="\'+esc(j.id)+\'">停</button>\'',
  '        +\'<button type="button" class="btn" data-a="trigger" data-id="\'+esc(j.id)+\'">触发</button>\'',
  '        +(j.activeRunId?\'<button type="button" class="btn danger" data-a="cancel" data-run="\'+esc(j.activeRunId)+\'">打断</button>\':"")',
  '        +\'<button type="button" class="btn danger" data-a="remove" data-id="\'+esc(j.id)+\'">删</button></div></td></tr>";}).join("");',
  '    document.getElementById("logs").innerHTML=logs.map(function(l){',
  '      return "<div class=\\""+(l.level==="error"?"err":l.level==="warn"?"warn":"")+"\\">["+fmtTs(l.at)+"] "+esc(l.message)+"</div>";',
  '    }).join("")||"（无）";',
  '    document.getElementById("runs").innerHTML=runs.map(function(r){',
  '      return "["+fmtTs(r.startedAt)+"] "+esc(r.jobId)+" "+esc(r.state);}).join("\\n")||"（无）";',
  '    var pick=document.getElementById("flowPick"), prev=selectedFlow||pick.value;',
  '    pick.innerHTML=\'<option value="">（选择实例）</option>\'+flowRuns.slice().reverse().map(function(f){',
  '      return \'<option value="\'+esc(f.id)+\'">\'+fmtTs(f.startedAt)+" "+esc(f.jobId)+" "+esc(f.state)+\'</option>\';}).join("");',
  '    if(prev)pick.value=prev; selectedFlow=pick.value; await loadTree(selectedFlow);',
  '  }',
  '  async function addJob(body){await call("create",[body]); await refresh();}',
  '  document.getElementById("add").onclick=function(){',
  '    var kind=document.getElementById("kind").value,sched=document.getElementById("sched").value.trim();',
  '    var mode=document.getElementById("mode").value,payload=parseJson(document.getElementById("payload").value,{});',
  '    var schedule={kind:kind};',
  '    if(kind==="cron")schedule.cron=sched; else if(kind==="once")schedule.delayMs=Number(sched)||5000; else schedule.intervalMs=Number(sched)||60000;',
  '    var body={label:document.getElementById("label").value||"job",schedule:schedule,autostart:true};',
  '    if(payload.flow)body.flow=payload.flow; else {',
  '      body.action={kind:"event",action:payload.action||"timer/tick",target:payload.target||"demo",payload:payload.payload};',
  '      if(mode==="chain"&&!payload.flow)body.flow={kind:"chain",steps:[{label:"步骤1",action:body.action}]};',
  '    }',
  '    addJob(body).catch(function(e){alert(e.message||e);});',
  '  };',
  '  document.getElementById("demoChain").onclick=function(){',
  '    addJob({label:"demo-chain",schedule:{kind:"once",delayMs:800},autostart:true,',
  '      flow:{kind:"chain",steps:[{label:"A",action:{kind:"event",action:"timer/a"}},{label:"B",delayMs:300,action:{kind:"event",action:"timer/b"}}]}}',
  '    }).catch(function(e){alert(e.message||e);});};',
  '  document.getElementById("demoTree").onclick=function(){',
  '    addJob({label:"demo-tree",schedule:{kind:"once",delayMs:800},autostart:true,',
  '      flow:{kind:"tree",rootLabel:"根",action:{kind:"event",action:"timer/root"},',
  '      branches:[{when:"ok",label:"成功",action:{kind:"event",action:"timer/ok"}},{when:"error",label:"失败",action:{kind:"event",action:"timer/err"}}]}}',
  '    }).catch(function(e){alert(e.message||e);});};',
  '  document.getElementById("flowPick").onchange=function(){selectedFlow=this.value; loadTree(selectedFlow).catch(function(){});};',
  '  document.getElementById("refresh").onclick=function(){refresh().catch(function(e){alert(e.message||e);});};',
  '  document.getElementById("stopAll").onclick=function(){call("stopAll",[]).then(refresh);};',
  '  document.getElementById("rows").onclick=function(e){',
  '    var btn=e.target.closest("button[data-a]"); if(!btn)return;',
  '    var a=btn.getAttribute("data-a"),id=btn.getAttribute("data-id"),run=btn.getAttribute("data-run");',
  '    (a==="cancel"?call("cancelRun",[run]):a==="remove"?call("remove",[id]):call(a,[id])).then(refresh).catch(function(err){alert(err.message||err);});',
  '  };',
  '  document.querySelectorAll(".tab").forEach(function(t){',
  '    t.onclick=function(){document.querySelectorAll(".tab").forEach(function(x){x.classList.remove("on");});',
  '      t.classList.add("on"); var k=t.getAttribute("data-tab");',
  '      document.getElementById("logs").classList.toggle("on",k==="logs");',
  '      document.getElementById("runs").classList.toggle("on",k==="runs");',
  '      document.getElementById("treePanel").classList.toggle("on",k==="tree");',
  '      document.getElementById("logs").style.display=k==="logs"?"block":"none";',
  '      document.getElementById("runs").style.display=k==="runs"?"block":"none";',
  '      document.getElementById("treePanel").style.display=k==="tree"?"flex":"none";',
  '    };});',
  '  document.getElementById("treePanel").classList.remove("on");',
  '  refresh().catch(function(e){document.getElementById("rows").innerHTML=\'<tr><td colspan="4" class="empty">\'+esc(e.message||e)+"</td></tr>";});',
  '  setInterval(function(){refresh().catch(function(){});},1400);',
  '</script></body></html>',
].join('');
