/** Agent 弹窗：live 实例列表（id · sessionId），经 ui.rpc agent.list 刷新。 */
export const AGENT_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  'html,body{height:100%;margin:0;overflow:hidden}',
  'body{display:flex;flex-direction:column;background:#16161e;color:#e6e6ef;',
  'font:13px/1.55 system-ui,"Segoe UI","Microsoft YaHei",sans-serif}',
  '.bar{flex:none;padding:10px 14px;border-bottom:1px solid #262634}',
  'h1{font:600 14px system-ui;margin:0 0 4px}',
  '.hint{margin:0;font-size:12px;color:#a8a8bd;line-height:1.5}',
  '#list{flex:1;min-height:0;overflow:auto;padding:10px 14px 16px}',
  '.row{padding:10px 12px;border:1px solid #262634;border-radius:10px;margin-bottom:8px;background:#1a1a24}',
  '.id{font:600 12px ui-monospace,Consolas,monospace;color:#d2a8ff}',
  '.sid{margin-top:4px;font:11px ui-monospace,Consolas,monospace;color:#8b949e;word-break:break-all}',
  '.empty{color:#8b949e;text-align:center;margin-top:20vh;font-size:13px}',
  '.err{color:#ffb4ae;text-align:center;margin-top:20vh;font-size:13px}',
  '</style></head><body>',
  '<div class="bar"><h1>Live agents</h1>',
  '<p class="hint">spawn / stop 经服务；App 连续对话应复用同一 agentId。</p></div>',
  '<div id="list"><div class="empty">加载中…</div></div>',
  '<script>',
  'const list=document.getElementById("list");',
  'function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}',
  'async function refresh(){',
  'if(!window.wh||!window.wh.call){list.innerHTML=\'<div class="err">窗口桥未就绪</div>\';return;}',
  'try{',
  'const r=await window.wh.call("agent","list",[]);',
  'if(!r.ok){',
  'const msg=String(r.error||"读取失败");',
  'list.innerHTML=\'<div class="err">\'+esc(msg.indexOf("不可用")>=0?"agent 服务未装入":msg)+"</div>";return;}',
  'const rows=(r.result||[]);',
  'if(!rows.length){list.innerHTML=\'<div class="empty">暂无 live 实例。App 发首条消息或 agentLoop.run 后会 spawn。</div>\';return;}',
  'list.innerHTML=rows.map(function(row){',
  'return \'<div class="row"><div class="id">\'+esc(row.id)+\'</div><div class="sid">session \'+esc(row.sessionId)+"</div></div>";',
  '}).join("");',
  '}catch(e){list.innerHTML=\'<div class="err">\'+esc(e)+"</div>";}}',
  'refresh();setInterval(refresh,1200);',
  '</script></body></html>',
].join('');
