export const PERSONA_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  'html,body{height:100%;margin:0;overflow:hidden}',
  'body{display:flex;flex-direction:column;background:#0d1117;color:#e6e6ef;',
  'font:13px/1.5 system-ui,"Segoe UI","Microsoft YaHei",sans-serif}',
  '.bar{flex:none;padding:8px 14px;border-bottom:1px solid #262634;display:flex;gap:8px;align-items:center}',
  'h1{font:600 14px system-ui;margin:0}',
  '.meta{color:#8b949e;font-size:11px}',
  '.ghost,.pri{border-radius:8px;padding:4px 10px;font:12px system-ui;cursor:pointer}',
  '.ghost{margin-left:auto;background:transparent;border:1px solid #333;color:#a8a8bd}',
  '.ghost:hover{border-color:#4a6aa0;color:#79c0ff}',
  '.pri{background:linear-gradient(135deg,#2ea043,#238636);border:none;color:#fff}',
  '.cols{flex:1;min-height:0;display:flex}',
  '.col{flex:1;min-width:0;display:flex;flex-direction:column;border-right:1px solid #262634}',
  '.col:last-child{border-right:none}',
  '.col h2{flex:none;margin:0;padding:8px 12px;font:600 12px system-ui;color:#a8a8bd;border-bottom:1px solid #262634}',
  '.pad{flex:1;min-height:0;overflow:auto;padding:10px 12px 16px}',
  'label{display:block;font-size:11px;color:#8b949e;margin:8px 0 4px}',
  'input,textarea{width:100%;box-sizing:border-box;background:#16161e;border:1px solid #2c2c3e;border-radius:8px;',
  'color:#e6e6ef;padding:7px 10px;font:13px/1.5 system-ui;outline:none}',
  'textarea{min-height:88px;resize:vertical}',
  '#personality{min-height:140px}',
  'input:focus,textarea:focus{border-color:#4a6aa0}',
  '.row{display:flex;gap:6px;margin-top:8px}',
  '.row input{flex:1}',
  '.mem{padding:8px 0;border-bottom:1px solid #1c1c28}',
  '.mem .t{color:#c9d1d9;word-break:break-word}',
  '.mem .ops{margin-top:4px;display:flex;gap:6px}',
  '.tiny{background:transparent;border:1px solid #333;color:#8b949e;border-radius:6px;padding:2px 8px;font:11px system-ui;cursor:pointer}',
  '.tiny.on{color:#e6c07b;border-color:rgba(230,192,123,.4)}',
  '.preview{flex:none;max-height:28%;overflow:auto;border-top:1px solid #262634;padding:8px 12px;background:#16161e;',
  'white-space:pre-wrap;word-break:break-word;font:11px/1.5 ui-monospace,Consolas,monospace;color:#a8a8bd}',
  '.empty,.err{color:#8b949e;padding:12px 0}',
  '.err{color:#ffb4ae}',
  '.toast{position:fixed;left:50%;bottom:16px;transform:translateX(-50%);background:#21262d;border:1px solid #30363d;',
  'color:#7ee787;border-radius:8px;padding:6px 12px;font:12px system-ui;opacity:0;pointer-events:none;transition:opacity .15s}',
  '.toast.on{opacity:1}',
  '</style></head><body>',
  '<div class="bar"><h1>人格</h1><span class="meta" id="meta">—</span>',
  '<button class="ghost" type="button" id="reload">刷新</button>',
  '<button class="pri" type="button" id="save">保存人格/习惯</button></div>',
  '<div class="cols">',
  '<section class="col"><h2>人格与习惯</h2><div class="pad">',
  '<label>名称</label><input id="name" />',
  '<label>人格</label><textarea id="personality" placeholder="这个助手是谁、怎么说话、做事原则"></textarea>',
  '<label>习惯（一行一条）</label><textarea id="habits" placeholder="先看工作区再改文件"></textarea>',
  '</div></section>',
  '<section class="col"><h2>相关记忆</h2><div class="pad">',
  '<div class="row"><input id="memIn" placeholder="记一条给后续对话用的事实" /><button class="pri" type="button" id="memAdd">记下</button></div>',
  '<div id="mems"></div>',
  '</div></section>',
  '</div>',
  '<pre class="preview" id="preview">模型将看到的片段…</pre>',
  '<div class="toast" id="toast"></div>',
  '<script>',
  'function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;");}',
  'let toastTimer;',
  'function toast(msg,ok){var el=document.getElementById("toast");el.textContent=msg;el.style.color=ok===false?"#ffb4ae":"#7ee787";',
  'el.className="toast on";clearTimeout(toastTimer);toastTimer=setTimeout(function(){el.className="toast";},1200);}',
  'async function call(method,args){',
  'if(!window.wh||!window.wh.call)return {ok:false,error:"窗口桥未就绪"};',
  'return window.wh.call("persona",method,args||[]);}',
  'function paint(snap){',
  'const p=snap.profile||{};',
  'document.getElementById("name").value=p.name||"";',
  'document.getElementById("personality").value=p.personality||"";',
  'document.getElementById("habits").value=(p.habits||[]).join("\\n");',
  'const agents=(snap.agents||[]).map(function(a){return a.id.slice(0,8);}).join(", ");',
  'document.getElementById("meta").textContent=(agents?agents+" · ":"")+(p.memories||[]).length+" 条记忆";',
  'const mems=document.getElementById("mems");',
  'const rows=p.memories||[];',
  'if(!rows.length){mems.innerHTML=\'<div class="empty">还没有记忆。记下用户偏好、项目约定、未完成事项。</div>\';}',
  'else mems.innerHTML=rows.map(function(m){',
  'return \'<div class="mem" data-id="\'+esc(m.id)+\'"><div class="t">\'+esc(m.text)+\'</div><div class="ops">\'+',
  '\'<button class="tiny\'+(m.pinned?" on":"")+\'" data-act="pin">\'+(m.pinned?"已钉":"钉住")+"</button>"+',
  '\'<button class="tiny" data-act="del">删除</button></div></div>\';}).join("");',
  'const prev=snap.preview||{};',
  'document.getElementById("preview").textContent=[prev.core,prev.memory].filter(Boolean).join("\\n\\n")||"（空：组装时不占用 token）";}',
  'async function load(){const r=await call("snapshot");if(!r.ok){toast(r.error||"读取失败",false);return;}paint(r.result);}',
  'async function save(){',
  'const habits=document.getElementById("habits").value.split(/\\r?\\n/).map(function(s){return s.trim();}).filter(Boolean);',
  'const r=await call("save",[{name:document.getElementById("name").value,personality:document.getElementById("personality").value,habits:habits}]);',
  'if(!r.ok){toast(r.error||"保存失败",false);return;}paint(r.result);toast("已保存");}',
  'document.getElementById("save").onclick=save;',
  'document.getElementById("reload").onclick=load;',
  'document.getElementById("memAdd").onclick=async function(){',
  'const t=document.getElementById("memIn").value.trim();if(!t)return;',
  'const r=await call("addMemory",[{text:t}]);if(!r.ok){toast(r.error||"失败",false);return;}',
  'document.getElementById("memIn").value="";paint(r.result);toast("已记下");};',
  'document.getElementById("mems").addEventListener("click",async function(e){',
  'const btn=e.target.closest("[data-act]");const row=e.target.closest(".mem");if(!btn||!row)return;',
  'const id=row.getAttribute("data-id");const act=btn.getAttribute("data-act");',
  'const r=act==="del"?await call("removeMemory",[id]):await call("pinMemory",[id,btn.className.indexOf("on")<0]);',
  'if(!r.ok){toast(r.error||"失败",false);return;}paint(r.result);});',
  'load();',
  '</script></body></html>',
].join('');
