/** 硅灵（AI格）管理弹窗 */
export const PERSONA_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  ':root{--bg:#0a0e14;--panel:#121820;--line:#243044;--text:#e8ecf4;--muted:#8b9cb3;',
  '--accent:#6ec1ff;--accent2:#9b7bff;--ok:#5fd97a;--warn:#e6c07b}',
  'html,body{height:100%;margin:0;overflow:hidden}',
  'body{display:flex;flex-direction:column;background:var(--bg);color:var(--text);',
  'font:13px/1.55 system-ui,"Segoe UI","Microsoft YaHei",sans-serif}',
  '.hero{flex:none;padding:14px 16px 12px;border-bottom:1px solid var(--line);',
  'background:linear-gradient(135deg,rgba(110,193,255,.08),rgba(155,123,255,.06) 55%,transparent)}',
  '.hero-top{display:flex;align-items:flex-start;gap:12px;flex-wrap:wrap}',
  '.mark{width:40px;height:40px;border-radius:12px;display:flex;align-items:center;justify-content:center;',
  'font:700 18px system-ui;color:#fff;background:linear-gradient(145deg,#4a9eff,#7b5cff);',
  'box-shadow:0 4px 18px rgba(74,158,255,.25)}',
  '.brand h1{margin:0;font:700 18px system-ui;letter-spacing:.12em}',
  '.def{margin:4px 0 0;font-size:12px;color:var(--muted)}',
  '.def strong{color:var(--accent);font-weight:600}',
  '.callout{flex:1;min-width:220px;margin:10px 0 0;padding:8px 12px;border-radius:10px;',
  'border:1px solid rgba(110,193,255,.22);background:rgba(110,193,255,.06);font-size:12px;line-height:1.6;color:#c5d4e8}',
  '.toolbar{flex:none;display:flex;align-items:center;gap:8px;padding:8px 16px;border-bottom:1px solid var(--line);',
  'background:var(--panel)}',
  '.meta{margin-right:auto;font-size:11px;color:var(--muted);font-family:ui-monospace,Consolas,monospace}',
  '.ghost,.pri{border-radius:8px;padding:5px 12px;font:12px system-ui;cursor:pointer;transition:.15s}',
  '.ghost{background:transparent;border:1px solid var(--line);color:var(--muted)}',
  '.ghost:hover{border-color:var(--accent);color:var(--accent)}',
  '.pri{background:linear-gradient(135deg,#2ea043,#1f7a34);border:none;color:#fff;font-weight:600}',
  '.pri:hover{filter:brightness(1.08)}',
  '.cols{flex:1;min-height:0;display:grid;grid-template-columns:repeat(3,minmax(0,1fr))}',
  '.col{min-width:0;display:flex;flex-direction:column;border-right:1px solid var(--line);background:var(--panel)}',
  '.col:last-child{border-right:none}',
  '.col h2{flex:none;margin:0;padding:10px 14px;font:600 12px system-ui;color:var(--accent);',
  'border-bottom:1px solid var(--line);letter-spacing:.04em}',
  '.col h2 span{display:block;font:400 10px system-ui;color:var(--muted);margin-top:2px;letter-spacing:0}',
  '.pad{flex:1;min-height:0;overflow:auto;padding:12px 14px 18px}',
  'label{display:block;font-size:11px;color:var(--muted);margin:10px 0 5px}',
  'label:first-child{margin-top:0}',
  'input,textarea{width:100%;box-sizing:border-box;background:#0d1219;border:1px solid var(--line);border-radius:9px;',
  'color:var(--text);padding:8px 10px;font:13px/1.5 system-ui;outline:none;transition:border-color .15s}',
  'textarea{min-height:76px;resize:vertical}',
  '#personality{min-height:128px}',
  'input:focus,textarea:focus{border-color:rgba(110,193,255,.55);box-shadow:0 0 0 2px rgba(110,193,255,.12)}',
  'input::placeholder,textarea::placeholder{color:#5c6b80}',
  '.row{display:flex;gap:8px;margin-top:10px}',
  '.row input{flex:1}',
  '.mem{padding:10px 0;border-bottom:1px solid rgba(36,48,68,.8)}',
  '.mem:last-child{border-bottom:none}',
  '.mem .t{color:#d7e0ee;word-break:break-word;line-height:1.5}',
  '.mem .ops{margin-top:6px;display:flex;gap:6px}',
  '.tiny{background:transparent;border:1px solid var(--line);color:var(--muted);border-radius:7px;',
  'padding:3px 9px;font:11px system-ui;cursor:pointer}',
  '.tiny:hover{border-color:var(--accent);color:var(--accent)}',
  '.tiny.on{color:var(--warn);border-color:rgba(230,192,123,.45);background:rgba(230,192,123,.08)}',
  '.preview-wrap{flex:none;border-top:1px solid var(--line);background:#0d1219}',
  '.preview-head{padding:6px 14px;font-size:10px;font-weight:600;color:var(--muted);letter-spacing:.06em;',
  'border-bottom:1px solid var(--line)}',
  '.preview{margin:0;max-height:24%;min-height:72px;overflow:auto;padding:10px 14px;',
  'white-space:pre-wrap;word-break:break-word;font:11px/1.55 ui-monospace,Consolas,monospace;color:#9aa8bd}',
  '.empty,.err{color:var(--muted);padding:12px 0;font-size:12px;line-height:1.6}',
  '.toast{position:fixed;left:50%;bottom:18px;transform:translateX(-50%);background:#1a2330;border:1px solid var(--line);',
  'color:var(--ok);border-radius:10px;padding:8px 14px;font:12px system-ui;opacity:0;pointer-events:none;',
  'transition:opacity .15s;box-shadow:0 8px 24px rgba(0,0,0,.35)}',
  '.toast.on{opacity:1}',
  '</style></head><body>',
  '<header class="hero">',
  '<div class="hero-top">',
  '<div class="mark" aria-hidden="true">硅</div>',
  '<div class="brand"><h1>硅灵</h1><p class="def"><strong>AI格</strong> · AI 的人格底色、说话方式与协作准则</p></div>',
  '</div>',
  '<p class="callout">「硅灵」是本助手的可编辑人格档案：名称、风格、硅格正文、习惯与记忆会拼进模型上下文，塑造稳定一致的 AI 格。</p>',
  '</header>',
  '<div class="toolbar"><span class="meta" id="meta">—</span>',
  '<button class="ghost" type="button" id="reload">刷新</button>',
  '<button class="pri" type="button" id="save">保存硅灵</button></div>',
  '<div class="cols">',
  '<section class="col"><h2>身份档案<span>名称 · 角色 · 风格</span></h2><div class="pad">',
  '<label>硅灵名称</label><input id="name" placeholder="如：小织、Aria" />',
  '<label>角色定位</label><input id="role" placeholder="编程搭档 / 研究助理" />',
  '<label>说话风格</label><input id="voiceStyle" placeholder="简洁直接、技术文档风…" />',
  '<label>语气</label><input id="tone" placeholder="冷静 / 热情…" />',
  '<label>性格特质（逗号分隔）</label><input id="traits" placeholder="好奇, 直接, 耐心" />',
  '<label>一句话自述</label><input id="tagline" placeholder="开场对齐用的极短自我介绍" />',
  '<label>边界</label><textarea id="boundaries" placeholder="不做的事、需先确认的场景"></textarea>',
  '</div></section>',
  '<section class="col"><h2>硅格正文<span>AI格核心 · 第一人称</span></h2><div class="pad">',
  '<label>硅格正文</label><textarea id="personality" placeholder="第一人称：我是谁、如何协作、遇到不确定时怎么做"></textarea>',
  '<label>工作习惯（一行一条）</label><textarea id="habits" placeholder="先看工作区再改文件"></textarea>',
  '</div></section>',
  '<section class="col"><h2>相关记忆<span>跨轮次事实与偏好</span></h2><div class="pad">',
  '<div class="row"><input id="memIn" placeholder="记下用户偏好、项目约定…" /><button class="pri" type="button" id="memAdd">记下</button></div>',
  '<div id="mems"></div>',
  '</div></section>',
  '</div>',
  '<div class="preview-wrap"><div class="preview-head">模型可见预览 · prompt-context 组装片段</div>',
  '<pre class="preview" id="preview">加载中…</pre></div>',
  '<div class="toast" id="toast"></div>',
  '<script>',
  'function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;");}',
  'let toastTimer;',
  'function toast(msg,ok){var el=document.getElementById("toast");el.textContent=msg;el.style.color=ok===false?"#ffb4ae":"#5fd97a";',
  'el.className="toast on";clearTimeout(toastTimer);toastTimer=setTimeout(function(){el.className="toast";},1400);}',
  'async function call(method,args){',
  'if(!window.wh||!window.wh.call)return {ok:false,error:"窗口桥未就绪"};',
  'return window.wh.call("persona",method,args||[]);}',
  'function paint(snap){',
  'const p=snap.profile||{};const m=p.meta||{};',
  'document.getElementById("name").value=p.name||"";',
  'document.getElementById("role").value=m.role||"";',
  'document.getElementById("voiceStyle").value=m.voiceStyle||"";',
  'document.getElementById("tone").value=m.tone||"";',
  'document.getElementById("traits").value=(m.traits||[]).join(", ");',
  'document.getElementById("tagline").value=m.tagline||"";',
  'document.getElementById("boundaries").value=m.boundaries||"";',
  'document.getElementById("personality").value=p.personality||"";',
  'document.getElementById("habits").value=(p.habits||[]).join("\\n");',
  'const agents=(snap.agents||[]).map(function(a){return a.id.slice(0,8);}).join(", ");',
  'document.getElementById("meta").textContent=(agents?agents+" · ":"")+(p.memories||[]).length+" 条记忆";',
  'const mems=document.getElementById("mems");',
  'const rows=p.memories||[];',
  'if(!rows.length){mems.innerHTML=\'<div class="empty">还没有记忆。可记下用户偏好、项目约定或未完成事项；钉住后每轮都会带上。</div>\';}',
  'else mems.innerHTML=rows.map(function(m){',
  'return \'<div class="mem" data-id="\'+esc(m.id)+\'"><div class="t">\'+esc(m.text)+\'</div><div class="ops">\'+',
  '\'<button class="tiny\'+(m.pinned?" on":"")+\'" data-act="pin">\'+(m.pinned?"已钉":"钉住")+"</button>"+',
  '\'<button class="tiny" data-act="del">删除</button></div></div>\';}).join("");',
  'const prev=snap.preview||{};',
  'document.getElementById("preview").textContent=[prev.core,prev.memory].filter(Boolean).join("\\n\\n")||"（空：未定制硅灵时不占用 token）";}',
  'async function load(){const r=await call("snapshot");if(!r.ok){toast(r.error||"读取失败",false);return;}paint(r.result);}',
  'async function save(){',
  'const habits=document.getElementById("habits").value.split(/\\r?\\n/).map(function(s){return s.trim();}).filter(Boolean);',
  'const traits=document.getElementById("traits").value.split(/[,，、]/).map(function(s){return s.trim();}).filter(Boolean);',
  'const patch={name:document.getElementById("name").value,personality:document.getElementById("personality").value,habits:habits,',
  'meta:{role:document.getElementById("role").value,voiceStyle:document.getElementById("voiceStyle").value,',
  'tone:document.getElementById("tone").value,traits:traits,tagline:document.getElementById("tagline").value,',
  'boundaries:document.getElementById("boundaries").value}};',
  'const r=await call("configure",[patch]);',
  'if(!r.ok){toast(r.error||"保存失败",false);return;}paint(r.result);toast("硅灵已保存");}',
  'document.getElementById("save").onclick=save;',
  'document.getElementById("reload").onclick=load;',
  'document.getElementById("memAdd").onclick=async function(){',
  'const t=document.getElementById("memIn").value.trim();if(!t)return;',
  'const r=await call("addMemory",[{text:t}]);if(!r.ok){toast(r.error||"失败",false);return;}',
  'document.getElementById("memIn").value="";paint(r.result);toast("已记下");};',
  'document.getElementById("mems").addEventListener("click",async function(e){',
  'const btn=e.target.closest("[data-act]");const row=e.target.closest(".mem");if(!btn||!row)return;',
  'const id=row.getAttribute("data-id");const act=btn.getAttribute("data-act");',
  'const r=act==="del"?await call("removeMemory",[id]):await call("pinMemory",[id,btn.className.indexOf("on")<0]);',
  'if(!r.ok){toast(r.error||"失败",false);return;}paint(r.result);});',
  'load();',
  '</script></body></html>',
].join('');
