/** 硅灵：多份 soul.md 式身份基线，不管理记忆 */
export const PERSONA_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  ':root{--bg:#0a0e14;--panel:#121820;--line:#243044;--text:#e8ecf4;--muted:#8b9cb3;',
  '--accent:#6ec1ff;--ok:#5fd97a;--warn:#e6c07b;--err:#ffb4ae}',
  'html,body{height:100%;margin:0;overflow:hidden}',
  'body{display:flex;flex-direction:column;background:var(--bg);color:var(--text);',
  'font:13px/1.55 system-ui,"Segoe UI","Microsoft YaHei",sans-serif}',
  '.hero{flex:none;padding:14px 16px 12px;border-bottom:1px solid var(--line);',
  'background:linear-gradient(135deg,rgba(110,193,255,.08),rgba(155,123,255,.06) 55%,transparent)}',
  '.hero-top{display:flex;align-items:flex-start;gap:12px}',
  '.mark{width:40px;height:40px;border-radius:12px;display:flex;align-items:center;justify-content:center;',
  'font:700 18px system-ui;color:#fff;background:linear-gradient(145deg,#4a9eff,#7b5cff);',
  'box-shadow:0 4px 18px rgba(74,158,255,.25)}',
  '.brand h1{margin:0;font:700 18px system-ui;letter-spacing:.12em}',
  '.def{margin:4px 0 0;font-size:12px;color:var(--muted)}',
  '.def strong{color:var(--accent);font-weight:600}',
  '.callout{margin:10px 0 0;padding:8px 12px;border-radius:10px;',
  'border:1px solid rgba(110,193,255,.22);background:rgba(110,193,255,.06);font-size:12px;line-height:1.6;color:#c5d4e8}',
  '.body{flex:1;min-height:0;display:flex}',
  '.rail{flex:none;width:220px;min-width:180px;display:flex;flex-direction:column;border-right:1px solid var(--line);background:#0d1219}',
  '.rail-h{flex:none;display:flex;align-items:center;justify-content:space-between;padding:10px 12px 8px;',
  'font:600 12px system-ui;color:var(--text)}',
  '.rail-h b{font:600 11px system-ui;color:var(--muted);background:var(--panel);border-radius:999px;padding:1px 7px}',
  '#p-list{flex:1;min-height:0;overflow:auto;padding:4px 8px 10px}',
  '.p-empty{color:var(--muted);text-align:center;padding:24px 10px;font-size:12px}',
  '.p-item{position:relative;padding:9px 10px;border-radius:10px;margin-bottom:4px;cursor:pointer;border:1px solid transparent}',
  '.p-item:hover{background:var(--panel)}',
  '.p-item.active{border-color:rgba(110,193,255,.55);background:rgba(110,193,255,.1)}',
  '.p-title{font:600 12.5px/1.35 system-ui;color:var(--text);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.p-meta{margin-top:3px;font:11px system-ui;color:var(--muted)}',
  '.rail-new{flex:none;margin:0 8px 10px;width:calc(100% - 16px)}',
  '.main{flex:1;min-width:0;display:flex;flex-direction:column;min-height:0}',
  '.toolbar{flex:none;display:flex;align-items:center;gap:8px;padding:8px 14px;border-bottom:1px solid var(--line);background:var(--panel)}',
  '#pname{flex:1;min-width:120px;max-width:280px;background:#0d1219;border:1px solid var(--line);border-radius:8px;',
  'color:var(--text);padding:6px 10px;font:13px system-ui;outline:none}',
  '#pname:focus{border-color:rgba(110,193,255,.55)}',
  '.count{margin-left:auto;font:600 12px ui-monospace,Consolas,monospace;color:var(--muted);min-width:88px;text-align:right}',
  '.count.warn{color:var(--warn)}.count.over{color:var(--err)}',
  '.ghost,.pri{border-radius:8px;padding:5px 12px;font:12px system-ui;cursor:pointer;transition:.15s}',
  '.ghost{background:transparent;border:1px solid var(--line);color:var(--muted)}',
  '.ghost:hover{border-color:var(--accent);color:var(--accent)}',
  '.pri{background:linear-gradient(135deg,#2ea043,#1f7a34);border:none;color:#fff;font-weight:600}',
  '.pri:hover{filter:brightness(1.08)}',
  '.pri:disabled{opacity:.4;cursor:default;filter:none}',
  '.danger{border-color:#5c2a2a;color:var(--err)}',
  '.danger:hover{border-color:var(--err);color:var(--err)}',
  '.editor{flex:1;min-height:0;display:flex;flex-direction:column;padding:12px 14px 14px}',
  '.editor label{flex:none;font-size:11px;color:var(--muted);margin-bottom:6px}',
  '#soul{flex:1;min-height:0;width:100%;box-sizing:border-box;resize:none;background:#0d1219;border:1px solid var(--line);',
  'border-radius:10px;color:var(--text);padding:12px 14px;font:13px/1.55 ui-monospace,Consolas,monospace;outline:none}',
  '#soul:focus{border-color:rgba(110,193,255,.55);box-shadow:0 0 0 2px rgba(110,193,255,.12)}',
  '.hint{flex:none;margin-top:8px;font-size:11px;color:var(--muted)}',
  '.toast{position:fixed;left:50%;bottom:18px;transform:translateX(-50%);background:#1a2330;border:1px solid var(--line);',
  'color:var(--ok);border-radius:10px;padding:8px 14px;font:12px system-ui;opacity:0;pointer-events:none;',
  'transition:opacity .15s;box-shadow:0 8px 24px rgba(0,0,0,.35)}',
  '.toast.on{opacity:1}',
  '</style></head><body>',
  '<header class="hero"><div class="hero-top">',
  '<div class="mark" aria-hidden="true">硅</div>',
  '<div class="brand"><h1>硅灵</h1><p class="def"><strong>身份基线</strong> · 恒定人格核心（soul.md），不是记忆系统</p></div>',
  '</div>',
  '<p class="callout">每份硅灵是一段写入模型 system 的身份基线。跨会话经历请用 memory 插件。可保存多份并切换；AI 用 persona_create / persona_update / persona_switch。</p>',
  '</header>',
  '<div class="body">',
  '<aside class="rail"><div class="rail-h"><span>硅灵<b id="p-count">0</b></span></div>',
  '<div id="p-list"></div>',
  '<button class="ghost rail-new" type="button" id="neu">新建</button></aside>',
  '<div class="main">',
  '<div class="toolbar">',
  '<input id="pname" placeholder="名称，如：小织" spellcheck="false" />',
  '<span class="count" id="count">0 / 3000</span>',
  '<button class="ghost" type="button" id="reload">刷新</button>',
  '<button class="ghost danger" type="button" id="del">删除</button>',
  '<button class="pri" type="button" id="save">保存硅灵</button>',
  '</div>',
  '<div class="editor"><label>身份基线 · 模型可见的 SystemPrompt</label>',
  '<textarea id="soul" placeholder="# 我是谁\\n名称：\\n\\n# 硅格\\n我是…" spellcheck="false"></textarea>',
  '<p class="hint" id="hint">登记为 prompt-context section <code>persona:core</code>。上限 3000 字。</p>',
  '</div></div></div>',
  '<div class="toast" id="toast"></div>',
  '<script>',
  'const LIMIT=3000;',
  'function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;");}',
  'function chars(s){return Array.from(String(s||"")).length;}',
  'let toastTimer,rows=[],activeId=null,limit=LIMIT;',
  'function toast(msg,ok){var el=document.getElementById("toast");el.textContent=msg;el.style.color=ok===false?"#ffb4ae":"#5fd97a";',
  'el.className="toast on";clearTimeout(toastTimer);toastTimer=setTimeout(function(){el.className="toast";},1400);}',
  'async function call(method,args){',
  'if(!window.wh||!window.wh.call)return {ok:false,error:"窗口桥未就绪"};',
  'return window.wh.call("persona",method,args||[]);}',
  'function tickCount(){var n=chars(document.getElementById("soul").value);var el=document.getElementById("count");',
  'el.textContent=n+" / "+limit;el.className="count"+(n>limit?" over":n>limit-200?" warn":"");',
  'document.getElementById("save").disabled=n>limit||n<1;}',
  'function renderList(){var box=document.getElementById("p-list");var count=document.getElementById("p-count");',
  'if(count)count.textContent=String(rows.length);',
  'if(!rows.length){box.innerHTML=\'<div class="p-empty">还没有硅灵</div>\';return;}',
  'box.innerHTML="";rows.forEach(function(row){',
  'var el=document.createElement("div");el.className="p-item"+(row.id===activeId?" active":"");',
  'el.innerHTML=\'<div class="p-title">\'+esc(row.name||"未命名")+"</div>"+',
  '\'<div class="p-meta">\'+(row.active?"当前 · ":"")+row.chars+" 字</div>";',
  'el.addEventListener("click",function(){activate(row.id);});box.appendChild(el);});}',
  'function paint(snap){',
  'const p=snap.profile||{};limit=snap.limit||LIMIT;activeId=p.id||null;rows=snap.profiles||[];',
  'document.getElementById("pname").value=p.name||"";',
  'document.getElementById("soul").value=p.soul||snap.preview||"";',
  'tickCount();renderList();}',
  'async function load(){const r=await call("snapshot");if(!r.ok){toast(r.error||"读取失败",false);return;}paint(r.result);}',
  'async function activate(id){if(!id||id===activeId)return;',
  'const r=await call("activate",[id]);if(!r.ok){toast(r.error||"切换失败",false);return;}paint(r.result);toast("已切换");}',
  'async function save(){',
  'const soul=document.getElementById("soul").value;if(chars(soul)>limit){toast("超过 "+limit+" 字",false);return;}',
  'const r=await call("save",[{name:document.getElementById("pname").value,soul:soul}]);',
  'if(!r.ok){toast(r.error||"保存失败",false);return;}paint(r.result);toast("硅灵已保存");}',
  'async function create(){',
  'const r=await call("create",[{name:"新硅灵",soul:"# 我是谁\\n名称：新硅灵\\n\\n# 硅格\\n我是…。与用户协作时，我会…。\\n\\n# 习惯\\n- 先看工作区再改文件"}]);',
  'if(!r.ok){toast(r.error||"新建失败",false);return;}paint(r.result);document.getElementById("pname").focus();toast("已新建");}',
  'async function remove(){',
  'if(!activeId)return;if(rows.length<=1){toast("至少保留一份",false);return;}',
  'if(!confirm("删除当前硅灵？无法恢复。"))return;',
  'const r=await call("remove",[activeId]);if(!r.ok){toast(r.error||"删除失败",false);return;}paint(r.result);toast("已删除");}',
  'document.getElementById("save").onclick=save;',
  'document.getElementById("reload").onclick=load;',
  'document.getElementById("neu").onclick=create;',
  'document.getElementById("del").onclick=remove;',
  'document.getElementById("soul").addEventListener("input",tickCount);',
  'load();',
  '</script></body></html>',
].join('');
