export const SKILLS_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  'body{margin:0;font-family:system-ui,"Microsoft YaHei",sans-serif;background:#16161e;color:#e6e6ef}',
  '.card{padding:14px 16px;height:100%;box-sizing:border-box;display:flex;flex-direction:column}',
  'h1{font-size:16px;margin:0 0 6px}.meta{font-size:11px;color:#8b949e;margin-bottom:10px}',
  '.bar{display:flex;gap:8px;margin-bottom:10px}',
  'button{background:#21262d;border:1px solid #30363d;color:#e6e6ef;border-radius:8px;padding:5px 10px;cursor:pointer;font:12px system-ui}',
  'button:hover{background:#30363d}',
  '.list{flex:1;min-height:0;overflow:auto;font:12px/1.5 ui-monospace,Consolas,monospace}',
  '.row{padding:8px 0;border-bottom:1px solid #262634}',
  '.name{color:#79c0ff}.dim{color:#8b949e;font-size:11px}',
  '.tag{display:inline-block;font-size:10px;padding:1px 6px;border-radius:999px;margin-left:6px}',
  '.on{color:#7ee787;border:1px solid rgba(126,231,135,.35)}',
  '.off{color:#8b949e;border:1px solid #30363d}',
  '</style></head><body><div class="card">',
  '<h1>Agent Skills</h1><p class="meta" id="meta">扫描中…</p>',
  '<div class="bar"><button type="button" id="scan">重新扫描</button><button type="button" id="refresh">刷新</button></div>',
  '<div class="list" id="list"></div>',
  '</div><script>',
  'function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;");}',
  'async function call(m,a){const r=await window.wh.call("skills",m,a||[]);if(!r.ok)throw new Error(r.error||"失败");return r.result;}',
  'async function load(){',
  '  const snap=await call("snapshot");',
  '  document.getElementById("meta").textContent="目录 "+snap.scanDirs.length+" · 技能 "+snap.skills.length+" · 启用 "+snap.enabledCount;',
  '  const list=document.getElementById("list");',
  '  if(!snap.skills.length){list.innerHTML=\'<div class="dim">未发现 SKILL.md（检查 ~/.cursor/skills 或项目 .cursor/skills）</div>\';return;}',
  '  list.innerHTML=snap.skills.map(function(s){',
  '    return \'<div class="row"><span class="name">\'+esc(s.name)+\'</span>\'',
  '      +\'<span class="tag \'+(s.enabled?"on":"off")+\'">\'+(s.enabled?"启用":"停用")+\'</span>\'',
  '      +(s.alwaysApply?\'<span class="tag on">常驻</span>\':"")',
  '      +\'<div class="dim">\'+esc(s.id)+" · "+esc(s.path)+\'</div>\'',
  '      +\'<div>\'+esc(s.description)+\'</div></div>\';}).join("");',
  '}',
  'document.getElementById("scan").onclick=function(){call("scan").then(load).catch(function(e){alert(e.message);});};',
  'document.getElementById("refresh").onclick=function(){load().catch(function(e){alert(e.message);});};',
  'load().catch(function(e){document.getElementById("meta").textContent=esc(e.message);});',
  '</script></body></html>',
].join('');
