/** 通用周期元素表 UI：多 catalog + 正式/演示；偏浏览体验 */
export const ELEMENT_TABLE_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  'html,body{height:100%;margin:0;overflow:hidden}',
  'body{height:100%;display:flex;background:#0a0d13;color:#e6edf3;',
  'font:13px/1.45 system-ui,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif}',
  'button{font:inherit}',
  '.table-pane{flex:1.2;min-width:0;overflow:auto;padding:10px 12px 14px;scrollbar-width:thin;',
  'display:flex;flex-direction:column;gap:8px}',
  '.chrome{flex:none;display:flex;flex-direction:column;gap:8px}',
  '.row1{display:flex;align-items:center;gap:8px;flex-wrap:wrap;min-height:30px}',
  '.catalogs{display:inline-flex;gap:2px;padding:2px;border-radius:999px;background:#121826;border:1px solid #1c2333}',
  '.cat{appearance:none;background:transparent;border:0;color:#8b949e;border-radius:999px;padding:5px 12px;',
  'font:12px system-ui;cursor:pointer;transition:color .12s,background .12s}',
  '.cat:hover{color:#c9d1d9}',
  '.cat.on{color:#e6edf3;background:#1c2436;box-shadow:inset 0 0 0 1px #2a3347}',
  '.cat:focus-visible,.tab:focus-visible,.cell:focus-visible,.replay:focus-visible,.lg:focus-visible{outline:2px solid #4c6fff;outline-offset:2px}',
  '.sub{flex:1;min-width:120px;color:#6e7681;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
  '.tabs{display:flex;gap:5px;flex:none;margin-left:auto}',
  '.tab{background:#121826;border:1px solid #2a3347;color:#8b949e;border-radius:999px;padding:4px 11px;',
  'cursor:pointer;display:inline-flex;align-items:center;gap:5px;transition:border-color .12s,color .12s,background .12s}',
  '.tab b{font:650 12px ui-monospace,Consolas,monospace;color:#c9d1d9}',
  '.tab .unit{font-size:10px;opacity:.7}',
  '.tab:hover{border-color:#3d4a63;color:#c9d1d9}',
  '.tab.on{color:#e6edf3;border-color:#4c6fff;background:rgba(76,111,255,.14)}',
  '.tab.on b{color:#79c0ff}',
  '.row2{display:flex;align-items:center;gap:6px;flex-wrap:wrap}',
  '.legend{display:flex;flex-wrap:wrap;gap:5px;flex:1;min-width:0}',
  '.lg{appearance:none;background:transparent;font-size:10px;padding:3px 8px;border-radius:999px;border:1px solid #2a3347;',
  'color:#8b949e;white-space:nowrap;cursor:pointer;opacity:.72;transition:opacity .12s,border-color .12s,background .12s}',
  '.lg:hover,.lg.on{opacity:1}',
  '.lg.on{background:rgba(255,255,255,.04)}',
  '.lg.dim{opacity:.28}',
  '.clear-f{appearance:none;background:transparent;border:0;color:#6e7681;font-size:11px;cursor:pointer;padding:2px 6px}',
  '.clear-f:hover{color:#79c0ff}',
  '.clear-f[hidden]{display:none}',
  '.banner{flex:none;margin:0;padding:7px 10px;border-radius:8px;border:1px solid #243044;',
  'background:rgba(18,24,38,.72);color:#8b949e;font-size:11px;line-height:1.4;display:flex;gap:8px;align-items:flex-start}',
  '.banner b{color:#c9d1d9;font-weight:650}',
  '.banner code{font:11px ui-monospace,Consolas,monospace;color:#79c0ff}',
  '.banner .x{margin-left:auto;appearance:none;background:transparent;border:0;color:#6e7681;cursor:pointer;padding:0 2px;font-size:14px;line-height:1}',
  '.banner .x:hover{color:#c9d1d9}',
  '.banner[hidden]{display:none}',
  '.pt{display:grid;gap:5px;align-items:stretch;flex:none}',
  '.ph{color:#484f58;font-size:10px;display:flex;align-items:center;justify-content:center}',
  '.gh{text-align:center;font-size:10px;color:#8b949e;padding:0 0 2px;transition:opacity .12s}',
  '.gh.dim{opacity:.28}',
  '.gh b{display:block;color:#c9d1d9;font-size:11px;letter-spacing:.02em}',
  '.cell,.slot{position:relative;aspect-ratio:1;border-radius:9px;border:1px solid #2a3347;background:#121826;',
  'padding:5px 6px;display:flex;flex-direction:column;justify-content:space-between;min-height:0}',
  '.cell{cursor:pointer;transition:transform .12s,border-color .12s,box-shadow .12s,opacity .12s}',
  '.cell:hover{transform:translateY(-1px);border-color:#4c6fff;box-shadow:0 6px 16px rgba(0,0,0,.28)}',
  '.cell.on{outline:2px solid #4c6fff;outline-offset:1px;z-index:1}',
  '.cell.tap{animation:cell-tap .34s cubic-bezier(.2,.8,.2,1)}',
  '@keyframes cell-tap{0%{transform:scale(1)}35%{transform:scale(.92);box-shadow:0 0 0 0 color-mix(in srgb,var(--c,#4c6fff) 45%,transparent)}',
  '70%{transform:scale(1.04);box-shadow:0 0 0 8px transparent}100%{transform:scale(1)}}',
  '.cell.dim{opacity:.22;pointer-events:none}',
  '.cell .n{font-size:9px;color:#6e7681}',
  '.cell .s{font:700 15px/1 ui-monospace,Consolas,monospace}',
  '.cell .nm{font-size:10px;color:#c9d1d9;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
  '.badge{position:absolute;top:3px;right:3px;font-size:8px;padding:1px 4px;border-radius:999px;border:1px solid transparent;letter-spacing:.02em}',
  '.badge.demo{color:#d2a8ff;border-color:rgba(210,168,255,.35);background:rgba(210,168,255,.08)}',
  '.badge.formal{color:#7ee787;border-color:rgba(126,231,135,.35);background:rgba(126,231,135,.08)}',
  '.slot{border-style:dashed;border-color:#1c212b;background:transparent;color:#2a303a;',
  'align-items:center;justify-content:center;font-size:14px}',
  '.slot.dim{opacity:.2}',
  '.tone-drive{--c:#7ee787}.tone-risk{--c:#ffa657}.tone-economy{--c:#e3b341}',
  '.tone-space{--c:#79c0ff}.tone-time{--c:#d2a8ff}.tone-social{--c:#ff7b72}.tone-generic{--c:#8b949e}',
  '.cell[class*="tone-"]{background:linear-gradient(160deg,color-mix(in srgb,var(--c) 14%,#121826),#121826 74%);border-color:color-mix(in srgb,var(--c) 32%,#2a3347)}',
  '.cell[class*="tone-"] .s{color:var(--c)}',
  '.lg[class*="tone-"]{color:var(--c);border-color:color-mix(in srgb,var(--c) 40%,#2a3347)}',
  '.lg[class*="tone-"].on{background:color-mix(in srgb,var(--c) 12%,transparent)}',
  '.demo-pane{flex:0.8;min-width:260px;max-width:340px;border-left:1px solid #1c2333;display:flex;flex-direction:column;background:#070a10}',
  '.demo-head{flex:none;padding:12px 14px;border-bottom:1px solid #1c2333}',
  '.demo-head .row{display:flex;align-items:baseline;gap:10px}',
  '.demo-head .sym{font:700 28px/1 ui-monospace,Consolas,monospace;margin:0;flex:none;transition:color .15s}',
  '.demo-head h2{margin:0;font:650 16px/1.25 system-ui;flex:1;min-width:0}',
  '.demo-head p{margin:8px 0 0;color:#8b949e;font-size:12px;min-height:2.6em}',
  '.tags{margin-top:10px;display:flex;gap:5px;flex-wrap:wrap}',
  '.tag{font-size:10px;padding:2px 7px;border-radius:999px;border:1px solid #2a3347;color:#8b949e}',
  '.tag.kind-demo{color:#d2a8ff;border-color:rgba(210,168,255,.35)}',
  '.tag.kind-formal{color:#7ee787;border-color:rgba(126,231,135,.35)}',
  '.stage{flex:1;min-height:0;display:flex;align-items:center;justify-content:center;padding:14px;position:relative;',
  'background:radial-gradient(ellipse at 50% 42%,rgba(76,111,255,.07),transparent 58%)}',
  '.stage-frame{width:min(200px,78%);aspect-ratio:1;border-radius:14px;border:1px dashed #2a3347;',
  'background:#0b0e14;display:flex;align-items:center;justify-content:center;overflow:hidden;position:relative}',
  '.stage-frame.pulse{animation:frame-in .28s ease}',
  '@keyframes frame-in{from{opacity:.35;transform:scale(.96)}to{opacity:1;transform:scale(1)}}',
  '.hint{flex:none;padding:8px 12px;border-top:1px solid #1c2333;color:#6e7681;font-size:11px;display:flex;justify-content:space-between;gap:8px}',
  '.hint kbd{font:10px ui-monospace,Consolas,monospace;border:1px solid #2a3347;border-radius:4px;padding:0 4px;color:#8b949e}',
  '.replay{position:absolute;right:12px;bottom:12px;background:#121826;border:1px solid #2a3347;color:#c9d1d9;',
  'border-radius:999px;padding:5px 12px;font:11px system-ui;cursor:pointer}',
  '.replay:hover{border-color:#4c6fff;color:#79c0ff}',
  '.empty{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;padding:28px 12px;color:#6e7681;font-size:12px}',
  '.empty b{color:#8b949e;font-weight:650}',
  '.d-generic{width:36px;height:36px;border-radius:10px;border:2px solid #4c6fff;animation:gen 1.2s ease-in-out infinite}',
  '@keyframes gen{0%,100%{transform:scale(.9);opacity:.5}50%{transform:scale(1.08);opacity:1}}',
  '.d-goal{width:54px;height:54px;border:3px solid #7ee787;border-radius:50%;position:relative}',
  '.d-goal::after{content:"";position:absolute;inset:12px;border-radius:50%;background:#7ee787;transform:scale(0);animation:goal-hit .9s ease infinite}',
  '@keyframes goal-hit{0%,40%{transform:scale(0);opacity:0}55%{transform:scale(1);opacity:1}100%{transform:scale(1.4);opacity:0}}',
  '.d-progress{width:70%;height:10px;background:#21262d;border-radius:999px;overflow:hidden}',
  '.d-progress i{display:block;height:100%;width:0;background:linear-gradient(90deg,#238636,#7ee787);animation:pg-fill 1.6s ease-in-out infinite}',
  '@keyframes pg-fill{0%{width:0}70%,100%{width:100%}}',
  '.d-scarcity{display:flex;gap:6px}',
  '.d-scarcity i{width:12px;height:12px;border-radius:50%;background:#7ee787;animation:scarce 1.8s ease-in-out infinite}',
  '.d-scarcity i:nth-child(2){animation-delay:.2s}.d-scarcity i:nth-child(3){animation-delay:.4s}',
  '.d-scarcity i:nth-child(4){animation-delay:.6s}.d-scarcity i:nth-child(5){animation-delay:.8s}',
  '@keyframes scarce{0%,20%{opacity:1;transform:scale(1)}50%,100%{opacity:.15;transform:scale(.6)}}',
  '.d-prestige{font-size:42px;color:#e3b341;animation:spin-star 2s linear infinite}',
  '@keyframes spin-star{to{transform:rotate(360deg)}}',
  '.d-chance{width:48px;height:48px;border-radius:10px;background:#21262d;border:1px solid #ffa657;display:flex;align-items:center;justify-content:center;',
  'font:700 22px ui-monospace;color:#ffa657;animation:dice 1.2s ease-in-out infinite}',
  '@keyframes dice{0%,100%{transform:rotate(0)}25%{transform:rotate(12deg) scale(1.05)}50%{transform:rotate(-8deg)}}',
  '.d-risk{width:80px;height:40px;border:2px solid #ffa657;border-bottom:0;border-radius:80px 80px 0 0;position:relative}',
  '.d-risk::before{content:"";position:absolute;left:50%;bottom:0;width:3px;height:34px;background:#ffa657;transform-origin:bottom center;animation:needle 1.5s ease-in-out infinite}',
  '@keyframes needle{0%,100%{transform:translateX(-50%) rotate(-50deg)}50%{transform:translateX(-50%) rotate(50deg)}}',
  '.d-skill{font:700 28px ui-monospace;color:#ffa657}',
  '.d-pressure{width:70px;height:70px;border-radius:50%;border:2px solid #ffa657;animation:squeeze 1.2s ease-in-out infinite}',
  '@keyframes squeeze{0%,100%{transform:scale(1)}50%{transform:scale(.72)}}',
  '.d-resource{display:flex;align-items:flex-end;gap:4px;height:54px}',
  '.d-resource i{width:14px;background:#e3b341;border-radius:3px 3px 0 0;animation:pile 1.4s ease-in-out infinite}',
  '.d-resource i:nth-child(1){height:18px}.d-resource i:nth-child(2){height:28px;animation-delay:.1s}',
  '.d-resource i:nth-child(3){height:40px;animation-delay:.2s}.d-resource i:nth-child(4){height:22px;animation-delay:.3s}',
  '@keyframes pile{0%,100%{transform:scaleY(.55)}50%{transform:scaleY(1)}}',
  '.d-cost{position:relative;width:40px;height:40px;border-radius:50%;background:#e3b341;animation:coin 1s ease-in-out infinite}',
  '.d-cost::after{content:"-";position:absolute;right:-18px;top:4px;color:#ff7b72;font:700 22px system-ui}',
  '@keyframes coin{0%,100%{transform:translateY(0)}50%{transform:translateY(10px);opacity:.5}}',
  '.d-trade{display:flex;gap:16px;align-items:center;position:relative}',
  '.d-trade i{width:22px;height:22px;border-radius:4px}',
  '.d-trade i:first-child{background:#79c0ff;animation:swap-a 1.4s ease-in-out infinite}',
  '.d-trade i:last-child{background:#e3b341;animation:swap-b 1.4s ease-in-out infinite}',
  '@keyframes swap-a{0%,100%{transform:translateX(0)}50%{transform:translateX(38px)}}',
  '@keyframes swap-b{0%,100%{transform:translateX(0)}50%{transform:translateX(-38px)}}',
  '.d-craft{width:36px;height:36px;background:#e3b341;clip-path:polygon(50% 0,100% 38%,82% 100%,18% 100%,0 38%);animation:forge .9s ease-in-out infinite}',
  '@keyframes forge{0%,100%{filter:brightness(1)}40%{filter:brightness(1.8);transform:scale(1.12)}}',
  '.d-arena{display:grid;grid-template-columns:repeat(3,18px);gap:4px}',
  '.d-arena i{width:18px;height:18px;background:#21262d;border-radius:3px}',
  '.d-arena i:nth-child(5){animation:cell-lit 1.2s ease-in-out infinite;background:#79c0ff}',
  '@keyframes cell-lit{0%,100%{box-shadow:0 0 0 0 rgba(121,192,255,0)}50%{box-shadow:0 0 12px rgba(121,192,255,.7)}}',
  '.d-path{width:90px;height:40px;position:relative}',
  '.d-path::before{content:"";position:absolute;left:8px;top:50%;width:74px;height:0;border-top:2px dashed #79c0ff;transform-origin:left center;animation:path-draw 1.6s ease-in-out infinite}',
  '@keyframes path-draw{0%{transform:scaleX(0)}60%,100%{transform:scaleX(1)}}',
  '.d-fog{width:90px;height:60px;background:#161b22;border-radius:8px;position:relative;overflow:hidden}',
  '.d-fog::after{content:"";position:absolute;inset:0;background:#0d1117;animation:reveal 2s ease-in-out infinite}',
  '@keyframes reveal{0%{transform:translateX(0)}50%,100%{transform:translateX(100%)}}',
  '.d-cover{width:48px;height:56px;border:2px solid #79c0ff;border-radius:8px 8px 40% 40%;animation:shield 1.3s ease-in-out infinite}',
  '@keyframes shield{0%,100%{opacity:.45}50%{opacity:1;box-shadow:0 0 16px rgba(121,192,255,.4)}}',
  '.d-beat{width:14px;height:40px;background:#d2a8ff;border-radius:4px;animation:metro .7s ease-in-out infinite}',
  '@keyframes metro{0%,100%{transform:scaleY(.4);opacity:.5}50%{transform:scaleY(1);opacity:1}}',
  '.d-cooldown{width:56px;height:56px;border-radius:50%;border:3px solid #21262d;border-top-color:#d2a8ff;animation:cd-spin 1.2s linear infinite}',
  '@keyframes cd-spin{to{transform:rotate(360deg)}}',
  '.d-wave{width:100px;height:40px;background:radial-gradient(circle at 10% 50%,#d2a8ff 4px,transparent 5px),radial-gradient(circle at 50% 50%,#d2a8ff 4px,transparent 5px),radial-gradient(circle at 90% 50%,#d2a8ff 4px,transparent 5px);animation:wave-y 1.2s ease-in-out infinite}',
  '@keyframes wave-y{0%,100%{transform:translateY(0)}50%{transform:translateY(-8px)}}',
  '.d-echo{width:20px;height:20px;border-radius:50%;border:2px solid #d2a8ff;animation:ripple 1.5s ease-out infinite}',
  '@keyframes ripple{0%{transform:scale(.4);opacity:1}100%{transform:scale(2.4);opacity:0}}',
  '.d-ally{display:flex;gap:20px;align-items:center;position:relative}',
  '.d-ally i{width:18px;height:18px;border-radius:50%;background:#ff7b72}',
  '.d-ally::before{content:"";width:28px;height:2px;background:#ff7b72;position:absolute;left:50%;transform:translateX(-50%);animation:link 1.2s ease-in-out infinite}',
  '@keyframes link{0%,100%{opacity:.3;transform:translateX(-50%) scaleX(.6)}50%{opacity:1;transform:translateX(-50%) scaleX(1)}}',
  '.d-rival{display:flex;gap:10px}',
  '.d-rival i{width:20px;height:20px;background:#ff7b72;clip-path:polygon(50% 0,100% 100%,0 100%);animation:clash .9s ease-in-out infinite}',
  '.d-rival i:last-child{transform:scaleX(-1);animation-name:clash2}',
  '@keyframes clash{0%,100%{transform:translateX(0)}50%{transform:translateX(8px)}}',
  '@keyframes clash2{0%,100%{transform:scaleX(-1) translateX(0)}50%{transform:scaleX(-1) translateX(8px)}}',
  '.d-audience{display:flex;align-items:flex-end;gap:5px;height:48px}',
  '.d-audience i{width:8px;background:#ff7b72;border-radius:2px;animation:clap .6s ease-in-out infinite}',
  '.d-audience i:nth-child(1){height:18px}.d-audience i:nth-child(2){height:30px;animation-delay:.1s}',
  '.d-audience i:nth-child(3){height:40px;animation-delay:.15s}.d-audience i:nth-child(4){height:24px;animation-delay:.05s}',
  '.d-audience i:nth-child(5){height:34px;animation-delay:.2s}',
  '@keyframes clap{0%,100%{transform:scaleY(.5)}50%{transform:scaleY(1)}}',
  '.d-guild{display:grid;grid-template-columns:repeat(3,14px);gap:4px;transform:rotate(30deg)}',
  '.d-guild i{width:14px;height:14px;background:#ff7b72;clip-path:polygon(25% 0,75% 0,100% 50%,75% 100%,25% 100%,0 50%);animation:hex 1.5s ease-in-out infinite}',
  '@keyframes hex{0%,100%{opacity:.35}50%{opacity:1}}',
  '@media (prefers-reduced-motion:reduce){*{animation:none!important}}',
  '@media (max-width:720px){body{flex-direction:column}.demo-pane{min-height:240px;max-width:none;border-left:0;border-top:1px solid #1c2333}',
  '.tabs{margin-left:0;width:100%;justify-content:flex-end}.hint .keys{display:none}}',
  '</style></head><body>',
  '<div class="table-pane">',
  '<div class="chrome">',
  '<div class="row1">',
  '<div class="catalogs" id="catalogs" role="tablist" aria-label="元素表种类"></div>',
  '<div class="sub" id="sub" title=""></div>',
  '<div class="tabs" role="tablist" aria-label="分层">',
  '<button type="button" class="tab" data-mode="formal" title="1">正式 <b id="c-formal">0</b></button>',
  '<button type="button" class="tab" data-mode="demo" title="2">演示 <b id="c-demo">0</b></button>',
  '<button type="button" class="tab" data-mode="all" title="3">全部 <b id="c-periods">0</b><span class="unit">周期</span></button>',
  '</div></div>',
  '<div class="row2">',
  '<div class="legend" id="legend" role="toolbar" aria-label="按族筛选"></div>',
  '<button type="button" class="clear-f" id="clearF" hidden>清除筛选</button>',
  '</div></div>',
  '<div class="banner" id="banner" hidden></div>',
  '<div class="pt" id="pt" role="grid" aria-label="元素周期表"></div>',
  '</div><aside class="demo-pane">',
  '<div class="demo-head"><div class="row"><div class="sym" id="sym">—</div><h2 id="title">选择一个元素</h2></div>',
  '<p id="blurb">点选左侧格子浏览；可按族筛选。</p>',
  '<div class="tags" id="tags"></div></div>',
  '<div class="stage"><div class="stage-frame" id="stage"></div>',
  '<button type="button" class="replay" id="replay" title="R">重播</button></div>',
  '<p class="hint"><span>演示不进正式库</span><span class="keys"><kbd>←</kbd><kbd>→</kbd> 浏览 · <kbd>R</kbd> 重播 · <kbd>1</kbd><kbd>2</kbd><kbd>3</kbd> 分层</span></p>',
  '</aside>',
  '<script>',
  'var snap=null,mode="demo",current=null,groupFilter=null,bannerDismissed={},modeByCat={},selByCat={},timers=[];',
  'function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;");}',
  'function clearTimers(){timers.forEach(function(t){clearInterval(t);clearTimeout(t);});timers=[];}',
  'function later(fn,ms){var id=setTimeout(fn,ms);timers.push(id);return id;}',
  'function every(fn,ms){var id=setInterval(fn,ms);timers.push(id);return id;}',
  'async function call(method,args){',
  'if(!window.wh||!window.wh.call)return {ok:false,error:"窗口桥未就绪"};',
  'return window.wh.call("elementTable",method,args||[]);}',
  'function toneOf(g){return (g&&(g.tone||g.id))||"generic";}',
  'function groupName(id){var g=(snap.groups||[]).find(function(x){return x.id===id;});return g?g.name:id;}',
  'function demoHtml(demo){',
  'var map={goal:"d-goal",progress:"d-progress",scarcity:"d-scarcity",prestige:"d-prestige",chance:"d-chance",',
  'risk:"d-risk",skill:"d-skill",pressure:"d-pressure",resource:"d-resource",cost:"d-cost",trade:"d-trade",',
  'craft:"d-craft",arena:"d-arena",path:"d-path",fog:"d-fog",cover:"d-cover",beat:"d-beat",cooldown:"d-cooldown",',
  'wave:"d-wave",echo:"d-echo",ally:"d-ally",rival:"d-rival",audience:"d-audience",guild:"d-guild",generic:"d-generic"};',
  'var cls=map[demo]||"d-generic";',
  'if(cls==="d-prestige")return "<div class=\\"d-prestige\\">*</div>";',
  'if(cls==="d-progress"||cls==="d-cost"||cls==="d-path"||cls==="d-fog"||cls==="d-cover"||cls==="d-beat"||cls==="d-cooldown"||cls==="d-wave"||cls==="d-echo"||cls==="d-goal"||cls==="d-risk"||cls==="d-pressure"||cls==="d-craft"||cls==="d-generic")',
  'return "<div class=\\""+cls+"\\"></div>";',
  'if(cls==="d-scarcity")return "<div class=\\"d-scarcity\\"><i></i><i></i><i></i><i></i><i></i></div>";',
  'if(cls==="d-chance")return "<div class=\\"d-chance\\" id=\\"dice\\">?</div>";',
  'if(cls==="d-skill")return "<div class=\\"d-skill\\" id=\\"combo\\">x1</div>";',
  'if(cls==="d-resource")return "<div class=\\"d-resource\\"><i></i><i></i><i></i><i></i></div>";',
  'if(cls==="d-trade")return "<div class=\\"d-trade\\"><i></i><i></i></div>";',
  'if(cls==="d-arena")return "<div class=\\"d-arena\\"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div>";',
  'if(cls==="d-ally")return "<div class=\\"d-ally\\"><i></i><i></i></div>";',
  'if(cls==="d-rival")return "<div class=\\"d-rival\\"><i></i><i></i></div>";',
  'if(cls==="d-audience")return "<div class=\\"d-audience\\"><i></i><i></i><i></i><i></i><i></i></div>";',
  'if(cls==="d-guild")return "<div class=\\"d-guild\\"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div>";',
  'return "<div class=\\"d-generic\\"></div>";}',
  'function showEmptyDetail(msg){',
  'current=null;clearTimers();',
  'document.getElementById("sym").textContent="\\u2014";document.getElementById("sym").style.color="";',
  'document.getElementById("title").textContent="暂无元素";',
  'document.getElementById("blurb").textContent=msg;',
  'document.getElementById("tags").innerHTML="";',
  'document.getElementById("stage").className="stage-frame";',
  'document.getElementById("stage").innerHTML="<div class=\\"empty\\"><b>\\u7a7a</b><span>"+esc(msg)+"</span></div>";}',
  'function play(el,opts){',
  'if(!el)return;opts=opts||{};',
  'current=el;if(snap)selByCat[snap.catalogId]=el.id;',
  'document.querySelectorAll(".cell").forEach(function(c){c.classList.toggle("on",c.getAttribute("data-id")===el.id);});',
  'if(opts.animate){',
  'var btn=document.querySelector(".cell[data-id=\\""+cssId(el.id)+"\\"]");',
  'if(btn){btn.classList.remove("tap");void btn.offsetWidth;btn.classList.add("tap");',
  'later(function(){btn.classList.remove("tap");},360);}}',
  'document.getElementById("sym").textContent=el.symbol;',
  'var sample=document.querySelector(".cell[data-id=\\""+cssId(el.id)+"\\"] .s");',
  'document.getElementById("sym").style.color=sample?getComputedStyle(sample).color:"";',
  'document.getElementById("title").textContent=el.name;',
  'document.getElementById("blurb").textContent=el.blurb||"";',
  'document.getElementById("tags").innerHTML=',
  '"<span class=\\"tag\\">"+esc(groupName(el.group))+"</span><span class=\\"tag\\">周期 "+el.period+"</span>"+',
  '"<span class=\\"tag\\">#"+el.atomic+"</span>"+',
  '"<span class=\\"tag kind-"+(el.kind==="demo"?"demo":"formal")+"\\">"+(el.kind==="demo"?"演示":"正式")+"</span>";',
  'clearTimers();',
  'var stage=document.getElementById("stage");',
  'stage.className="stage-frame pulse";',
  'stage.innerHTML=demoHtml(el.demo);',
  'later(function(){stage.classList.remove("pulse");},300);',
  'if(el.demo==="chance"){var d=document.getElementById("dice");var faces=["1","2","3","4","5","6"];var t=0;',
  'every(function(){if(!d)return;d.textContent=faces[t++%6];},120);later(function(){clearTimers();},1200);}',
  'if(el.demo==="skill"){var c=document.getElementById("combo");var n=1;',
  'every(function(){if(!c)return;c.textContent="x"+(n++);if(n>9)n=1;},400);later(function(){clearTimers();},2400);}',
  '}',
  'function filtered(){',
  'if(!snap)return [];',
  'var rows=mode==="formal"?(snap.formal||[]):mode==="demo"?(snap.demo||[]):[].concat(snap.formal||[],snap.demo||[]);',
  'if(groupFilter)rows=rows.filter(function(e){return e.group===groupFilter;});',
  'return rows;',
  '}',
  'function allVisible(){',
  'if(!snap)return [];',
  'return mode==="formal"?(snap.formal||[]):mode==="demo"?(snap.demo||[]):[].concat(snap.formal||[],snap.demo||[]);',
  '}',
  'function cssId(id){return String(id).split("\\\\").join("\\\\\\\\").split("\\"").join("\\\\\\"");}',
  'function renderCatalogs(){',
  'var box=document.getElementById("catalogs");',
  'var list=(snap&&snap.catalogs)||[];',
  'box.innerHTML=list.map(function(c){',
  'return "<button type=\\"button\\" role=\\"tab\\" aria-selected=\\""+(c.id===snap.catalogId)+"\\" class=\\""+(c.id===snap.catalogId?"cat on":"cat")+"\\" data-cat=\\""+esc(c.id)+"\\" title=\\""+esc(c.blurb||"")+"\\">"+esc(c.title)+"</button>";',
  '}).join("");',
  'document.getElementById("sub").textContent=snap.blurb||"";',
  'document.getElementById("sub").title=snap.blurb||"";',
  '}',
  'function setBanner(html){',
  'var banner=document.getElementById("banner");',
  'var key=(snap&&snap.catalogId||"")+"|"+mode;',
  'if(!html||bannerDismissed[key]){banner.hidden=true;banner.innerHTML="";return;}',
  'banner.hidden=false;',
  'banner.innerHTML="<div>"+html+"</div><button type=\\"button\\" class=\\"x\\" id=\\"banX\\" aria-label=\\"关闭\\">×</button>";',
  'document.getElementById("banX").onclick=function(){bannerDismissed[key]=true;banner.hidden=true;};',
  '}',
  'function render(){',
  'if(!snap)return;',
  'renderCatalogs();',
  'var formal=(snap.formal||[]).length, demo=(snap.demo||[]).length;',
  'document.getElementById("c-formal").textContent=String(formal);',
  'document.getElementById("c-demo").textContent=String(demo);',
  'document.getElementById("c-periods").textContent=String(snap.periods||0);',
  'document.querySelectorAll(".tab").forEach(function(t){t.classList.toggle("on",t.getAttribute("data-mode")===mode);t.setAttribute("aria-selected",t.getAttribute("data-mode")===mode?"true":"false");});',
  'var catTitle=esc(snap.title||"元素表");',
  'if(mode==="formal"&&formal===0){',
  'setBanner("<b>"+catTitle+" · 正式库为空</b> — 用 <code>registerElement({ catalogId, kind:\\"formal\\" })</code> 添加");',
  '}else if(mode==="demo"&&demo>0){',
  'setBanner("");',
  '}else if(mode==="all"&&formal===0){',
  'setBanner("<b>"+catTitle+"</b> — 当前仅有演示样例");',
  '}else{setBanner("");}',
  'var groups=snap.groups||[];',
  'document.getElementById("clearF").hidden=!groupFilter;',
  'document.getElementById("legend").innerHTML=groups.map(function(g){',
  'var on=groupFilter===g.id, dim=groupFilter&&!on;',
  'var cls="lg tone-"+toneOf(g)+(on?" on":"")+(dim?" dim":"");',
  'return "<button type=\\"button\\" class=\\""+esc(cls)+"\\" data-g=\\""+esc(g.id)+"\\" title=\\""+esc(g.blurb||g.name)+"\\">"+esc(g.symbol)+" "+esc(g.name)+"</button>";',
  '}).join("");',
  'var cols=groups.length;',
  'var pt=document.getElementById("pt");',
  'pt.style.gridTemplateColumns="22px repeat("+cols+",minmax(52px,1fr))";',
  'var showBadge=mode==="all";',
  'var html="<div></div>"+groups.map(function(g){',
  'var dim=groupFilter&&groupFilter!==g.id;',
  'return "<div class=\\""+(dim?"gh dim":"gh")+"\\"><b>"+esc(g.symbol)+"</b>"+esc(g.name)+"</div>";}).join("");',
  'var visible=allVisible();',
  'for(var p=1;p<=snap.periods;p++){',
  'html+="<div class=\\"ph\\">"+p+"</div>";',
  'groups.forEach(function(g){',
  'var el=visible.find(function(e){return e.group===g.id&&e.period===p;});',
  'var dim=groupFilter&&groupFilter!==g.id;',
  'if(!el){html+="<div class=\\""+(dim?"slot dim":"slot")+"\\">.</div>";return;}',
  'var ccls="cell tone-"+toneOf(g)+(dim?" dim":"");',
  'html+="<button type=\\"button\\" class=\\""+esc(ccls)+"\\" data-id=\\""+esc(el.id)+"\\" data-g=\\""+esc(g.id)+"\\" aria-label=\\""+esc(el.name)+"\\">"',
  '+(showBadge?"<span class=\\"badge "+(el.kind==="demo"?"demo":"formal")+"\\">"+(el.kind==="demo"?"演示":"正式")+"</span>":"")',
  '+"<span class=\\"n\\">"+el.atomic+"</span><span class=\\"s\\">"+esc(el.symbol)+"</span>"',
  '+"<span class=\\"nm\\">"+esc(el.name)+"</span></button>";',
  '});}',
  'pt.innerHTML=html;',
  'var rows=filtered();',
  'var prefer=selByCat[snap.catalogId];',
  'var pick=(prefer&&rows.find(function(e){return e.id===prefer;}))||rows[0];',
  'if(pick)play(pick,{force:true});',
  'else showEmptyDetail(mode==="formal"?"正式库还是空的，可切到演示。":groupFilter?"该族在当前分层下没有元素。":"没有可展示的元素。");',
  '}',
  'async function boot(){',
  'var r=await call("snapshot");',
  'if(!r.ok){setBanner(esc(r.error||"读取失败"));document.getElementById("banner").hidden=false;return;}',
  'snap=r.result;',
  'mode=modeByCat[snap.catalogId]||((snap.formal&&snap.formal.length)?"formal":"demo");',
  'render();',
  '}',
  'async function switchCatalog(id){',
  'if(snap&&id===snap.catalogId)return;',
  'if(snap)modeByCat[snap.catalogId]=mode;',
  'var r=await call("setCatalog",[id]);',
  'if(!r.ok){setBanner(esc(r.error||"切换失败"));return;}',
  'snap=r.result;groupFilter=null;',
  'mode=modeByCat[snap.catalogId]||((snap.formal&&snap.formal.length)?"formal":"demo");',
  'render();',
  '}',
  'function moveSel(dir){',
  'var rows=filtered();if(!rows.length)return;',
  'var i=current?rows.findIndex(function(e){return e.id===current.id;}):-1;',
  'i=Math.max(0,Math.min(rows.length-1,(i<0?0:i)+dir));',
  'play(rows[i],{force:true,animate:true});',
  'var btn=document.querySelector(".cell[data-id=\\""+cssId(rows[i].id)+"\\"]");',
  'if(btn)btn.focus();',
  '}',
  'document.getElementById("catalogs").addEventListener("click",function(e){',
  'var btn=e.target.closest(".cat");if(!btn)return;switchCatalog(btn.getAttribute("data-cat"));});',
  'document.getElementById("legend").addEventListener("click",function(e){',
  'var btn=e.target.closest(".lg");if(!btn)return;',
  'var g=btn.getAttribute("data-g");',
  'groupFilter=groupFilter===g?null:g;render();});',
  'document.getElementById("clearF").onclick=function(){groupFilter=null;render();};',
  'document.getElementById("pt").addEventListener("click",function(e){',
  'var btn=e.target.closest(".cell");if(!btn||!snap)return;',
  'var el=allVisible().find(function(x){return x.id===btn.getAttribute("data-id");});',
  'if(!el)return;',
  'play(el,{force:true,animate:true});});',
  'document.getElementById("replay").onclick=function(){if(current)play(current,{force:true,animate:true});};',
  'document.querySelectorAll(".tab").forEach(function(t){t.onclick=function(){',
  'mode=t.getAttribute("data-mode");if(snap)modeByCat[snap.catalogId]=mode;groupFilter=groupFilter;render();};});',
  'document.addEventListener("keydown",function(e){',
  'if(e.target&&(e.target.tagName==="INPUT"||e.target.tagName==="TEXTAREA"))return;',
  'if(e.key==="ArrowRight"||e.key==="ArrowDown"){e.preventDefault();moveSel(1);}',
  'else if(e.key==="ArrowLeft"||e.key==="ArrowUp"){e.preventDefault();moveSel(-1);}',
  'else if(e.key==="r"||e.key==="R"){if(current)play(current,{force:true});}',
  'else if(e.key==="1"){mode="formal";if(snap)modeByCat[snap.catalogId]=mode;render();}',
  'else if(e.key==="2"){mode="demo";if(snap)modeByCat[snap.catalogId]=mode;render();}',
  'else if(e.key==="3"){mode="all";if(snap)modeByCat[snap.catalogId]=mode;render();}',
  'else if(e.key==="Escape"&&groupFilter){groupFilter=null;render();}',
  '});',
  'boot();',
  '</script></body></html>',
].join('');

/** @deprecated 使用 ELEMENT_TABLE_HTML */
export const MECHANICS_TABLE_HTML = ELEMENT_TABLE_HTML;
