export const SESSION_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  'html,body{height:100%;margin:0;overflow:hidden}',
  'body{display:flex;flex-direction:column;background:#0d1117;color:#e6e6ef;',
  'font:13px/1.5 system-ui,"Segoe UI","Microsoft YaHei",sans-serif}',
  '.bar{flex:none;padding:8px 14px;border-bottom:1px solid #262634;display:flex;gap:8px;align-items:center}',
  'h1{font:600 14px system-ui;margin:0}',
  '.meta{color:#8b949e;font-size:11px}',
  '.ghost,.pri{border-radius:8px;padding:4px 10px;font:12px system-ui;cursor:pointer}',
  '.ghost{margin-left:auto;background:transparent;border:1px solid #333;color:#a8a8bd}',
  '.ghost:hover{border-color:#4a6aa0;color:#79c0ff}',
  '.pri{background:linear-gradient(135deg,#2ea043,#238636);border:none;color:#fff}',
  '.cols{flex:1;min-height:0;display:flex}',
  '.col{min-width:0;display:flex;flex-direction:column;border-right:1px solid #262634}',
  '.col.list{flex:0 0 240px}',
  '.col.detail{flex:1;border-right:none}',
  '.col h2{flex:none;margin:0;padding:8px 12px;font:600 12px system-ui;color:#a8a8bd;border-bottom:1px solid #262634}',
  '.pad{flex:1;min-height:0;overflow:auto;padding:10px 12px 16px}',
  '.item{padding:8px 10px;border-bottom:1px solid #1c1c28;cursor:pointer}',
  '.item:hover{background:#16161e}',
  '.item.on{background:#1c2d41}',
  '.item .t{font-weight:600}',
  '.item .s{color:#8b949e;font:11px ui-monospace,Consolas,monospace;word-break:break-all}',
  'label{display:block;font-size:11px;color:#8b949e;margin:8px 0 4px}',
  'input{width:100%;box-sizing:border-box;background:#16161e;border:1px solid #2c2c3e;border-radius:8px;',
  'color:#e6e6ef;padding:7px 10px;font:13px system-ui;outline:none}',
  'input:focus{border-color:#4a6aa0}',
  '.kv{display:flex;justify-content:space-between;gap:8px;font-size:12px;padding:4px 0;border-bottom:1px solid #1c1c28}',
  '.k{color:#8b949e}.v{font:12px ui-monospace,Consolas,monospace;color:#79c0ff;word-break:break-all;text-align:right}',
  '.log{margin-top:10px;background:#16161e;border:1px solid #262634;border-radius:8px;padding:8px 10px;',
  'font:11px/1.45 ui-monospace,Consolas,monospace;color:#a8a8bd;white-space:pre-wrap;word-break:break-word;max-height:180px;overflow:auto}',
  '.empty,.err{color:#8b949e;padding:12px 0}.err{color:#ffb4ae}',
  '.row{display:flex;gap:6px;margin-top:10px}',
  '.toast{position:fixed;left:50%;bottom:16px;transform:translateX(-50%);background:#21262d;border:1px solid #30363d;',
  'color:#7ee787;border-radius:8px;padding:6px 12px;font:12px system-ui;opacity:0;pointer-events:none;transition:opacity .15s}',
  '.toast.on{opacity:1}',
  '</style></head><body>',
  '<div class="bar"><h1>会话</h1><span class="meta" id="meta">—</span>',
  '<button class="ghost" type="button" id="reload">刷新</button>',
  '<button class="pri" type="button" id="neu">新建</button></div>',
  '<div class="cols">',
  '<section class="col list"><h2>已创建</h2><div class="pad" id="list"></div></section>',
  '<section class="col detail"><h2>元数据</h2><div class="pad" id="detail">',
  '<div class="empty">选一条会话，或点新建。</div></div></section>',
  '</div><div class="toast" id="toast"></div>',
  '<script>',
  'function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;");}',
  'let toastTimer, selected, cache=[];',
  'function toast(msg,ok){var el=document.getElementById("toast");el.textContent=msg;el.style.color=ok===false?"#ffb4ae":"#7ee787";',
  'el.className="toast on";clearTimeout(toastTimer);toastTimer=setTimeout(function(){el.className="toast";},1200);}',
  'async function call(method,args){',
  'if(!window.wh||!window.wh.call)return {ok:false,error:"窗口桥未就绪"};',
  'return window.wh.call("session",method,args||[]);}',
  'function clock(ts){try{return new Date(ts).toLocaleString("zh-CN",{hour12:false});}catch(e){return String(ts);}}',
  'function label(s){return s.title||s.id.slice(0,8);}',
  'function paintList(){',
  'const list=document.getElementById("list");',
  'if(!cache.length){list.innerHTML=\'<div class="empty">还没有会话。App demo 发一条，或这里点新建。</div>\';return;}',
  'list.innerHTML=cache.map(function(s){',
  'return \'<div class="item\'+(s.id===selected?" on":"")+\'" data-id="\'+esc(s.id)+\'"><div class="t">\'+esc(label(s))+',
  '\' · \'+s.entries+\' 条</div><div class="s">\'+esc(s.workspace||"（未设工作区）")+"</div></div>";}).join("");}',
  'function clipEntry(e){',
  'var d=e.data||{};',
  'var bit=d.content||d.phase||d.name||"";',
  'bit=String(bit).replace(/\\s+/g," ").slice(0,80);',
  'return e.seq+" "+e.kind+(bit?" "+bit:"");}',
  'function paintDetail(peek){',
  'if(!peek){document.getElementById("detail").innerHTML=\'<div class="empty">选一条会话，或点新建。</div>\';return;}',
  'var entries=peek.entries||[];',
  'var log=entries.slice(-20).map(clipEntry).join("\\n")||"（空日志）";',
  'document.getElementById("detail").innerHTML=',
  '\'<div class="kv"><span class="k">id</span><span class="v">\'+esc(peek.id)+"</span></div>"+',
  '\'<div class="kv"><span class="k">开始</span><span class="v">\'+esc(clock(peek.startedAt))+"</span></div>"+',
  '\'<div class="kv"><span class="k">条目</span><span class="v">\'+entries.length+"</span></div>"+',
  '\'<label>标题</label><input id="title" value="\'+esc(peek.title||"")+\'" />\'+',
  '\'<label>工作区</label><input id="ws" value="\'+esc(peek.workspace||"")+\'" placeholder="绝对路径，空则用 dev-tools 默认 root" />\'+',
  '\'<div class="row"><button class="pri" type="button" id="save">保存元数据</button></div>\'+',
  '\'<div class="log">\'+esc(log)+"</div>";',
  'document.getElementById("save").onclick=save;}',
  'async function load(){',
  'const r=await call("inspect");',
  'if(!r.ok){toast(r.error||"读取失败",false);return;}',
  'cache=r.result.sessions||[];',
  'const dir=r.result.persistDir||"（内存）";',
  'document.getElementById("meta").textContent=cache.length+" 条 · "+dir;',
  'if(selected&&!cache.some(function(s){return s.id===selected;})) selected=undefined;',
  'if(!selected&&cache[0]) selected=cache[0].id;',
  'paintList();',
  'if(!selected){paintDetail(null);return;}',
  'const p=await call("peek",[selected]);',
  'if(!p.ok){toast(p.error||"读取失败",false);return;}',
  'paintDetail(p.result);}',
  'async function save(){',
  'if(!selected)return;',
  'const r=await call("patch",[selected,{title:document.getElementById("title").value,workspace:document.getElementById("ws").value}]);',
  'if(!r.ok){toast(r.error||"保存失败",false);return;}toast("已保存");load();}',
  'async function neu(){',
  'const r=await call("open",[{title:"未命名"}]);',
  'if(!r.ok){toast(r.error||"新建失败",false);return;}',
  'selected=r.result&&r.result.id; toast("已新建"); load();}',
  'document.getElementById("list").addEventListener("click",function(e){',
  'const row=e.target.closest("[data-id]"); if(!row)return; selected=row.getAttribute("data-id"); load();});',
  'document.getElementById("reload").onclick=load;',
  'document.getElementById("neu").onclick=neu;',
  'load();',
  '</script></body></html>',
].join('');
