import { CONTEXT_MENU_CSS, CONTEXT_MENU_HTML, CONTEXT_MENU_JS } from './context-menu.js';
import { FILE_SYNC_JS } from './file-sync.js';
import { SYNTAX_CSS, SYNTAX_JS } from './syntax.js';
import { CODE_VIEW_CHROME_CSS } from './view-chrome.js';

export const CODE_BROWSER_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  CODE_VIEW_CHROME_CSS,
  CONTEXT_MENU_CSS,
  SYNTAX_CSS,
  'pre.code code{display:block}',
  '</style></head><body>',
  '<div class="bar"><span class="path" id="path">（未打开文件）</span><span class="meta" id="meta"></span>',
  '<button type="button" class="btn" id="reload" style="display:none">重载</button>',
  '<button type="button" class="btn" id="edit" style="display:none">编辑</button></div>',
  '<div class="workspace" id="wrap" style="display:none"><pre class="gutter" id="gutter"></pre>',
  '<pre class="code-scroll code code-pane" id="code"><code id="codeInner"></code></pre></div>',
  '<div class="empty" id="empty">等待打开文件…</div>',
  '<div class="err" id="err"></div>',
  CONTEXT_MENU_HTML,
  '<div class="status" id="status">只读浏览 · 选中代码后右键可局部编辑</div>',
  '<script>',
  SYNTAX_JS,
  CONTEXT_MENU_JS,
  FILE_SYNC_JS,
  'var curPath="",curContent="",viewSlice=null;',
  'function syncGutter(n,from){var g=document.getElementById("gutter"),lines=[];',
  'var base=from||1;for(var i=0;i<n;i++)lines.push(base+i);g.textContent=lines.join("\\n");}',
  'function syncScroll(){var g=document.getElementById("gutter"),c=document.getElementById("code");g.scrollTop=c.scrollTop;}',
  'function renderView(){',
  'var view=curContent,from=1;',
  'if(viewSlice){from=viewSlice.startLine;view=curContent.split("\\n").slice(viewSlice.startLine-1,viewSlice.endLine).join("\\n");}',
  'document.getElementById("path").textContent=curPath+(viewSlice?" · L"+viewSlice.startLine+"-"+viewSlice.endLine:"");',
  'document.getElementById("meta").textContent=view.split("\\n").length+" 行 · 只读";',
  'paintHighlight(document.getElementById("codeInner"),view,curPath);syncGutter(view.split("\\n").length,from);',
  'document.getElementById("status").textContent=(viewSlice?"局部浏览":"只读浏览")+" · "+curPath;',
  '}',
  'async function openFile(rel,slice){',
  'if(!window.wh||!window.wh.call)return;',
  'var err=document.getElementById("err"),wrap=document.getElementById("wrap"),empty=document.getElementById("empty");',
  'err.textContent="";',
  'var r=await window.wh.call("codeBrowser","read",[rel]);',
  'if(!r.ok){wrap.style.display="none";empty.style.display="flex";empty.textContent=r.error||"读取失败";return;}',
  'curPath=r.result.path;curContent=r.result.content;',
  'viewSlice=(slice&&slice.startLine&&slice.endLine)?{startLine:slice.startLine,endLine:slice.endLine}:null;',
  'renderView();wrap.style.display="flex";empty.style.display="none";',
  'document.getElementById("reload").style.display="inline-block";',
  'document.getElementById("edit").style.display="inline-block";',
  '}',
  'async function refreshFromDisk(){',
  'if(!curPath)return;var code=document.getElementById("code"),scroll=code.scrollTop;',
  'await openFile(curPath,viewSlice);code.scrollTop=scroll;',
  '}',
  'async function boot(){',
  'if(!window.wh||!window.wh.call)return;',
  'var i=await window.wh.call("codeBrowser","info",[]);',
  'if(i.ok)document.getElementById("status").textContent="root: "+i.result.root;',
  'document.getElementById("code").addEventListener("scroll",syncScroll);',
  'document.getElementById("reload").onclick=function(){if(curPath)openFile(curPath,viewSlice);};',
  'document.getElementById("edit").onclick=function(){if(curPath&&window.wh.openCodeEditor)window.wh.openCodeEditor(curPath);};',
  'bindSliceContextMenu({root:document.getElementById("code"),codeInner:document.getElementById("codeInner"),',
  'getPath:function(){return curPath;},getText:function(){return curContent;}});',
  'startFileSync(function(payload){if(normPath(payload.path)!==normPath(curPath))return;refreshFromDisk();});',
  'var pending=await window.wh.call("codeBrowser","takePendingOpen",[]);',
  'if(pending.ok&&pending.result)await openFile(pending.result);',
  '}',
  'window.__whOpenFile=function(rel){return openFile(rel);};',
  'window.__whOpenTarget=function(t){if(typeof t==="string")return openFile(t);return openFile(t.path,t);};',
  'boot();',
  '</script></body></html>',
].join('');
