import { SYNTAX_CSS, SYNTAX_JS } from './syntax.js';

export const CODE_BROWSER_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  '*{box-sizing:border-box}',
  'body{margin:0;font-family:system-ui,"Microsoft YaHei",sans-serif;background:#16161e;color:#e6e6ef;height:100vh;display:flex;flex-direction:column}',
  '.bar{flex:none;display:flex;align-items:center;gap:8px;padding:8px 12px;border-bottom:1px solid #262634;background:#1b1b24}',
  '.path{font:12px ui-monospace,Consolas,monospace;color:#79c0ff;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.meta{font:11px;color:#8b949e;flex:none}',
  '.btn{background:rgba(121,192,255,.12);border:1px solid rgba(121,192,255,.35);color:#79c0ff;border-radius:6px;padding:4px 12px;cursor:pointer;font-size:12px}',
  '.btn:hover{background:rgba(121,192,255,.2)}',
  '.view-wrap{flex:1;min-height:0;display:flex;overflow:hidden}',
  '.gutter{flex:none;width:44px;overflow:auto;background:#14141e;border-right:1px solid #262634;padding:8px 6px 8px 0;text-align:right;',
  'font:12px/1.45 ui-monospace,Consolas,monospace;color:#6e7681;user-select:none}',
  'pre.code{flex:1;margin:0;padding:8px 10px;overflow:auto;font:12px/1.45 ui-monospace,Consolas,monospace;',
  'white-space:pre;tab-size:2;color:#e6e6ef;scrollbar-gutter:stable}',
  SYNTAX_CSS,
  '.status{flex:none;padding:6px 12px;font-size:11px;color:#8b949e;border-top:1px solid #262634}',
  '.err{color:#ff7b72;padding:12px;font-size:12px}',
  '.empty{flex:1;display:flex;align-items:center;justify-content:center;color:#8b949e;font-size:13px}',
  '</style></head><body>',
  '<div class="bar"><span class="path" id="path">（未打开文件）</span><span class="meta" id="meta"></span>',
  '<button type="button" class="btn" id="reload" style="display:none">重载</button>',
  '<button type="button" class="btn" id="edit" style="display:none">编辑</button></div>',
  '<div class="view-wrap" id="wrap" style="display:none"><pre class="gutter" id="gutter"></pre>',
  '<pre class="code" id="code"><code id="codeInner"></code></pre></div>',
  '<div class="empty" id="empty">等待打开文件…</div>',
  '<div class="err" id="err"></div>',
  '<div class="status" id="status">只读浏览</div>',
  '<script>',
  SYNTAX_JS,
  'var curPath="";',
  'function syncGutter(n){var g=document.getElementById("gutter"),lines=[];for(var i=1;i<=n;i++)lines.push(i);g.textContent=lines.join("\\n");}',
  'function syncScroll(){var g=document.getElementById("gutter"),c=document.getElementById("code");g.scrollTop=c.scrollTop;}',
  'async function openFile(rel){',
  'if(!window.wh||!window.wh.call)return;',
  'var err=document.getElementById("err"),wrap=document.getElementById("wrap"),empty=document.getElementById("empty");',
  'err.textContent="";',
  'var r=await window.wh.call("codeBrowser","read",[rel]);',
  'if(!r.ok){wrap.style.display="none";empty.style.display="flex";empty.textContent=r.error||"读取失败";return;}',
  'curPath=r.result.path;document.getElementById("path").textContent=curPath;',
  'document.getElementById("meta").textContent=r.result.lines+" 行 · 只读";',
  'paintHighlight(document.getElementById("codeInner"),r.result.content,curPath);syncGutter(r.result.lines);',
  'wrap.style.display="flex";empty.style.display="none";',
  'document.getElementById("reload").style.display="inline-block";',
  'document.getElementById("edit").style.display="inline-block";',
  'document.getElementById("status").textContent="只读浏览 · "+curPath;',
  '}',
  'async function boot(){',
  'if(!window.wh||!window.wh.call)return;',
  'var i=await window.wh.call("codeBrowser","info",[]);',
  'if(i.ok)document.getElementById("status").textContent="root: "+i.result.root;',
  'document.getElementById("code").addEventListener("scroll",syncScroll);',
  'document.getElementById("reload").onclick=function(){if(curPath)openFile(curPath);};',
  'document.getElementById("edit").onclick=function(){if(curPath&&window.wh.openCodeEditor)window.wh.openCodeEditor(curPath);};',
  'var pending=await window.wh.call("codeBrowser","takePendingOpen",[]);',
  'if(pending.ok&&pending.result)await openFile(pending.result);',
  '}',
  'window.__whOpenFile=openFile;',
  'boot();',
  '</script></body></html>',
].join('');
