/** 嵌入插件 HTML 的语法高亮 CSS + JS（无外部依赖） */
export const SYNTAX_CSS = [
  '.code-pane .hl-kw{color:#ff7b72}',
  '.code-pane .hl-str{color:#a5d6ff}',
  '.code-pane .hl-cmt{color:#8b949e;font-style:italic}',
  '.code-pane .hl-num{color:#79c0ff}',
  '.code-pane .hl-key{color:#ffa657}',
  '.code-pane .hl-fn{color:#d2a8ff}',
  '.code-pane .hl-type{color:#ffa657}',
  '.code-pane .hl-tag{color:#7ee787}',
  '.code-pane .hl-bool{color:#ff7b72}',
  '.code-pane .hl-op{color:#79c0ff}',
  '.code-pane .hl-attr{color:#e6c07b}',
  '.code-lang-ts .hl-type,.code-lang-js .hl-type{color:#f0883e}',
  '.code-lang-ts .hl-fn,.code-lang-js .hl-fn{color:#d2a8ff}',
  '.code-lang-json .hl-key{color:#79c0ff}',
  '.code-lang-json .hl-str{color:#a5d6ff}',
  '.code-lang-json .hl-num{color:#56d364}',
  '.code-lang-css .hl-key{color:#79c0ff}',
  '.code-lang-css .hl-str{color:#a5d6ff}',
  '.code-lang-css .hl-num{color:#56d364}',
  '.code-lang-html .hl-tag{color:#7ee787}',
  '.code-lang-html .hl-attr{color:#79c0ff}',
  '.code-lang-html .hl-str{color:#a5d6ff}',
  '.code-lang-py .hl-kw{color:#ff7b72}',
  '.code-lang-py .hl-fn{color:#d2a8ff}',
  '.code-lang-py .hl-str{color:#a5d6ff}',
  '.code-lang-py .hl-dec{color:#ffa657}',
  '.code-lang-sh .hl-kw{color:#ff7b72}',
  '.code-lang-sh .hl-str{color:#a5d6ff}',
  '.code-lang-sh .hl-var{color:#79c0ff}',
  '.code-lang-yaml .hl-key{color:#79c0ff}',
  '.code-lang-yaml .hl-str{color:#a5d6ff}',
  '.code-lang-yaml .hl-bool{color:#ff7b72}',
  '.code-lang-md .hl-kw{color:#e6e6ef}',
  'pre.code code{display:block}',
].join('');

export const SYNTAX_JS = [
  'function escHtml(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}',
  'function langOf(path){var m=String(path||"").match(/\\.([^.]+)$/);if(!m)return"plain";',
  'var e=m[1].toLowerCase();',
  'if(e==="ts"||e==="tsx"||e==="mts"||e==="cts")return"ts";',
  'if(e==="js"||e==="jsx"||e==="mjs"||e==="cjs")return"js";',
  'if(e==="json"||e==="jsonc")return"json";',
  'if(e==="css"||e==="scss"||e==="less")return"css";',
  'if(e==="html"||e==="htm"||e==="vue"||e==="svg")return"html";',
  'if(e==="md"||e==="markdown")return"md";',
  'if(e==="py"||e==="pyw")return"py";',
  'if(e==="yaml"||e==="yml")return"yaml";',
  'if(e==="sh"||e==="bash"||e==="zsh")return"sh";',
  'if(e==="toml")return"toml";',
  'if(e==="sql")return"sql";',
  'if(e==="rs")return"rs";',
  'if(e==="go")return"go";',
  'return"plain";}',
  'var HL_TS="abstract async await break case catch class const continue debugger default delete do else enum export extends false finally for from function get if implements import in infer instanceof interface let module namespace new null of package private protected public return set static super switch this throw true try type typeof undefined var void while with yield".split(" ");',
  'var HL_PY="and as assert async await break class continue def del elif else except False finally for from global if import in is lambda None nonlocal not or pass raise return True try while with yield".split(" ");',
  'var HL_SH="if then else elif fi for while do done case esac in function return exit export local readonly".split(" ");',
  'function hlList(word,list){return list.indexOf(word)>=0;}',
  'function hlKw(word,lang){if(lang==="json"||lang==="css"||lang==="html"||lang==="md"||lang==="plain"||lang==="yaml"||lang==="toml")return false;',
  'if(lang==="py")return hlList(word,HL_PY);if(lang==="sh")return hlList(word,HL_SH);return hlList(word,HL_TS);}',
  'function highlightSource(code,path){',
  'var lang=langOf(path),s=escHtml(String(code||"")),ph=[];',
  'function stash(html,cls){var id=ph.length;ph.push({html:html,cls:cls||""});return"\\uE000"+String.fromCharCode(0xF000+id)+"\\uE001";}',
  'function unwrap(){ph.forEach(function(item,idx){var token="\\uE000"+String.fromCharCode(0xF000+idx)+"\\uE001";',
  's=s.split(token).join(item.html);});return s;}',
  'if(lang==="plain"||lang==="md")return s;',
  'if(lang==="json"){',
  's=s.replace(/"([^"\\\\]|\\\\.)*"(\\s*:)/g,function(m,p1,p2){return stash(\'<span class="hl-key">\'+m.slice(0,m.length-p2.length)+"</span>")+p2;});',
  's=s.replace(/"([^"\\\\]|\\\\.)*"/g,function(m){return stash(\'<span class="hl-str">\'+m+"</span>");});',
  's=s.replace(/\\b(true|false|null)\\b/g,function(m){return stash(\'<span class="hl-bool">\'+m+"</span>");});',
  's=s.replace(/\\b-?\\d+\\.?\\d*\\b/g,function(m){return stash(\'<span class="hl-num">\'+m+"</span>");});return unwrap();}',
  'if(lang==="yaml"||lang==="toml"){',
  's=s.replace(/#[^\\n]*/g,function(m){return stash(\'<span class="hl-cmt">\'+m+"</span>");});',
  's=s.replace(/^([\\w.-]+)(\\s*:)/gm,function(m,k,p2){return stash(\'<span class="hl-key">\'+k+"</span>")+p2;});',
  's=s.replace(/"([^"\\\\]|\\\\.)*"|\'([^\'\\\\]|\\\\.)*\'/g,function(m){return stash(\'<span class="hl-str">\'+m+"</span>");});',
  's=s.replace(/\\b(true|false|null|yes|no)\\b/gi,function(m){return stash(\'<span class="hl-bool">\'+m+"</span>");});return unwrap();}',
  'if(lang==="css"){',
  's=s.replace(/\\/\\*[\\s\\S]*?\\*\\//g,function(m){return stash(\'<span class="hl-cmt">\'+m+"</span>");});',
  's=s.replace(/"([^"\\\\]|\\\\.)*"|\'([^\'\\\\]|\\\\.)*\'/g,function(m){return stash(\'<span class="hl-str">\'+m+"</span>");});',
  's=s.replace(/#[0-9a-fA-F]{3,8}\\b/g,function(m){return stash(\'<span class="hl-num">\'+m+"</span>");});',
  's=s.replace(/\\b\\d+\\.?\\d*(?:px|em|rem|%|s|ms|deg|vh|vw)?\\b/g,function(m){return stash(\'<span class="hl-num">\'+m+"</span>");});',
  's=s.replace(/([\\w-]+)(?=\\s*:)/g,function(m){return stash(\'<span class="hl-key">\'+m+"</span>");});return unwrap();}',
  'if(lang==="html"){',
  's=s.replace(/&lt;!--[\\s\\S]*?--&gt;/g,function(m){return stash(\'<span class="hl-cmt">\'+m+"</span>");});',
  's=s.replace(/&lt;\\/?[a-zA-Z][\\w:-]*|\\/?&gt;/g,function(m){return stash(\'<span class="hl-tag">\'+m+"</span>");});',
  's=s.replace(/\\s([\\w:-]+)=/g,function(m,k){return \' <span class="hl-attr">\'+k+"</span>=";});',
  's=s.replace(/"([^"\\\\]|\\\\.)*"|\'([^\'\\\\]|\\\\.)*\'/g,function(m){return stash(\'<span class="hl-str">\'+m+"</span>");});return unwrap();}',
  'if(lang==="py"){',
  's=s.replace(/#[^\\n]*/g,function(m){return stash(\'<span class="hl-cmt">\'+m+"</span>");});',
  's=s.replace(/"""[\\s\\S]*?"""|\'\'\'[\\s\\S]*?\'\'\'/g,function(m){return stash(\'<span class="hl-str">\'+m+"</span>");});',
  's=s.replace(/"(?:\\\\.|[^"\\\\])*"|\'(?:\\\\.|[^\'\\\\])*\'/g,function(m){return stash(\'<span class="hl-str">\'+m+"</span>");});',
  's=s.replace(/\\bdef\\s+([A-Za-z_]\\w*)/g,function(m,n){return \'<span class="hl-kw">def</span> <span class="hl-fn">\'+n+"</span>";});',
  's=s.replace(/\\bclass\\s+([A-Za-z_]\\w*)/g,function(m,n){return \'<span class="hl-kw">class</span> <span class="hl-dec">\'+n+"</span>";});',
  's=s.replace(/\\b[A-Za-z_]\\w*(?=\\s*\\()/g,function(m){if(hlKw(m,"py"))return m;return stash(\'<span class="hl-fn">\'+m+"</span>");});',
  's=s.replace(/\\b[A-Za-z_]\\w*\\b/g,function(m){if(hlKw(m,"py"))return stash(\'<span class="hl-kw">\'+m+"</span>");return m;});return unwrap();}',
  'if(lang==="sh"){',
  's=s.replace(/#[^\\n]*/g,function(m){return stash(\'<span class="hl-cmt">\'+m+"</span>");});',
  's=s.replace(/"(?:\\\\.|[^"\\\\])*"|\'(?:\\\\.|[^\'\\\\])*\'/g,function(m){return stash(\'<span class="hl-str">\'+m+"</span>");});',
  's=s.replace(/\\$[\\w@#?*!-]+/g,function(m){return stash(\'<span class="hl-var">\'+m+"</span>");});',
  's=s.replace(/\\b[A-Za-z_]\\w*\\b/g,function(m){if(hlKw(m,"sh"))return stash(\'<span class="hl-kw">\'+m+"</span>");return m;});return unwrap();}',
  's=s.replace(/\\/\\/[^\\n]*/g,function(m){return stash(\'<span class="hl-cmt">\'+m+"</span>");});',
  's=s.replace(/\\/\\*[\\s\\S]*?\\*\\//g,function(m){return stash(\'<span class="hl-cmt">\'+m+"</span>");});',
  's=s.replace(/"(?:\\\\.|[^"\\\\])*"|\'(?:\\\\.|[^\'\\\\])*\'|`(?:\\\\.|[^`\\\\])*`/g,function(m){return stash(\'<span class="hl-str">\'+m+"</span>");});',
  's=s.replace(/\\b[A-Za-z_$][\\w$]*(?=\\s*\\()/g,function(m){return stash(\'<span class="hl-fn">\'+m+"</span>");});',
  's=s.replace(/\\b[A-Z][a-zA-Z0-9_]*\\b/g,function(m){return stash(\'<span class="hl-type">\'+m+"</span>");});',
  's=s.replace(/\\b-?\\d+\\.?\\d*\\b/g,function(m){return stash(\'<span class="hl-num">\'+m+"</span>");});',
  's=s.replace(/\\b[A-Za-z_$][\\w$]*\\b/g,function(m){if(hlKw(m,lang))return stash(\'<span class="hl-kw">\'+m+"</span>");return m;});',
  'return unwrap();}',
  'function applyLangClass(el,path){',
  'if(!el)return;var pane=el.closest(".code-pane");if(!pane)return;',
  'var lang=langOf(path);pane.className="code-pane code-scroll code code-lang-"+lang;',
  'if(pane.classList.contains("hl"))pane.className="code-pane code-scroll hl code-lang-"+lang;}',
  'function paintHighlight(el,code,path){if(!el)return;applyLangClass(el,path);el.innerHTML=highlightSource(code,path);}',
].join('');
