/** Context Usage 弹窗：深色主题，与 Agent demo 一致 */

export const CONTEXT_USAGE_CSS = [
  '.ctx-modal{position:fixed;inset:0;z-index:100001;display:none;align-items:center;justify-content:center;',
  'background:rgba(0,0,0,.55);padding:16px}',
  '.ctx-modal.open{display:flex}',
  '.ctx-panel{width:min(420px,100%);height:min(480px,calc(100vh - 80px));display:flex;flex-direction:column;',
  'background:#1c1c28;color:#e6e6ef;border:1px solid #30363d;border-radius:12px;',
  'box-shadow:0 20px 50px rgba(0,0,0,.55);overflow:hidden}',
  '.ctx-hdr{flex:none;display:flex;align-items:center;justify-content:space-between;',
  'padding:12px 14px;border-bottom:1px solid #30363d;font:600 14px system-ui}',
  '.ctx-x{border:none;background:transparent;color:#a8a8bd;font-size:18px;line-height:1;',
  'cursor:pointer;padding:4px 8px;border-radius:6px}',
  '.ctx-x:hover{background:rgba(255,255,255,.08);color:#fff}',
  '.ctx-sum{flex:none;display:flex;justify-content:space-between;padding:10px 14px 8px;',
  'font:12px system-ui;color:#8b949e}',
  '.ctx-bar{flex:none;height:6px;margin:0 14px 10px;background:#262634;border-radius:999px;overflow:hidden;display:flex}',
  '.ctx-bar>span{height:100%;min-width:0}',
  '.ctx-list{flex:1;min-height:120px;overflow:auto;padding:0 6px 8px}',
  '.ctx-row{display:flex;align-items:center;gap:10px;padding:8px 10px;border-radius:8px;cursor:pointer}',
  '.ctx-row:hover{background:rgba(255,255,255,.06)}',
  '.ctx-swatch{width:10px;height:10px;border-radius:2px;flex:none}',
  '.ctx-lbl{flex:1;font:13px system-ui;color:#e6e6ef}',
  '.ctx-val{font:12px ui-monospace,Consolas,monospace;color:#8b949e}',
  '.ctx-detail{flex:1;min-height:0;display:none;flex-direction:column;border-top:1px solid #30363d;padding:10px 14px 14px}',
  '.ctx-detail.open{display:flex}',
  '.ctx-detail-h{flex:none;font:600 12px system-ui;color:#a8a8bd;margin-bottom:8px}',
  '.ctx-detail pre{flex:1;min-height:0;margin:0;overflow:auto;white-space:pre-wrap;word-break:break-word;',
  'font:11px/1.45 ui-monospace,Consolas,monospace;color:#c9d1d9}',
  '.ctx-empty{padding:20px 14px;text-align:center;color:#8b949e;font-size:12px}',
  '.ctx-back{flex:none;display:inline-flex;align-items:center;border:none;background:transparent;color:#79c0ff;',
  'font:12px system-ui;cursor:pointer;padding:0 0 8px}',
  '.ctx-back:hover{text-decoration:underline}',
].join('');

export const CONTEXT_USAGE_HTML = [
  '<div class="ctx-modal" id="ctx-modal" aria-hidden="true">',
  '<div class="ctx-panel" role="dialog" aria-label="Context Usage" onclick="event.stopPropagation()">',
  '<div class="ctx-hdr"><span>Context Usage</span>',
  '<button class="ctx-x" id="ctx-close" type="button" aria-label="Close">×</button></div>',
  '<div class="ctx-sum"><span id="ctx-pct">—</span><span id="ctx-tot">—</span></div>',
  '<div class="ctx-bar" id="ctx-bar"></div>',
  '<div class="ctx-list" id="ctx-list"></div>',
  '<div class="ctx-detail" id="ctx-detail">',
  '<button class="ctx-back" id="ctx-back" type="button">← Back</button>',
  '<div class="ctx-detail-h" id="ctx-detail-title"></div>',
  '<pre id="ctx-detail-body"></pre></div>',
  '</div></div>',
].join('');

export const CONTEXT_USAGE_JS = [
  'const CTX_COLORS={"system-prompt":"#6b7280","tool-definitions":"#8b5cf6",rules:"#16a34a",skills:"#d97706",',
  '"mcp-tools":"#db2777",subagents:"#2563eb","runtime-context":"#0d9488",summarized:"#f43f5e",conversation:"#ef4444"};',
  'function fmtTok(n){n=Number(n)||0;if(n>=1e6)return(n/1e6).toFixed(1)+"M";if(n>=1e3)return(n/1e3).toFixed(1)+"K";return String(n);}',
  'let ctxReport=null;',
  'function ctxEl(id){return document.getElementById(id);}',
  'function closeCtxModal(){const m=ctxEl("ctx-modal");if(m){m.classList.remove("open");m.setAttribute("aria-hidden","true");}',
  'hideCtxDetail();}',
  'function showCtxDetail(title,text){const d=ctxEl("ctx-detail"),t=ctxEl("ctx-detail-title"),b=ctxEl("ctx-detail-body"),l=ctxEl("ctx-list");',
  'if(!d||!t||!b)return;t.textContent=title;b.textContent=text||"（空）";d.classList.add("open");if(l)l.style.display="none";}',
  'function hideCtxDetail(){const d=ctxEl("ctx-detail"),l=ctxEl("ctx-list");if(d)d.classList.remove("open");if(l)l.style.display="";}',
  'function renderContextUsage(rep){ctxReport=rep;const list=ctxEl("ctx-list"),bar=ctxEl("ctx-bar"),pct=ctxEl("ctx-pct"),tot=ctxEl("ctx-tot");',
  'if(!list||!bar||!pct||!tot)return;hideCtxDetail();list.style.display="";',
  'const lim=rep.limitTokens||200000,used=rep.totalTokens||0,p=lim?Math.min(100,Math.round(used/lim*100)):0;',
  'pct.textContent=p+"% Full";tot.textContent="~"+fmtTok(used)+" / "+fmtTok(lim)+" Tokens";bar.innerHTML="";',
  'const cats=Array.isArray(rep.categories)?rep.categories:[];',
  'if(!cats.length){list.innerHTML=\'<div class="ctx-empty">暂无上下文数据。发送一条消息后再试。</div>\';return;}',
  'for(const c of cats){const w=used?Math.max(1,Math.round(c.tokens/used*100)):0;const seg=document.createElement("span");',
  'seg.style.width=w+"%";seg.style.background=CTX_COLORS[c.id]||"#9ca3af";bar.appendChild(seg);}',
  'list.innerHTML=cats.map(function(c,i){return \'<div class="ctx-row" data-i="\'+i+\'"><span class="ctx-swatch" style="background:\'',
  '+(CTX_COLORS[c.id]||"#9ca3af")+\'"></span><span class="ctx-lbl">\'+trajEsc(c.label)+\'</span><span class="ctx-val">\'+fmtTok(c.tokens)+\'</span></div>\';}).join("");',
  'list.querySelectorAll(".ctx-row").forEach(function(el){el.onclick=function(){const c=cats[Number(el.getAttribute("data-i"))];if(!c)return;',
  'if(c.breakdown&&c.breakdown.length>1){list.innerHTML=c.breakdown.map(function(b,j){return \'<div class="ctx-row" data-j="\'+j+\'">',
  '<span class="ctx-swatch" style="background:\'+(CTX_COLORS[c.id]||"#9ca3af")+\'"></span><span class="ctx-lbl">\'+trajEsc(b.name)+\'</span>',
  '<span class="ctx-val">\'+fmtTok(b.tokens)+\'</span></div>\';}).join("");',
  'const back=document.createElement("button");back.className="ctx-back";back.type="button";back.textContent="← All categories";',
  'back.onclick=function(){renderContextUsage(rep);};list.insertBefore(back,list.firstChild);',
  'list.querySelectorAll(".ctx-row").forEach(function(row){row.onclick=function(){const b=c.breakdown[Number(row.getAttribute("data-j"))];',
  'if(b)showCtxDetail(c.label+" · "+b.name,b.text);};});}else showCtxDetail(c.label,c.text);};});}',
  'async function openContextUsage(){const modal=ctxEl("ctx-modal"),list=ctxEl("ctx-list");if(!modal||!list)return;',
  'modal.classList.add("open");modal.setAttribute("aria-hidden","false");hideCtxDetail();list.style.display="";',
  'list.innerHTML=\'<div class="ctx-empty">加载中…</div>\';',
  'if(!window.wh||!window.wh.call){list.innerHTML=\'<div class="ctx-empty">窗口桥未就绪</div>\';return;}',
  'try{const args=sessionId?[{sessionId:sessionId}]:[{}];const r=await window.wh.call("promptContext","usage",args);',
  'if(!r.ok){list.innerHTML=\'<div class="ctx-empty">\'+trajEsc(r.error||"读取失败")+"</div>";return;}',
  'renderContextUsage(r.result||{});}catch(e){list.innerHTML=\'<div class="ctx-empty">\'+trajEsc(e)+"</div>";}}',
  'function bindContextUsageUi(){const u=ctxEl("ctx-usage"),c=ctxEl("ctx-close"),b=ctxEl("ctx-back"),m=ctxEl("ctx-modal");',
  'if(u)u.addEventListener("click",function(){openContextUsage();});',
  'if(c)c.addEventListener("click",function(e){e.stopPropagation();closeCtxModal();});',
  'if(b)b.addEventListener("click",function(e){e.preventDefault();hideCtxDetail();});',
  'if(m)m.addEventListener("click",function(){closeCtxModal();});',
  'document.addEventListener("keydown",function(e){if(e.key==="Escape"&&m&&m.classList.contains("open"))closeCtxModal();});}',
  'bindContextUsageUi();',
].join('');
