import { formatsListHtml, renderMarkdown } from './markdown.js';
import { TRAJECTORY_VIEW_CSS, TRAJECTORY_VIEW_JS } from './traj-view.js';
import { CONTEXT_USAGE_CSS, CONTEXT_USAGE_HTML, CONTEXT_USAGE_JS } from './context-usage.js';

export const APP_UI_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  'html,body{height:100%;margin:0;overflow:hidden}',
  'body{display:flex;flex-direction:column;background:#12121a;color:#e6e6ef;',
  'font:13px/1.55 system-ui,"Segoe UI","Microsoft YaHei",sans-serif}',
  '.app{flex:1;min-height:0;display:flex;flex-direction:column}',
  '.bar{flex:none;display:flex;align-items:center;gap:8px;padding:8px 12px;border-bottom:1px solid #262634;flex-wrap:wrap}',
  '.bar label{display:flex;gap:5px;align-items:center;color:#8b949e;font-size:12px;cursor:pointer}',
  '.bar .sep{width:1px;height:18px;background:#30363d;margin:0 2px}',
  '.ghost{background:transparent;border:1px solid #3d444d;color:#c9d1d9;border-radius:8px;',
  'padding:4px 10px;font:12px system-ui;cursor:pointer;transition:background .15s,border-color .15s}',
  '.ghost:hover{background:#21262d;border-color:#484f58}',
  CONTEXT_USAGE_CSS,
  '.fmt-lab{color:#6e7681;font-size:11px}',
  '.formats{display:flex;gap:6px;list-style:none;margin:0;padding:0}',
  '.formats li{font:11px ui-monospace,Consolas,monospace;color:#7ee787;',
  'border:1px solid rgba(126,231,135,.35);border-radius:999px;padding:1px 8px}',
  '#ws{flex:1;min-width:120px;max-width:min(36vw,280px);background:#1a1a24;border:1px solid #333;border-radius:8px;',
  'color:#e6e6ef;padding:4px 8px;font:11px ui-monospace,Consolas,monospace}',
  '#ws:disabled{opacity:.55}',
  '#neu{margin-left:auto}',
  '#aid{max-width:120px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#d2a8ff;font:11px ui-monospace,Consolas,monospace}',
  '#sb{max-width:180px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#8b949e;font:11px ui-monospace,Consolas,monospace}',
  '.gap-banner{flex:none;padding:10px 14px;background:#3a1f22;color:#ffb4ae;border-bottom:1px solid #5c2a2a;font-size:12px;line-height:1.5}',
  '.body-row{flex:1;min-height:0;display:flex}',
  '.sessions{flex:none;width:248px;min-width:200px;border-right:1px solid #262634;display:flex;flex-direction:column;min-height:0;background:#0f0f16}',
  '.sessions-h{flex:none;display:flex;align-items:center;justify-content:space-between;gap:8px;padding:10px 12px 8px;font:600 12px system-ui;color:#e6e6ef}',
  '.sessions-h b{font:600 11px system-ui;color:#8b949e;background:#1a1a24;border-radius:999px;padding:1px 7px;margin-left:6px}',
  '.sessions-tools{flex:none;padding:0 10px 8px}',
  '#sess-q{width:100%;box-sizing:border-box;background:#1a1a24;border:1px solid #2c2c3e;border-radius:8px;color:#e6e6ef;padding:6px 8px;font:12px system-ui}',
  '#sess-q:focus{outline:none;border-color:#388bfd}',
  '#sess-list{flex:1;min-height:0;overflow:auto;padding:4px 8px 10px}',
  '.sess-empty{color:#8b949e;text-align:center;padding:28px 12px;line-height:1.55;font-size:12px}',
  '.sess-empty span{display:block;margin-top:4px;color:#6e7681}',
  '.sess{position:relative;padding:9px 32px 9px 10px;border-radius:10px;margin-bottom:4px;cursor:pointer;border:1px solid transparent}',
  '.sess:hover{background:#1a1a24}',
  '.sess.active{border-color:rgba(56,139,253,.55);background:rgba(56,139,253,.1)}',
  '.sess-title{font:600 12.5px/1.35 system-ui;color:#e6e6ef;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}',
  '.sess-meta{margin-top:4px;font:11px system-ui;color:#8b949e}',
  '.sess-prev{margin-top:3px;font:11px/1.4 system-ui;color:#6e7681;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}',
  '.sess-del{position:absolute;top:7px;right:6px;opacity:0;background:#3a1f22;border:1px solid #5c2a2a;color:#ffb4ae;border-radius:6px;padding:1px 6px;font:11px system-ui;cursor:pointer}',
  '.sess:hover .sess-del,.sess.active .sess-del,.sess-del:focus{opacity:1}',
  '.sess-del:hover{background:#5c2a2a}',
  '.chat-col{flex:1;min-width:0;display:flex;flex-direction:column;min-height:0}',
  '.main{flex:1;min-height:0;display:flex;min-width:0}',
  '#log{flex:1;min-width:0;overflow:auto;padding:16px 18px;scrollbar-width:none}',
  '#log::-webkit-scrollbar{display:none;width:0;height:0}',
  '.empty{color:#8b949e;text-align:center;margin-top:18vh}',
  '.row{display:flex;margin:0 0 10px}.row.user{justify-content:flex-end}',
  '.b{max-width:78%;padding:9px 12px;border-radius:14px;white-space:pre-wrap;word-break:break-word}',
  '.b.user{background:#1b4f72;color:#eaf6ff;border-bottom-right-radius:4px}',
  '.b.bot{background:#1c1c28;border-bottom-left-radius:4px}.b.err{color:#ffb4ae;background:#3a1f22}.b.pending{color:#8b949e}',
  '.b.md{white-space:normal}',
  '.b.md p{margin:0 0 .55em}.b.md p:last-child{margin:0}',
  '.b.md h1,.b.md h2,.b.md h3,.b.md h4{margin:.15em 0 .4em;line-height:1.3;font-size:14px}',
  '.b.md h1{font-size:16px}.b.md h2{font-size:15px}',
  '.b.md ul,.b.md ol{margin:.15em 0 .5em;padding-left:1.25em}',
  '.b.md li{margin:.15em 0}',
  '.b.md blockquote{margin:.35em 0;padding:0 0 0 10px;border-left:3px solid #30363d;color:#a8a8bd}',
  '.b.md a{color:#79c0ff}',
  '.b.md code{font:12px/1.45 ui-monospace,Consolas,monospace;background:#12121a;padding:1px 5px;border-radius:4px}',
  '.b.md pre{margin:.4em 0;padding:8px 10px;background:#12121a;border:1px solid #262634;border-radius:8px;overflow:auto}',
  '.b.md pre code{background:none;padding:0;display:block;white-space:pre}',
  '.rail{flex:none;width:300px;min-width:220px;max-width:42%;border-left:1px solid #262634;',
  'display:flex;flex-direction:column;min-height:0;background:#0f0f16}',
  '.rail-h{flex:none;padding:8px 12px;font:600 12px system-ui;color:#a8a8bd;border-bottom:1px solid #262634}',
  '#traj{flex:1;min-height:0}',
  '.app.no-traj .rail{display:none}',
  'footer{flex:none;padding:10px 12px 12px;border-top:1px solid #262634;background:#0f0f16}',
  '.compose{display:flex;gap:8px;align-items:flex-end}',
  '.compose-actions{display:flex;flex-direction:column;gap:6px;flex:none}',
  'textarea{flex:1;min-height:52px;max-height:120px;resize:vertical;background:#1a1a24;color:#e6e6ef;',
  'border:1px solid #3d444d;border-radius:10px;padding:10px 12px;font:13px inherit;line-height:1.45}',
  'textarea:focus{outline:none;border-color:#388bfd;box-shadow:0 0 0 2px rgba(56,139,253,.25)}',
  '#ctx-usage{min-width:76px;height:36px;padding:0 10px}',
  '#go,#cancel{min-width:76px;height:44px;border:none;border-radius:10px;font:600 13px system-ui;cursor:pointer}',
  '#go{background:#238636;color:#fff}',
  '#cancel{background:#3a1f22;color:#ffb4ae;border:1px solid #5c2a2a;display:none}',
  '#go:disabled,#cancel:disabled{opacity:.4}',
  TRAJECTORY_VIEW_CSS,
  '</style></head><body><div class="app" id="app">',
  '<div class="gap-banner" id="gap" hidden>上下文组装器（prompt-context）未装入，无法作为完整助手使用。</div>',
  '<div class="bar"><label><input type="checkbox" id="tools" checked> 工具</label>',
  '<label><input type="checkbox" id="show-traj" checked> 轨迹</label>',
  '<span class="sep"></span>',
  '<span class="fmt-lab">工作区</span>',
  '<input id="ws" placeholder="本会话工作区路径" spellcheck="false" />',
  '<span class="sep"></span>',
  '<span id="aid" title="">agent …</span><span id="sb" title="">沙箱…</span>',
  '<span class="sep"></span>',
  '<span class="fmt-lab">渲染</span>',
  formatsListHtml(),
  '<button class="ghost" id="neu" type="button">New Session</button></div>',
  '<div class="body-row">',
  '<aside class="sessions"><div class="sessions-h"><span>会话<b id="sess-count">0</b></span></div>',
  '<div class="sessions-tools"><input id="sess-q" type="search" placeholder="搜索会话" spellcheck="false" /></div>',
  '<div id="sess-list"></div></aside>',
  '<div class="chat-col"><div class="main"><div id="log"><div class="empty">Enter 发送。左侧可选会话继续聊，悬停可删除。</div></div>',
  '<aside class="rail"><div class="rail-h">本轮轨迹</div><div id="traj" class="traj-root"></div></aside></div>',
  '<footer><div class="compose"><textarea id="box" placeholder="问点什么…" rows="2"></textarea>',
  '<div class="compose-actions"><button class="ghost" id="ctx-usage" type="button" title="查看上下文用量">上下文</button>',
  '<button id="cancel" type="button">取消</button><button id="go" type="button">发送</button></div></div></footer></div>',
  '</div></div>',
  CONTEXT_USAGE_HTML,
  '<script>',
  TRAJECTORY_VIEW_JS,
  renderMarkdown.toString(),
  'function mdHtml(s){try{return renderMarkdown(String(s||""));}catch(e){return String(s||"");}}',
  'let agentId=null,sessionId=null,busy=false,trajTimer=null,deltaTimer=null,lastKey="",promptReady=true,eventCursor=0,activeSid=null;',
  'const log=document.getElementById("log"),box=document.getElementById("box"),go=document.getElementById("go"),cancel=document.getElementById("cancel"),ws=document.getElementById("ws");',
  'const app=document.getElementById("app"),traj=document.getElementById("traj"),gap=document.getElementById("gap"),aid=document.getElementById("aid");',
  'const sessList=document.getElementById("sess-list"),sessQ=document.getElementById("sess-q");',
  'let sessRows=[],sessSelectId=null;',
  'function relTime(ts){var n=Date.now()-Number(ts||0);if(!Number.isFinite(n)||n<0)return "";if(n<60000)return "刚刚";if(n<3600000)return Math.floor(n/60000)+" 分钟前";var d=new Date(ts),now=new Date();if(d.toDateString()===now.toDateString())return d.toLocaleTimeString("zh-CN",{hour12:false,hour:"2-digit",minute:"2-digit"});return d.toLocaleDateString("zh-CN",{month:"2-digit",day:"2-digit"});}',
  'function sessLabel(row){return String(row.title||row.preview||"空会话").replace(/\\s+/g," ").trim()||"空会话";}',
  'function renderSessList(){if(!sessList)return;var count=document.getElementById("sess-count");if(count)count.textContent=String(sessRows.length);var q=(sessQ&&sessQ.value||"").trim().toLowerCase();var rows=sessRows.filter(function(row){if(!q)return true;return sessLabel(row).toLowerCase().indexOf(q)>=0||String(row.id).toLowerCase().indexOf(q)>=0;});if(!sessRows.length){sessList.innerHTML=\'<div class="sess-empty">还没有会话<span>发送一条消息就会出现在这里</span></div>\';return;}if(!rows.length){sessList.innerHTML=\'<div class="sess-empty">没有匹配的会话</div>\';return;}sessList.innerHTML="";rows.forEach(function(row){var el=document.createElement("div");el.className="sess"+(sessSelectId&&row.id===sessSelectId?" active":"");el.setAttribute("data-id",row.id);var del=document.createElement("button");del.type="button";del.className="sess-del";del.title="删除会话";del.textContent="删除";del.addEventListener("click",function(ev){ev.preventDefault();ev.stopPropagation();deleteSession(row.id);});var title=document.createElement("div");title.className="sess-title";title.textContent=sessLabel(row);var meta=document.createElement("div");meta.className="sess-meta";meta.textContent=relTime(row.updatedAt||row.startedAt);el.appendChild(del);el.appendChild(title);el.appendChild(meta);if(row.preview&&row.title&&row.preview!==row.title){var prev=document.createElement("div");prev.className="sess-prev";prev.textContent=row.preview;el.appendChild(prev);}el.addEventListener("click",function(){loadSession(row.id);});sessList.appendChild(el);});}',
  'function setAgentChip(id){if(!aid)return;if(id){aid.textContent="agent "+id.slice(0,8);aid.title=id;}else{aid.textContent="agent —";aid.title="尚未 spawn";}}',
  'function setPromptGap(on,msg){promptReady=!on;if(gap){gap.hidden=!on;if(msg)gap.textContent=msg;}if(box)box.disabled=on;if(go)go.disabled=on||busy;if(on&&log){log.innerHTML=\'<div class="empty err">\'+(msg||"上下文组装器未装入")+"</div>";}}',
  'async function pullPromptContext(){if(!window.wh||!window.wh.call){setPromptGap(true,"窗口桥未就绪");return;}try{const r=await window.wh.call("promptContext","inspect",[]);if(!r.ok){const msg=String(r.error||"");setPromptGap(true,msg.indexOf("不可用")>=0?"上下文组装器（prompt-context）未装入，无法作为完整助手使用。":msg);return;}setPromptGap(false);}catch(e){setPromptGap(true,String(e));}}',
  'function humanError(msg){const s=String(msg||"");if(/已取消|aborted|cancel/i.test(s))return{title:"已取消",detail:"生成被中断。",hint:"可重新发送。"};if(/401|403|api key|apikey|鉴权|unauthorized/i.test(s))return{title:"模型鉴权失败",detail:s,hint:"检查 WH_LLM_API_KEY 或 wizard.patch.json。"};if(/timeout|ETIMEDOUT|timed out/i.test(s))return{title:"请求超时",detail:s,hint:"稍后重试或换模型。"};if(/tools\\[\\d+\\]\\.function\\.name|does not match pattern/i.test(s))return{title:"工具名不合法",detail:"模型 API 拒绝带点号的工具名（如 box.open_folder）。",hint:"已自动转换；请重启 GUI 后再试。"};if(/未知工具/i.test(s))return{title:"工具调用失败",detail:s,hint:"详见右侧轨迹。"};if(/步数|max-cycles|maxSteps/i.test(s))return{title:"步数用尽",detail:s,hint:"任务太复杂，可拆分问题。"};if(/prompt-context|组装器/i.test(s))return{title:"上下文组装器不可用",detail:s,hint:"装入 prompt-context 插件。"};return{title:"出错了",detail:s,hint:"详见右侧轨迹。"};}',
  'function showError(bubble,msg){const e=humanError(msg);bubble.classList.remove("pending","md");bubble.classList.add("err");bubble.textContent=e.title+"\\n"+e.detail+"\\n（"+e.hint+"）";}',
  'function fillBot(el,text){el.classList.remove("pending","err");el.classList.add("md");el.innerHTML=mdHtml(text||"（空回复）");}',
  'function add(role,text,cls){const empty=log.querySelector(".empty");if(empty)empty.remove();const row=document.createElement("div");row.className="row "+(role==="user"?"user":"bot");const b=document.createElement("div");b.className="b "+(role==="user"?"user":"bot")+(cls?" "+cls:"");if(role!=="user"&&!cls){b.classList.add("md");b.innerHTML=mdHtml(text);}else b.textContent=text;row.appendChild(b);log.appendChild(row);log.scrollTop=log.scrollHeight;return b;}',
  'function renderMessages(msgs){log.innerHTML="";if(!msgs||!msgs.length){log.innerHTML=\'<div class="empty">会话已加载，继续发送即可。</div>\';return;}for(const m of msgs){if(m.role==="system")continue;if(m.role==="tool")continue;add(m.role==="user"?"user":"bot",m.content);}}',
  'async function syncEventCursor(){if(!window.wh||!window.wh.eventsHistory)return;try{const h=await window.wh.eventsHistory();eventCursor=Array.isArray(h)?h.length:0;}catch(e){eventCursor=0;}}',
  'function watchDeltas(on,bubble){if(deltaTimer){clearInterval(deltaTimer);deltaTimer=null;}if(!on)return;deltaTimer=setInterval(async function(){if(!window.wh||!window.wh.eventsHistory||!bubble)return;try{const events=await window.wh.eventsHistory();if(!Array.isArray(events))return;for(let i=eventCursor;i<events.length;i++){const e=events[i];if(e.action==="agent-loop/start"&&e.payload&&e.payload.sessionId&&(!agentId||e.target===agentId)){activeSid=e.payload.sessionId;sessionId=activeSid;}if(e.action!=="llm/delta"||!e.payload||!e.payload.chunk)continue;if(activeSid&&e.target!==activeSid)continue;if(bubble.textContent==="正在回复…")bubble.textContent="";bubble.classList.remove("pending","md");bubble.textContent+=e.payload.chunk;log.scrollTop=log.scrollHeight;}eventCursor=events.length;}catch(e){}},80);}',
  'async function pullTraj(){if(!window.wh||!window.wh.call){renderTrajectory(traj,null);return;}try{const r=await window.wh.call("trajectory","latest",[]);if(!r.ok){if(r.error&&String(r.error).indexOf("不可用")>=0){traj.innerHTML=\'<div class="traj-empty">轨迹插件未装入。</div>\';return;}traj.innerHTML=\'<div class="traj-empty">\'+trajEsc(r.error||"读取失败")+"</div>";return;}const snap=r.result;const key=snap?(snap.id+":"+(snap.spans?snap.spans.length:0)):"0";if(key===lastKey)return;lastKey=key;renderTrajectory(traj,snap);const list=traj.querySelector(".traj-list");if(list)list.scrollTop=list.scrollHeight;}catch(e){traj.innerHTML=\'<div class="traj-empty">\'+trajEsc(e)+"</div>";}}',
  'function watchTraj(on){if(trajTimer){clearInterval(trajTimer);trajTimer=null;}if(on){pullTraj();trajTimer=setInterval(pullTraj,450);}}',
  'async function pullSessions(selectId){sessSelectId=selectId||null;if(!window.wh||!window.wh.call||!sessList)return;try{const r=await window.wh.call("appChat","listSessions",[]);if(!r.ok){sessList.innerHTML=\'<div class="sess-empty">\'+trajEsc(r.error||"无法加载")+"</div>";return;}sessRows=r.result||[];renderSessList();}catch(e){sessList.innerHTML=\'<div class="sess-empty">\'+trajEsc(e)+"</div>";}}',
  'async function resetComposer(){agentId=null;sessionId=null;activeSid=null;setAgentChip(null);if(ws){ws.disabled=false;ws.value="";}log.innerHTML=\'<div class="empty">New session started. 工作区在首次发送时写入这条会话。</div>\';}',
  'async function deleteSession(id){if(!id||!window.wh||!window.wh.call)return;if(busy&&sessionId===id){alert("这条会话正在回复，请先取消或等它结束。");return;}if(!confirm("删除这条会话？无法恢复。"))return;try{const r=await window.wh.call("appChat","deleteSession",[id]);if(!r.ok){alert(r.error||"删除失败");return;}if(sessionId===id)await resetComposer();await pullSessions(sessionId===id?null:sessionId);}catch(e){alert(String(e));}}',
  'async function loadSession(id){if(!id||busy||!window.wh||!window.wh.call)return;try{const r=await window.wh.call("appChat","resumeSession",[id]);if(!r.ok){add("bot",humanError(r.error).title+"\\n"+humanError(r.error).detail,"err");return;}agentId=r.result.agentId;sessionId=r.result.sessionId;activeSid=sessionId;setAgentChip(agentId);if(ws)ws.disabled=true;renderMessages(r.result.messages||[]);await pullSessions(sessionId);}catch(e){add("bot",String(e),"err");}}',
  'async function send(){const q=box.value.trim();if(!q||busy||!promptReady||!window.wh||!window.wh.call)return;busy=true;go.disabled=true;cancel.style.display="inline-block";cancel.disabled=false;box.value="";add("user",q);const pending=add("bot","正在回复…","pending");lastKey="";activeSid=sessionId;await syncEventCursor();watchDeltas(true,pending);watchTraj(true);try{const r=await window.wh.call("appChat","send",[{agentId:agentId||undefined,sessionId:sessionId||undefined,prompt:q,useTools:document.getElementById("tools").checked,workspace:(agentId||sessionId)?undefined:(ws&&ws.value.trim()?ws.value.trim():undefined)}]);watchDeltas(false,pending);if(r.ok&&r.result){if(r.result.agentId){agentId=r.result.agentId;setAgentChip(agentId);}if(r.result.sessionId){sessionId=r.result.sessionId;activeSid=sessionId;}if(r.result.workspace&&ws)ws.value=r.result.workspace;if(ws)ws.disabled=true;fillBot(pending,r.result.text);await pullSessions(sessionId);}else{showError(pending,r.error||"失败");}}catch(e){watchDeltas(false,pending);showError(pending,e);}await pullTraj();watchTraj(false);busy=false;go.disabled=false;cancel.style.display="none";box.focus();}',
  'async function doCancel(){if(!busy||!agentId||!window.wh||!window.wh.call)return;cancel.disabled=true;try{await window.wh.call("appChat","cancel",[agentId]);}catch(e){}}',
  'go.onclick=send;cancel.onclick=doCancel;',
  'box.addEventListener("keydown",function(e){if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send();}});',
  'document.getElementById("neu").onclick=function(){if(busy)return;resetComposer();pullSessions(null);box.focus();};',
  'if(sessQ)sessQ.addEventListener("input",function(){renderSessList();});',
  'document.getElementById("show-traj").onchange=function(){app.classList.toggle("no-traj",!this.checked);};',
  'async function pullSandbox(){const chip=document.getElementById("sb");if(!window.wh||!window.wh.call){chip.textContent="沙箱不可用";return;}try{const r=await window.wh.call("sandbox","info",[]);if(!r.ok){chip.textContent=(r.error&&String(r.error).indexOf("不可用")>=0)?"沙箱未装入":(r.error||"沙箱失败");chip.title="";return;}chip.textContent="沙箱 "+r.result.root;chip.title=r.result.root;}catch(e){chip.textContent=String(e);}}',
  CONTEXT_USAGE_JS,
  'renderTrajectory(traj,null);pullTraj();pullSandbox();pullPromptContext();pullSessions(null);setAgentChip(null);syncEventCursor();box.focus();',
  '</script></body></html>',
].join('');
