import { formatsListHtml, renderMarkdown } from './markdown.js';
import { TRAJECTORY_VIEW_CSS, TRAJECTORY_VIEW_JS } from './traj-view.js';

export const APP_UI_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  'html,body{height:100%;margin:0;overflow:hidden}',
  'body{display:flex;flex-direction:column;background:#12121a;color:#e6e6ef;',
  'font:13px/1.55 system-ui,"Segoe UI","Microsoft YaHei",sans-serif}',
  '.app{flex:1;min-height:0;display:flex;flex-direction:column}',
  '.bar{flex:none;display:flex;align-items:center;gap:10px;padding:8px 14px;border-bottom:1px solid #262634}',
  '.bar label{display:flex;gap:6px;align-items:center;color:#8b949e;font-size:12px}',
  '.ghost{background:transparent;border:1px solid #333;color:#a8a8bd;border-radius:8px;',
  'padding:4px 10px;font:12px system-ui;cursor:pointer}',
  '.fmt-lab{color:#6e7681;font-size:11px}',
  '.formats{display:flex;gap:6px;list-style:none;margin:0;padding:0}',
  '.formats li{font:11px ui-monospace,Consolas,monospace;color:#7ee787;',
  'border:1px solid rgba(126,231,135,.35);border-radius:999px;padding:1px 8px}',
  '#ws{flex:1;min-width:140px;max-width:220px;background:#1a1a24;border:1px solid #333;border-radius:8px;',
  'color:#e6e6ef;padding:4px 8px;font:11px ui-monospace,Consolas,monospace}',
  '#ws:disabled{opacity:.55}',
  '#neu{margin-left:auto}',
  '#aid{max-width:120px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#d2a8ff;font:11px ui-monospace,Consolas,monospace}',
  '#sb{max-width:180px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#8b949e;font:11px ui-monospace,Consolas,monospace}',
  '.gap-banner{flex:none;padding:10px 14px;background:#3a1f22;color:#ffb4ae;border-bottom:1px solid #5c2a2a;font-size:12px;line-height:1.5}',
  '.body-row{flex:1;min-height:0;display:flex}',
  '.sessions{flex:none;width:200px;min-width:160px;border-right:1px solid #262634;display:flex;flex-direction:column;min-height:0;background:#0f0f16}',
  '.sessions-h{flex:none;padding:8px 10px;font:600 11px system-ui;color:#a8a8bd;border-bottom:1px solid #262634}',
  '#sess-list{flex:1;min-height:0;overflow:auto;padding:6px}',
  '.sess{padding:8px 10px;border-radius:8px;margin-bottom:4px;cursor:pointer;border:1px solid transparent}',
  '.sess:hover{background:#1a1a24}',
  '.sess.active{border-color:#388bfd;background:rgba(56,139,253,.08)}',
  '.sess-id{font:11px ui-monospace,Consolas,monospace;color:#79c0ff}',
  '.sess-meta{margin-top:3px;font:11px system-ui;color:#8b949e;line-height:1.35}',
  '.chat-col{flex:1;min-width:0;display:flex;flex-direction:column;min-height:0}',
  '.main{flex:1;min-height:0;display:flex;min-width:0}',
  '#log{flex:1;min-width:0;overflow:auto;padding:16px 18px;scrollbar-width:none}',
  '#log::-webkit-scrollbar{display:none;width:0;height:0}',
  '.empty{color:#8b949e;text-align:center;margin-top:18vh}',
  '.row{display:flex;margin:0 0 10px}.row.user{justify-content:flex-end}',
  '.b{max-width:78%;padding:9px 12px;border-radius:14px;white-space:pre-wrap;word-break:break-word}',
  '.b.user{background:#1b4f72;color:#eaf6ff;border-bottom-right-radius:4px}',
  '.b.bot{background:#1c1c28;border-bottom-left-radius:4px}.b.err{color:#ffb4ae;background:#3a1f22}.b.pending{color:#8b949e}',
  '.b.md{white-space:normal}',
  '.b.md p{margin:0 0 .55em}.b.md p:last-child{margin:0}',
  '.b.md h1,.b.md h2,.b.md h3,.b.md h4{margin:.15em 0 .4em;line-height:1.3;font-size:14px}',
  '.b.md h1{font-size:16px}.b.md h2{font-size:15px}',
  '.b.md ul,.b.md ol{margin:.15em 0 .5em;padding-left:1.25em}',
  '.b.md li{margin:.15em 0}',
  '.b.md blockquote{margin:.35em 0;padding:0 0 0 10px;border-left:3px solid #30363d;color:#a8a8bd}',
  '.b.md a{color:#79c0ff}',
  '.b.md code{font:12px/1.45 ui-monospace,Consolas,monospace;background:#12121a;padding:1px 5px;border-radius:4px}',
  '.b.md pre{margin:.4em 0;padding:8px 10px;background:#12121a;border:1px solid #262634;border-radius:8px;overflow:auto}',
  '.b.md pre code{background:none;padding:0;display:block;white-space:pre}',
  '.rail{flex:none;width:300px;min-width:220px;max-width:42%;border-left:1px solid #262634;',
  'display:flex;flex-direction:column;min-height:0;background:#0f0f16}',
  '.rail-h{flex:none;padding:8px 12px;font:600 12px system-ui;color:#a8a8bd;border-bottom:1px solid #262634}',
  '#traj{flex:1;min-height:0}',
  '.app.no-traj .rail{display:none}',
  'footer{flex:none;padding:10px 14px 12px;border-top:1px solid #262634}',
  '.compose{display:flex;gap:8px}',
  'textarea{flex:1;min-height:44px;max-height:44px;resize:none;background:#1a1a24;color:#e6e6ef;',
  'border:1px solid #333;border-radius:10px;padding:9px 11px;font:13px inherit}',
  '#go,#cancel{min-width:64px;height:44px;border:none;border-radius:10px;font:600 13px system-ui;cursor:pointer}',
  '#go{background:#238636;color:#fff}',
  '#cancel{background:#3a1f22;color:#ffb4ae;border:1px solid #5c2a2a;display:none}',
  '#go:disabled,#cancel:disabled{opacity:.4}',
  TRAJECTORY_VIEW_CSS,
  '</style></head><body><div class="app" id="app">',
  '<div class="gap-banner" id="gap" hidden>上下文组装器（prompt-context）未装入，无法作为完整助手使用。</div>',
  '<div class="bar"><label><input type="checkbox" id="tools" checked> 工具</label>',
  '<label><input type="checkbox" id="show-traj" checked> 轨迹</label>',
  '<span class="fmt-lab">工作区</span>',
  '<input id="ws" placeholder="本会话工作区路径" spellcheck="false" />',
  '<span id="aid" title="">agent …</span><span id="sb" title="">沙箱…</span>',
  '<span class="fmt-lab">渲染</span>',
  formatsListHtml(),
  '<button class="ghost" id="neu" type="button">New Session</button></div>',
  '<div class="body-row">',
  '<aside class="sessions"><div class="sessions-h">历史会话</div><div id="sess-list"></div></aside>',
  '<div class="chat-col"><div class="main"><div id="log"><div class="empty">Enter 发送。左侧可选历史会话继续聊。</div></div>',
  '<aside class="rail"><div class="rail-h">本轮轨迹</div><div id="traj" class="traj-root"></div></aside></div>',
  '<footer><div class="compose"><textarea id="box" placeholder="问点什么…"></textarea>',
  '<button id="cancel" type="button">取消</button><button id="go" type="button">发送</button></div></footer></div>',
  '</div><script>',
  TRAJECTORY_VIEW_JS,
  renderMarkdown.toString(),
  'function mdHtml(s){try{return renderMarkdown(String(s||""));}catch(e){return String(s||"");}}',
  'let agentId=null,sessionId=null,busy=false,trajTimer=null,deltaTimer=null,lastKey="",promptReady=true,eventCursor=0,activeSid=null;',
  'const log=document.getElementById("log"),box=document.getElementById("box"),go=document.getElementById("go"),cancel=document.getElementById("cancel"),ws=document.getElementById("ws");',
  'const app=document.getElementById("app"),traj=document.getElementById("traj"),gap=document.getElementById("gap"),aid=document.getElementById("aid");',
  'const sessList=document.getElementById("sess-list");',
  'function setAgentChip(id){if(!aid)return;if(id){aid.textContent="agent "+id.slice(0,8);aid.title=id;}else{aid.textContent="agent —";aid.title="尚未 spawn";}}',
  'function setPromptGap(on,msg){promptReady=!on;if(gap){gap.hidden=!on;if(msg)gap.textContent=msg;}if(box)box.disabled=on;if(go)go.disabled=on||busy;if(on&&log){log.innerHTML=\'<div class="empty err">\'+(msg||"上下文组装器未装入")+"</div>";}}',
  'async function pullPromptContext(){if(!window.wh||!window.wh.call){setPromptGap(true,"窗口桥未就绪");return;}try{const r=await window.wh.call("promptContext","inspect",[]);if(!r.ok){const msg=String(r.error||"");setPromptGap(true,msg.indexOf("不可用")>=0?"上下文组装器（prompt-context）未装入，无法作为完整助手使用。":msg);return;}setPromptGap(false);}catch(e){setPromptGap(true,String(e));}}',
  'function humanError(msg){const s=String(msg||"");if(/已取消|aborted|cancel/i.test(s))return{title:"已取消",detail:"生成被中断。",hint:"可重新发送。"};if(/401|403|api key|apikey|鉴权|unauthorized/i.test(s))return{title:"模型鉴权失败",detail:s,hint:"检查 WH_LLM_API_KEY 或 wizard.patch.json。"};if(/timeout|ETIMEDOUT|timed out/i.test(s))return{title:"请求超时",detail:s,hint:"稍后重试或换模型。"};if(/未知工具/i.test(s))return{title:"工具调用失败",detail:s,hint:"详见右侧轨迹。"};if(/步数|max-cycles|maxSteps/i.test(s))return{title:"步数用尽",detail:s,hint:"任务太复杂，可拆分问题。"};if(/prompt-context|组装器/i.test(s))return{title:"上下文组装器不可用",detail:s,hint:"装入 prompt-context 插件。"};return{title:"出错了",detail:s,hint:"详见右侧轨迹。"};}',
  'function showError(bubble,msg){const e=humanError(msg);bubble.classList.remove("pending","md");bubble.classList.add("err");bubble.textContent=e.title+"\\n"+e.detail+"\\n（"+e.hint+"）";}',
  'function fillBot(el,text){el.classList.remove("pending","err");el.classList.add("md");el.innerHTML=mdHtml(text||"（空回复）");}',
  'function add(role,text,cls){const empty=log.querySelector(".empty");if(empty)empty.remove();const row=document.createElement("div");row.className="row "+(role==="user"?"user":"bot");const b=document.createElement("div");b.className="b "+(role==="user"?"user":"bot")+(cls?" "+cls:"");if(role!=="user"&&!cls){b.classList.add("md");b.innerHTML=mdHtml(text);}else b.textContent=text;row.appendChild(b);log.appendChild(row);log.scrollTop=log.scrollHeight;return b;}',
  'function renderMessages(msgs){log.innerHTML="";if(!msgs||!msgs.length){log.innerHTML=\'<div class="empty">会话已加载，继续发送即可。</div>\';return;}for(const m of msgs){if(m.role==="system")continue;if(m.role==="tool")continue;add(m.role==="user"?"user":"bot",m.content);}}',
  'async function syncEventCursor(){if(!window.wh||!window.wh.eventsHistory)return;try{const h=await window.wh.eventsHistory();eventCursor=Array.isArray(h)?h.length:0;}catch(e){eventCursor=0;}}',
  'function watchDeltas(on,bubble){if(deltaTimer){clearInterval(deltaTimer);deltaTimer=null;}if(!on)return;deltaTimer=setInterval(async function(){if(!window.wh||!window.wh.eventsHistory||!bubble)return;try{const events=await window.wh.eventsHistory();if(!Array.isArray(events))return;for(let i=eventCursor;i<events.length;i++){const e=events[i];if(e.action==="agent-loop/start"&&e.payload&&e.payload.sessionId&&(!agentId||e.target===agentId)){activeSid=e.payload.sessionId;sessionId=activeSid;}if(e.action!=="llm/delta"||!e.payload||!e.payload.chunk)continue;if(activeSid&&e.target!==activeSid)continue;if(bubble.textContent==="正在回复…")bubble.textContent="";bubble.classList.remove("pending","md");bubble.textContent+=e.payload.chunk;log.scrollTop=log.scrollHeight;}eventCursor=events.length;}catch(e){}},80);}',
  'async function pullTraj(){if(!window.wh||!window.wh.call){renderTrajectory(traj,null);return;}try{const r=await window.wh.call("trajectory","latest",[]);if(!r.ok){if(r.error&&String(r.error).indexOf("不可用")>=0){traj.innerHTML=\'<div class="traj-empty">轨迹插件未装入。</div>\';return;}traj.innerHTML=\'<div class="traj-empty">\'+trajEsc(r.error||"读取失败")+"</div>";return;}const snap=r.result;const key=snap?(snap.id+":"+(snap.spans?snap.spans.length:0)):"0";if(key===lastKey)return;lastKey=key;renderTrajectory(traj,snap);const list=traj.querySelector(".traj-list");if(list)list.scrollTop=list.scrollHeight;}catch(e){traj.innerHTML=\'<div class="traj-empty">\'+trajEsc(e)+"</div>";}}',
  'function watchTraj(on){if(trajTimer){clearInterval(trajTimer);trajTimer=null;}if(on){pullTraj();trajTimer=setInterval(pullTraj,450);}}',
  'async function pullSessions(selectId){if(!window.wh||!window.wh.call||!sessList)return;try{const r=await window.wh.call("appChat","listSessions",[]);if(!r.ok){sessList.innerHTML=\'<div class="sess-meta">\'+trajEsc(r.error||"无法加载")+"</div>";return;}const rows=r.result||[];if(!rows.length){sessList.innerHTML=\'<div class="sess-meta">暂无历史会话</div>\';return;}sessList.innerHTML=rows.map(function(row){const active=(selectId&&row.id===selectId)?" active":"";const t=new Date(row.startedAt).toLocaleString("zh-CN",{hour12:false,month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"});const prev=row.preview?trajEsc(row.preview):"（无用户消息）";return \'<div class="sess\'+active+\'" data-id="\'+trajEsc(row.id)+\'"><div class="sess-id">\'+trajEsc(row.id.slice(0,8))+\'…</div><div class="sess-meta">\'+t+" · "+row.entryCount+" 条<br>"+prev+"</div></div>";}).join("");sessList.querySelectorAll(".sess").forEach(function(el){el.onclick=function(){loadSession(el.getAttribute("data-id"));};});}catch(e){sessList.innerHTML=\'<div class="sess-meta">\'+trajEsc(e)+"</div>";}}',
  'async function loadSession(id){if(!id||busy||!window.wh||!window.wh.call)return;try{const r=await window.wh.call("appChat","resumeSession",[id]);if(!r.ok){add("bot",humanError(r.error).title+"\\n"+humanError(r.error).detail,"err");return;}agentId=r.result.agentId;sessionId=r.result.sessionId;activeSid=sessionId;setAgentChip(agentId);if(ws)ws.disabled=true;renderMessages(r.result.messages||[]);await pullSessions(sessionId);}catch(e){add("bot",String(e),"err");}}',
  'async function send(){const q=box.value.trim();if(!q||busy||!promptReady||!window.wh||!window.wh.call)return;busy=true;go.disabled=true;cancel.style.display="inline-block";cancel.disabled=false;box.value="";add("user",q);const pending=add("bot","正在回复…","pending");lastKey="";activeSid=sessionId;await syncEventCursor();watchDeltas(true,pending);watchTraj(true);try{const r=await window.wh.call("appChat","send",[{agentId:agentId||undefined,sessionId:sessionId||undefined,prompt:q,useTools:document.getElementById("tools").checked,workspace:(agentId||sessionId)?undefined:(ws&&ws.value.trim()?ws.value.trim():undefined)}]);watchDeltas(false,pending);if(r.ok&&r.result){if(r.result.agentId){agentId=r.result.agentId;setAgentChip(agentId);}if(r.result.sessionId){sessionId=r.result.sessionId;activeSid=sessionId;}if(r.result.workspace&&ws)ws.value=r.result.workspace;if(ws)ws.disabled=true;fillBot(pending,r.result.text);await pullSessions(sessionId);}else{showError(pending,r.error||"失败");}}catch(e){watchDeltas(false,pending);showError(pending,e);}await pullTraj();watchTraj(false);busy=false;go.disabled=false;cancel.style.display="none";box.focus();}',
  'async function doCancel(){if(!busy||!agentId||!window.wh||!window.wh.call)return;cancel.disabled=true;try{await window.wh.call("appChat","cancel",[agentId]);}catch(e){}}',
  'go.onclick=send;cancel.onclick=doCancel;',
  'box.addEventListener("keydown",function(e){if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send();}});',
  'document.getElementById("neu").onclick=function(){if(busy)return;agentId=null;sessionId=null;activeSid=null;setAgentChip(null);if(ws){ws.disabled=false;ws.value="";}log.innerHTML=\'<div class="empty">New session started. 工作区在首次发送时写入这条会话。</div>\';pullSessions(null);box.focus();};',
  'document.getElementById("show-traj").onchange=function(){app.classList.toggle("no-traj",!this.checked);};',
  'async function pullSandbox(){const chip=document.getElementById("sb");if(!window.wh||!window.wh.call){chip.textContent="沙箱不可用";return;}try{const r=await window.wh.call("sandbox","info",[]);if(!r.ok){chip.textContent=(r.error&&String(r.error).indexOf("不可用")>=0)?"沙箱未装入":(r.error||"沙箱失败");chip.title="";return;}chip.textContent="沙箱 "+r.result.root;chip.title=r.result.root;}catch(e){chip.textContent=String(e);}}',
  'renderTrajectory(traj,null);pullTraj();pullSandbox();pullPromptContext();pullSessions(null);setAgentChip(null);syncEventCursor();box.focus();',
  '</script></body></html>',
].join('');
