import { TRAJECTORY_VIEW_CSS, TRAJECTORY_VIEW_JS } from './traj-view.js';

export const APP_UI_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  'html,body{height:100%;margin:0;overflow:hidden}',
  'body{display:flex;flex-direction:column;background:#12121a;color:#e6e6ef;',
  'font:13px/1.55 system-ui,"Segoe UI","Microsoft YaHei",sans-serif}',
  '.app{flex:1;min-height:0;display:flex;flex-direction:column}',
  '.bar{flex:none;display:flex;align-items:center;gap:10px;padding:8px 14px;border-bottom:1px solid #262634}',
  '.bar label{display:flex;gap:6px;align-items:center;color:#8b949e;font-size:12px}',
  '.ghost{margin-left:auto;background:transparent;border:1px solid #333;color:#a8a8bd;border-radius:8px;',
  'padding:4px 10px;font:12px system-ui;cursor:pointer}',
  '.main{flex:1;min-height:0;display:flex}',
  '#log{flex:1;min-width:0;overflow:auto;padding:16px 18px;scrollbar-width:none}',
  '#log::-webkit-scrollbar{display:none;width:0;height:0}',
  '.empty{color:#8b949e;text-align:center;margin-top:18vh}',
  '.row{display:flex;margin:0 0 10px}.row.user{justify-content:flex-end}',
  '.b{max-width:78%;padding:9px 12px;border-radius:14px;white-space:pre-wrap;word-break:break-word}',
  '.b.user{background:#1b4f72;color:#eaf6ff;border-bottom-right-radius:4px}',
  '.b.bot{background:#1c1c28;border-bottom-left-radius:4px}.b.err{color:#ffb4ae;background:#3a1f22}.b.pending{color:#8b949e}',
  '.rail{flex:none;width:300px;min-width:220px;max-width:42%;border-left:1px solid #262634;',
  'display:flex;flex-direction:column;min-height:0;background:#0f0f16}',
  '.rail-h{flex:none;padding:8px 12px;font:600 12px system-ui;color:#a8a8bd;border-bottom:1px solid #262634}',
  '#traj{flex:1;min-height:0}',
  '.app.no-traj .rail{display:none}',
  'footer{flex:none;padding:10px 14px 12px;border-top:1px solid #262634}',
  '.compose{display:flex;gap:8px}',
  'textarea{flex:1;min-height:44px;max-height:44px;resize:none;background:#1a1a24;color:#e6e6ef;',
  'border:1px solid #333;border-radius:10px;padding:9px 11px;font:13px inherit}',
  '#go{min-width:72px;height:44px;border:none;border-radius:10px;background:#238636;color:#fff;font:600 13px system-ui;cursor:pointer}',
  '#go:disabled{opacity:.4}',
  TRAJECTORY_VIEW_CSS,
  '</style></head><body><div class="app" id="app">',
  '<div class="bar"><label><input type="checkbox" id="tools" checked> 允许调用工具</label>',
  '<label><input type="checkbox" id="show-traj" checked> 执行轨迹</label>',
  '<button class="ghost" id="neu" type="button">新对话</button></div>',
  '<div class="main"><div id="log"><div class="empty">Enter 发送，Shift+Enter 换行。右侧是本轮怎么跑出来的。</div></div>',
  '<aside class="rail"><div class="rail-h">本轮轨迹</div><div id="traj" class="traj-root"></div></aside></div>',
  '<footer><div class="compose"><textarea id="box" placeholder="问点什么…"></textarea>',
  '<button id="go" type="button">发送</button></div></footer>',
  '</div><script>',
  TRAJECTORY_VIEW_JS,
  'let agentId=null,busy=false,trajTimer=null,lastKey="";',
  'const log=document.getElementById("log"),box=document.getElementById("box"),go=document.getElementById("go");',
  'const app=document.getElementById("app"),traj=document.getElementById("traj");',
  'function add(role,text,cls){',
  'const empty=log.querySelector(".empty"); if(empty) empty.remove();',
  'const row=document.createElement("div"); row.className="row "+(role==="user"?"user":"bot");',
  'const b=document.createElement("div"); b.className="b "+(role==="user"?"user":"bot")+(cls?" "+cls:"");',
  'b.textContent=text; row.appendChild(b); log.appendChild(row); log.scrollTop=log.scrollHeight; return b;',
  '}',
  'async function pullTraj(){',
  'if(!window.wh||!window.wh.call){renderTrajectory(traj,null);return;}',
  'try{',
  'const r=await window.wh.call("trajectory","latest",[]);',
  'if(!r.ok){',
  'if(r.error&&String(r.error).indexOf("不可用")>=0){',
  'traj.innerHTML=\'<div class="traj-empty">轨迹插件未装入。</div>\';return;}',
  'traj.innerHTML=\'<div class="traj-empty">\'+trajEsc(r.error||"读取失败")+"</div>";return;}',
  'const snap=r.result;',
  'const key=snap?(snap.id+":"+(snap.spans?snap.spans.length:0)):"0";',
  'if(key===lastKey)return;',
  'lastKey=key;',
  'renderTrajectory(traj,snap);',
  'const list=traj.querySelector(".traj-list");',
  'if(list)list.scrollTop=list.scrollHeight;',
  '}catch(e){traj.innerHTML=\'<div class="traj-empty">\'+trajEsc(e)+"</div>";}}',
  'function watchTraj(on){',
  'if(trajTimer){clearInterval(trajTimer);trajTimer=null;}',
  'if(on){pullTraj();trajTimer=setInterval(pullTraj,450);}',
  '}',
  'async function send(){',
  'const q=box.value.trim(); if(!q||busy||!window.wh||!window.wh.call) return;',
  'busy=true; go.disabled=true; box.value=""; add("user",q); const pending=add("bot","正在回复…","pending");',
  'lastKey=""; watchTraj(true);',
  'try{',
  'const r=await window.wh.call("appChat","send",[{agentId:agentId||undefined,prompt:q,useTools:document.getElementById("tools").checked}]);',
  'if(r.ok&&r.result&&r.result.agentId) agentId=r.result.agentId;',
  'pending.classList.remove("pending"); pending.textContent=r.ok?((r.result&&r.result.text)||"（空回复）"):(r.error||"失败");',
  'if(!r.ok) pending.classList.add("err");',
  '}catch(e){ pending.classList.remove("pending"); pending.classList.add("err"); pending.textContent=String(e); }',
  'await pullTraj(); watchTraj(false);',
  'busy=false; go.disabled=false; box.focus();',
  '}',
  'go.onclick=send;',
  'box.addEventListener("keydown",function(e){ if(e.key==="Enter"&&!e.shiftKey){ e.preventDefault(); send(); }});',
  'document.getElementById("neu").onclick=function(){ if(busy)return; agentId=null; log.innerHTML=\'<div class="empty">新对话已开始。</div>\'; box.focus(); };',
  'document.getElementById("show-traj").onchange=function(){',
  'app.classList.toggle("no-traj",!this.checked);',
  '};',
  'renderTrajectory(traj,null); pullTraj();',
  'box.focus();',
  '</script></body></html>',
].join('');
