/** 与 plugins/trajectory/src/view.ts 同步：轨迹时间线 CSS / 浏览器脚本。 */

export const TRAJECTORY_VIEW_CSS = [
  '.traj-root{display:flex;flex-direction:column;min-height:0;height:100%}',
  '.traj-empty{color:#8b949e;padding:18px 14px;line-height:1.6}',
  '.traj-meta{flex:none;padding:8px 14px;border-bottom:1px solid #262634;color:#8b949e;font-size:11px;',
  'display:flex;gap:8px;flex-wrap:wrap;align-items:center}',
  '.traj-meta b{color:#e6e6ef;font-weight:600}',
  '.traj-list{flex:1;min-height:0;overflow:auto;padding:10px 12px 16px 18px;scrollbar-width:none}',
  '.traj-list::-webkit-scrollbar{display:none;width:0;height:0}',
  '.traj-step{position:relative;padding:0 0 12px 12px;cursor:pointer}',
  '.traj-step:last-child{padding-bottom:0}',
  '.traj-step::before{content:"";position:absolute;left:-2px;top:7px;width:8px;height:8px;',
  'border-radius:50%;background:var(--dot,#8b949e);box-shadow:0 0 0 3px rgba(255,255,255,.04)}',
  '.traj-step::after{content:"";position:absolute;left:1px;top:18px;bottom:0;width:2px;background:#262634}',
  '.traj-step:last-child::after{display:none}',
  '.traj-step[data-kind="run-start"],.traj-step[data-kind="run-end"]{--dot:#8b949e}',
  '.traj-step[data-kind="prompt"]{--dot:#79c0ff}',
  '.traj-step[data-kind="http"]{--dot:#d2a8ff}',
  '.traj-step[data-kind="tool"]{--dot:#ffa657}',
  '.traj-step[data-kind="complete"]{--dot:#7ee787}',
  '.traj-hd{display:flex;gap:8px;align-items:baseline}',
  '.traj-k{font:600 12px system-ui;color:var(--dot,#e6e6ef)}',
  '.traj-t{margin-left:auto;color:#6e7681;font:11px ui-monospace,Consolas,monospace}',
  '.traj-line{color:#c9d1d9;font-size:12px;margin-top:2px;word-break:break-word}',
  '.traj-det{display:none;margin:8px 0 0;padding:8px 10px;background:#16161e;border:1px solid #262634;',
  'border-radius:8px;color:#a8a8bd;font:11px/1.5 ui-monospace,Consolas,monospace;white-space:pre-wrap;',
  'word-break:break-word;max-height:220px;overflow:auto}',
  '.traj-step.open .traj-det{display:block}',
].join('');

export const TRAJECTORY_VIEW_JS = [
  'function trajEsc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;");}',
  'function trajClip(s,n){s=String(s||"").replace(/\\s+/g," ").trim();return s.length<=n?s:s.slice(0,n)+"…";}',
  'function trajClock(ts){try{return new Date(ts).toLocaleTimeString("zh-CN",{hour12:false});}catch(e){return "";}}',
  'function trajLabel(s){',
  'var d=s.data||{};',
  'if(s.kind==="run-start")return "开始";',
  'if(s.kind==="run-end")return d.error?"失败":"结束";',
  'if(s.kind==="prompt"){',
  'if(d.phase==="observe")return "观察 #"+(d.cycle||"?");',
  'if(d.phase==="apply")return "系统提示";',
  'return "组装上下文";}',
  'if(s.kind==="http")return "请求模型";',
  'if(s.kind==="tool")return "调用工具";',
  'if(s.kind==="complete")return "模型输出";',
  'return s.kind;}',
  'function trajLine(s){',
  'var d=s.data||{};',
  'if(s.kind==="run-start"){',
  'return "OTA 最多 "+(d.maxSteps??"?")+" 轮"+(d.useTools===false?" · 不用工具":" · 可用工具");}',
  'if(s.kind==="run-end"){',
  'if(d.error)return trajClip(d.error,120);',
  'return "完成 "+(d.steps??"?")+" 轮 OTA"+(d.provider?" · "+d.provider:"");}',
  'if(s.kind==="prompt"&&d.phase==="apply")return trajClip(d.content||"（空）",100);',
  'if(s.kind==="prompt"){',
  'var n=Array.isArray(d.messages)?d.messages.length:(Array.isArray(d.wire)?d.wire.length:0);',
  'var tools=Array.isArray(d.tools)?d.tools.map(function(t){return t.name||t;}).filter(Boolean):[];',
  'return n+" 条消息"+(tools.length?" · 工具 "+tools.join("、"):" · 无工具");}',
  'if(s.kind==="http"){',
  'var st=d.status==null?"—":d.status;',
  'return st+" "+(d.model||d.provider||"")+(d.ok===false?" · 失败":"")+(d.error?" · "+trajClip(d.error,60):"");}',
  'if(s.kind==="tool"){',
  'return (d.name||"tool")+" · "+(d.ok===false?"失败":"成功")+(d.content?" → "+trajClip(d.content,80):"");}',
  'if(s.kind==="complete"){',
  'var tc=Array.isArray(d.toolCalls)?d.toolCalls:[];',
  'if(tc.length)return "要调 "+tc.map(function(c){return c.name;}).join("、");',
  'return trajClip(d.text||"（空）",100);}',
  'return "";}',
  'function trajDetail(s){',
  'var d=s.data||{},copy={};',
  'Object.keys(d).forEach(function(k){',
  'var v=d[k];',
  'if(k==="wire")return;',
  'if(k==="messages"&&Array.isArray(v)){',
  'copy.messages=v.map(function(m){return {role:m.role,content:trajClip(m.content||"",180)};});',
  'return;}',
  'if(k==="request"&&v&&typeof v==="object"){',
  'copy.request={messages:Array.isArray(v.messages)?v.messages.length+" 条":undefined,tools:v.tools};',
  'return;}',
  'if(k==="response"&&v&&typeof v==="object"){copy.response={text:trajClip(v.text||"",200),toolCalls:v.toolCalls};return;}',
  'copy[k]=v;',
  '});',
  'try{return JSON.stringify(copy,null,2);}catch(e){return String(d);}}',
  'function renderTrajectory(el,snap){',
  'if(!el)return;',
  'if(!snap||!snap.spans||!snap.spans.length){',
  'el.innerHTML=\'<div class="traj-empty">暂无记录。发一条消息后，这里会记下拼提示词、请求和工具进出。</div>\';',
  'return;}',
  'var loopN;',
  'snap.spans.forEach(function(s){ if(s.kind==="run-end"&&s.data&&s.data.steps!=null) loopN=s.data.steps; });',
  'var meta="<div class=traj-meta><b>"+snap.spans.length+" 条记录</b>";',
  'if(loopN!=null)meta+="<span>循环 "+loopN+" 次</span>";',
  'meta+=trajClock(snap.startedAt)?"<span>"+trajEsc(trajClock(snap.startedAt))+"</span>":"";',
  'if(snap.agentId)meta+="<span>agent "+trajEsc(String(snap.agentId).slice(0,8))+"</span>";',
  'meta+="</div>";',
  'var body=snap.spans.map(function(s){',
  'return \'<div class="traj-step" data-kind="\'+trajEsc(s.kind)+\'">\'+',
  '\'<div class="traj-hd"><span class="traj-k">\'+trajEsc(trajLabel(s))+\'</span>\'+',
  '\'<span class="traj-t">\'+trajEsc(trajClock(s.ts))+\'</span></div>\'+',
  '\'<div class="traj-line">\'+trajEsc(trajLine(s))+\'</div>\'+',
  '\'<pre class="traj-det">\'+trajEsc(trajDetail(s))+\'</pre></div>\';',
  '}).join("");',
  'el.innerHTML=meta+\'<div class="traj-list">\'+body+"</div>";',
  'el.onclick=function(ev){',
  'var step=ev.target.closest(".traj-step");',
  'if(step)step.classList.toggle("open");',
  '};}',
].join('\n');
