export const DEV_TOOLS_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  'body{margin:0;font-family:system-ui,"Microsoft YaHei",sans-serif;background:#16161e;color:#e6e6ef}',
  '.card{padding:18px 20px} h1{font-size:16px;margin:0 0 6px}',
  '.desc{margin:0 0 12px;font-size:13px;color:#a8a8bd;line-height:1.6}',
  '.root{font:12px ui-monospace,Consolas,monospace;color:#79c0ff;word-break:break-all;margin:0 0 12px}',
  'ul{margin:0;padding:0;list-style:none;font:12px ui-monospace,Consolas,monospace}',
  'li{padding:4px 0;border-bottom:1px solid #262634;color:#d7d7e4}',
  'button{margin-top:10px;background:rgba(121,192,255,.12);border:1px solid rgba(121,192,255,.35);color:#79c0ff;',
  'border-radius:8px;padding:5px 10px;cursor:pointer}',
  '</style></head><body><div class="card">',
  '<h1>本地编程工具套件</h1>',
  '<p class="desc">向 tools 登记 bash / read_file / write_file / str_replace / grep / glob。文件不出 root。完整名单看「工具注册表」弹窗。</p>',
  '<p class="root" id="root">…</p>',
  '<ul id="list"></ul>',
  '<button type="button" id="go">刷新</button>',
  '</div><script>',
  'async function load(){',
  'const root=document.getElementById("root"),list=document.getElementById("list");',
  'if(!window.wh||!window.wh.call){root.textContent="无 RPC";return;}',
  'const i=await window.wh.call("devTools","info",[]);',
  'if(!i.ok){root.textContent=i.error||"失败";return;}',
  'root.textContent=i.result.root;',
  'list.innerHTML="";',
  '(i.result.tools||[]).forEach(function(name){',
  'const li=document.createElement("li");li.textContent=name;list.appendChild(li);',
  '});',
  '}',
  'document.getElementById("go").onclick=load; load();',
  '</script></body></html>',
].join('');
