export const TOOLS_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  'html,body{height:100%;margin:0;overflow:hidden}',
  'body{display:flex;flex-direction:column;background:#0d1117;color:#e6e6ef;',
  'font:13px/1.5 system-ui,"Segoe UI","Microsoft YaHei",sans-serif}',
  '.bar{flex:none;padding:8px 14px;border-bottom:1px solid #262634;display:flex;gap:8px;align-items:center}',
  'h1{font:600 14px system-ui;margin:0}',
  '.meta{color:#8b949e;font-size:11px}',
  '.ghost{margin-left:auto;background:transparent;border:1px solid #333;color:#a8a8bd;border-radius:8px;',
  'padding:4px 10px;font:12px system-ui;cursor:pointer}',
  '.ghost:hover{border-color:#4a6aa0;color:#79c0ff}',
  '.search{flex:none;padding:8px 14px;border-bottom:1px solid #262634}',
  '.search input{width:100%;box-sizing:border-box;background:#16161e;border:1px solid #2c2c3e;border-radius:8px;',
  'color:#e6e6ef;padding:7px 10px;font:13px system-ui;outline:none}',
  '.search input:focus{border-color:#4a6aa0}',
  '.search input::placeholder{color:#6e7681}',
  '.hint{flex:none;padding:6px 16px 0;font-size:11px;color:#6e7681}',
  '.list{flex:1;min-height:0;overflow:auto;padding:6px 10px 20px;scrollbar-width:thin;scrollbar-color:#2c2c3a transparent}',
  '.grp{margin:10px 6px 4px;font:600 11px system-ui;color:#8b949e;letter-spacing:.04em}',
  '.item{padding:9px 10px 10px;border-bottom:1px solid #1c1c28;border-radius:8px;cursor:pointer}',
  '.item:hover{background:#16161e}',
  '.item.open{background:#16161e}',
  '.hd{display:flex;gap:8px;align-items:center;flex-wrap:wrap}',
  '.n{font:600 13px ui-monospace,Consolas,monospace;color:#ffa657}',
  '.n:hover{text-decoration:underline;text-underline-offset:3px}',
  '.chip{font:10px ui-monospace,Consolas,monospace;color:#79c0ff;border:1px solid rgba(121,192,255,.28);',
  'border-radius:999px;padding:0 7px;line-height:18px}',
  '.line{color:#c9d1d9;font-size:12px;margin-top:4px;line-height:1.45}',
  '.body{display:none;margin-top:8px;padding:8px 10px;background:#0d1117;border:1px solid #262634;border-radius:8px;',
  'white-space:pre-wrap;word-break:break-word;font:12px/1.55 ui-monospace,Consolas,monospace;color:#a8a8bd}',
  '.item.open .body{display:block}',
  '.empty,.err{padding:28px 16px;color:#8b949e;line-height:1.6}',
  '.err{color:#ffb4ae}',
  '.toast{position:fixed;left:50%;bottom:16px;transform:translateX(-50%);background:#21262d;border:1px solid #30363d;',
  'color:#7ee787;border-radius:8px;padding:6px 12px;font:12px system-ui;opacity:0;pointer-events:none;transition:opacity .15s}',
  '.toast.on{opacity:1}',
  '</style></head><body>',
  '<div class="bar"><h1>工具注册表</h1><span class="meta" id="meta">—</span>',
  '<button class="ghost" type="button" id="go">刷新</button></div>',
  '<div class="search"><input id="q" type="search" placeholder="搜索名称或描述" autocomplete="off" /></div>',
  '<div class="hint">只读名单 · 点名称复制 · 点条目展开全文</div>',
  '<div class="list" id="list"></div>',
  '<div class="toast" id="toast">已复制</div>',
  '<script>',
  'function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;");}',
  'function groupOf(n){',
  'if(n.indexOf("web_")==0)return {id:"web",label:"网页"};',
  'if(n.indexOf("sandbox_")==0)return {id:"sandbox",label:"沙箱"};',
  'if(n.indexOf("persona_")==0)return {id:"persona",label:"人格"};',
  'if(n==="echo"||n==="now"||n==="upper")return {id:"builtin",label:"内置"};',
  'if(/^(bash|read_file|write_file|str_replace|grep|glob)$/.test(n))return {id:"dev",label:"本地编程"};',
  'return {id:"other",label:"其它"};}',
  'const ORDER=["dev","web","sandbox","persona","builtin","other"];',
  'function summary(d){var t=String(d||"").trim();if(!t)return "（无描述）";var i=t.indexOf("。");return i>8&&i<90?t.slice(0,i+1):t;}',
  'function chips(d){var s={},out=[];String(d||"").replace(/args\\.(\\w+)/g,function(_,k){if(!s[k]){s[k]=1;out.push(k);}return _;});return out;}',
  'let rows=[],open=Object.create(null),toastTimer;',
  'function toast(msg){var el=document.getElementById("toast");el.textContent=msg;el.className="toast on";clearTimeout(toastTimer);toastTimer=setTimeout(function(){el.className="toast";},900);}',
  'function copyName(name){',
  'function ok(){toast("已复制 "+name);}',
  'if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(name).then(ok).catch(function(){toast("复制失败");});}',
  'else toast("无法复制");}',
  'function render(){',
  'const list=document.getElementById("list"),meta=document.getElementById("meta");',
  'const q=document.getElementById("q").value.trim().toLowerCase();',
  'const hit=rows.filter(function(t){if(!q)return true;return (t.name+" "+(t.description||"")).toLowerCase().indexOf(q)>=0;});',
  'meta.textContent=q?hit.length+" / "+rows.length+" 个":rows.length+" 个已登记";',
  'if(!rows.length){list.innerHTML=\'<div class="empty">还没有工具。其它插件 ctx.tools.register 之后会出现在这里。</div>\';return;}',
  'if(!hit.length){list.innerHTML=\'<div class="empty">没有匹配「\'+esc(q)+\'」</div>\';return;}',
  'const buckets={};',
  'hit.forEach(function(t){var g=groupOf(t.name);(buckets[g.id]||(buckets[g.id]={label:g.label,items:[]})).items.push(t);});',
  'var html="";',
  'ORDER.forEach(function(id){var b=buckets[id];if(!b)return;',
  'html+=\'<div class="grp">\'+esc(b.label)+\' · \'+b.items.length+"</div>";',
  'b.items.forEach(function(t){',
  'var ch=chips(t.description).map(function(k){return \'<span class="chip">\'+esc(k)+"</span>";}).join("");',
  'html+=\'<div class="item\'+(open[t.name]?" open":"")+\'" data-name="\'+esc(t.name)+\'"><div class="hd">\'+',
  '\'<span class="n" data-copy="1">\'+esc(t.name)+"</span>"+ch+"</div>"+',
  '\'<div class="line">\'+esc(summary(t.description))+"</div>"+',
  '\'<pre class="body">\'+esc(t.description||"（无描述）")+"</pre></div>";',
  '});});',
  'list.innerHTML=html;}',
  'async function load(){',
  'const list=document.getElementById("list"),meta=document.getElementById("meta");',
  'if(!window.wh||!window.wh.call){meta.textContent="无 RPC";list.innerHTML=\'<div class="err">窗口桥未就绪</div>\';return;}',
  'const r=await window.wh.call("tools","list",[]);',
  'if(!r.ok){meta.textContent="失败";list.innerHTML=\'<div class="err">\'+esc(r.error||"list 失败")+"</div>";return;}',
  'rows=Array.isArray(r.result)?r.result:[]; render();}',
  'document.getElementById("go").onclick=load;',
  'document.getElementById("q").addEventListener("input",render);',
  'document.getElementById("q").addEventListener("keydown",function(e){if(e.key==="Escape"){this.value="";render();}});',
  'document.getElementById("list").addEventListener("click",function(e){',
  'var copy=e.target.closest("[data-copy]");',
  'var item=e.target.closest(".item"); if(!item)return;',
  'var name=item.getAttribute("data-name");',
  'if(copy){e.stopPropagation();copyName(name);return;}',
  'open[name]=!open[name]; item.classList.toggle("open",open[name]);',
  '});',
  'load();',
  '</script></body></html>',
].join('');
