export const KREA_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  'body{margin:0;font-family:system-ui,"Microsoft YaHei",sans-serif;background:#16161e;color:#e6e6ef}',
  '.card{padding:18px 20px;overflow:auto;height:100%;box-sizing:border-box}',
  'h1{font-size:16px;margin:0 0 6px}',
  '.desc{margin:0 0 12px;font-size:13px;color:#a8a8bd;line-height:1.6}',
  '.root{font:12px ui-monospace,Consolas,monospace;color:#79c0ff;word-break:break-all;margin:0 0 12px}',
  'ul{margin:0;padding:0;list-style:none;font:12px ui-monospace,Consolas,monospace}',
  'li{padding:6px 0;border-bottom:1px solid #262634;color:#d7d7e4}',
  'a{color:#79c0ff}',
  'button{margin-top:10px;background:rgba(121,192,255,.12);border:1px solid rgba(121,192,255,.35);color:#79c0ff;',
  'border-radius:8px;padding:5px 10px;cursor:pointer}',
  '.muted{color:#a8a8bd}',
  '</style></head><body><div class="card">',
  '<h1>Krea 绘图</h1>',
  '<p class="desc">Agent 用 krea_generate 出图。Key 走 WH_KREA_API_KEY 或插件 config.apiKey，弹窗不展示密钥。</p>',
  '<p class="root" id="root">…</p>',
  '<ul id="list"></ul>',
  '<button type="button" id="go">刷新</button>',
  '</div><script>',
  'async function load(){',
  'const root=document.getElementById("root"),list=document.getElementById("list");',
  'if(!window.wh||!window.wh.call){root.textContent="无 RPC";return;}',
  'const i=await window.wh.call("krea","info",[]);',
  'if(!i.ok){root.textContent=i.error||"失败";return;}',
  'const r=i.result;',
  'root.textContent=(r.configured?"已配置 Key":"未配置 Key")+" · 默认 "+r.defaultModel;',
  'list.innerHTML="";',
  '(r.recent||[]).forEach(function(job){',
  'const li=document.createElement("li");',
  'const url=(job.urls&&job.urls[0])||"";',
  'li.appendChild(document.createTextNode((job.status||"")+" · "+(job.model||"")));',
  'if(url){const a=document.createElement("a");a.href=url;a.target="_blank";a.rel="noreferrer";a.textContent=" 打开";li.appendChild(a);}',
  'list.appendChild(li);',
  '});',
  'if(!(r.recent||[]).length){',
  'const li=document.createElement("li");li.className="muted";li.textContent="还没有任务。让 Agent 调用 krea_generate。";list.appendChild(li);',
  '}',
  '}',
  'document.getElementById("go").onclick=load; load();',
  '</script></body></html>',
].join('');
