/** Kando 开花式 marking：子菜单绽开，不硬切替换 */
export const PIE_MENU_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  ':root{--bg0:#07090f;--bg1:#121826;--ink:#eef2ff;--muted:#8b95a8;--line:rgba(255,255,255,.1);',
  '--accent:#7aa2ff;--accent2:#b388ff;--glow:rgba(122,162,255,.35)}',
  'html,body{height:100%;margin:0;overflow:hidden;background:radial-gradient(1200px 800px at 50% 45%,#141b2b 0%,var(--bg0) 62%)}',
  'body{font:13px/1.35 "Segoe UI","PingFang SC","Microsoft YaHei",system-ui,sans-serif;color:var(--ink);',
  'cursor:crosshair;user-select:none;-webkit-font-smoothing:antialiased}',
  '#hud{position:fixed;inset:0}',
  '#stage{position:absolute;left:var(--cx,50%);top:var(--cy,50%);width:0;height:0}',
  'svg.ring{position:absolute;left:-210px;top:-210px;width:420px;height:420px;overflow:visible;',
  'filter:drop-shadow(0 18px 40px rgba(0,0,0,.45))}',
  '.wedge{fill:rgba(255,255,255,.03);stroke:var(--line);stroke-width:1}',
  '.wedge.bloom{opacity:0;transform-origin:210px 210px;transform:scale(.55);',
  'animation:bloomWedge .38s cubic-bezier(.2,.9,.2,1) forwards}',
  '.wedge.hot{fill:rgba(122,162,255,.2);stroke:rgba(170,200,255,.45)}',
  '.node{transform-box:fill-box;transform-origin:center}',
  '.node.bloom{opacity:0;transform:scale(.2);animation:bloomNode .42s cubic-bezier(.18,1.1,.3,1) forwards}',
  '.node circle{fill:rgba(22,28,42,.96);stroke:rgba(255,255,255,.14);stroke-width:1.6}',
  '.node.hot circle{fill:rgba(42,58,110,.98);stroke:var(--accent);stroke-width:2.2;',
  'filter:drop-shadow(0 0 12px var(--glow))}',
  '.node.sub circle{stroke:rgba(179,136,255,.65)}',
  '.center.bloom{opacity:0;animation:bloomNode .3s .02s cubic-bezier(.2,.9,.2,1) forwards}',
  '.center circle{fill:rgba(14,18,28,.96);stroke:var(--accent);stroke-width:2;',
  'filter:drop-shadow(0 0 16px rgba(122,162,255,.25))}',
  '.lab{pointer-events:none;text-anchor:middle;dominant-baseline:central;fill:var(--ink);',
  'font:650 12px "Segoe UI","PingFang SC",sans-serif}',
  '.lab-ico{font:700 14px ui-monospace,Consolas,monospace;fill:var(--accent)}',
  '.lab-name{font:11px "Segoe UI","PingFang SC",sans-serif;fill:var(--muted)}',
  '.lab-c{font:650 13px "Segoe UI","PingFang SC",sans-serif;fill:var(--ink)}',
  '@keyframes bloomWedge{to{opacity:1;transform:scale(1)}}',
  '@keyframes bloomNode{0%{opacity:0;transform:scale(.15)}70%{opacity:1;transform:scale(1.06)}100%{opacity:1;transform:scale(1)}}',
  '.ring.leaving .wedge,.ring.leaving .node,.ring.leaving .center{animation:fadeOut .16s ease forwards}',
  '@keyframes fadeOut{to{opacity:0;transform:scale(1.12)}}',
  '.crumb{position:absolute;left:50%;top:18px;transform:translateX(-50%);display:flex;gap:8px;align-items:center;',
  'pointer-events:none;padding:6px 14px;border-radius:999px;background:rgba(8,10,16,.45);',
  'border:1px solid var(--line);backdrop-filter:blur(10px);color:var(--muted);font-size:12px}',
  '.crumb b{color:var(--ink);font-weight:650}',
  '.crumb i{font-style:normal;opacity:.4}',
  '.hint{position:absolute;left:50%;bottom:22px;transform:translateX(-50%);pointer-events:none;',
  'color:var(--muted);font-size:11px;letter-spacing:.02em;opacity:.85}',
  '@media (prefers-reduced-motion:reduce){.wedge,.node,.center{animation:none!important;opacity:1;transform:none}}',
  '</style></head><body>',
  '<div id="hud">',
  '<div class="crumb" id="crumb"><b>Wizard</b></div>',
  '<div id="stage"><svg class="ring" id="ring" viewBox="0 0 420 420"></svg></div>',
  '<div class="hint">按住拖向扇区 · 子菜单会开花 · 松手执行</div>',
  '</div>',
  '<script>',
  'var root=null,stack=[],hoverId=null,marking=false,openedAt=0,lastEnterAt=0,busy=false;',
  'var R=128,r=44,CX=210,CY=210,ENTER_R=82;',
  'var FALLBACK={id:"root",label:"Wizard",kind:"submenu",children:[',
  '{id:"agent",label:"Agent",icon:"Ag",kind:"openPlugin",pluginId:"app-ui"},',
  '{id:"workspace",label:"工作台",icon:"Ws",kind:"openPlugin",pluginId:"workspace"},',
  '{id:"tools",label:"工具",icon:"Tl",kind:"submenu",children:[',
  '{id:"pomodoro",label:"番茄钟",icon:"Po",kind:"openPlugin",pluginId:"pomodoro"},',
  '{id:"elements",label:"元素表",icon:"El",kind:"openPlugin",pluginId:"element-table"},',
  '{id:"files",label:"文件",icon:"Fm",kind:"openPlugin",pluginId:"file-manager"}]},',
  '{id:"workflow",label:"工作流",icon:"Wf",kind:"openPlugin",pluginId:"app-workflow"},',
  '{id:"close",label:"关闭",icon:"x",kind:"action",action:"close"}]};',
  'function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;");}',
  'async function call(method,args){',
  'if(!window.wh||!window.wh.call)return {ok:false,error:"no-bridge"};',
  'return window.wh.call("pieMenu",method,args||[]);}',
  'function closeWin(){if(window.wh&&window.wh.windowControl)window.wh.windowControl("close");}',
  'function setOrigin(x,y){',
  'x=Math.max(210,Math.min(window.innerWidth-210,x));',
  'y=Math.max(210,Math.min(window.innerHeight-210,y));',
  'document.documentElement.style.setProperty("--cx",x+"px");',
  'document.documentElement.style.setProperty("--cy",y+"px");',
  '}',
  'window.__piePlace=function(){',
  'var o=window.__PIE_ORIGIN__;',
  'if(o&&typeof o.x==="number")setOrigin(o.x,o.y);',
  'else setOrigin(window.innerWidth/2,window.innerHeight/2);',
  '};',
  'function current(){return stack.length?stack[stack.length-1]:root;}',
  'function childrenOf(node){return (node&&node.children)||[];}',
  'function anglesFor(items){',
  'var n=items.length||1,step=360/n;',
  'return items.map(function(it,i){',
  'var mid=it.angle!=null?(((Number(it.angle)%360)+360)%360):((-90+i*step+step/2)%360+360)%360;',
  'return {start:mid-step/2,end:mid+step/2,mid:mid};});}',
  'function polar(deg,rad){var a=(deg-90)*Math.PI/180;return [CX+rad*Math.cos(a),CY+rad*Math.sin(a)];}',
  'function wedgePath(a0,a1){',
  'var span=((a1-a0)%360+360)%360;if(span===0)span=360;var large=span>180?1:0;',
  'var p0=polar(a0,R+40),p1=polar(a1,R+40),q0=polar(a0,r),q1=polar(a1,r);',
  'return "M "+q0[0]+" "+q0[1]+" L "+p0[0]+" "+p0[1]+" A "+(R+40)+" "+(R+40)+" 0 "+large+" 1 "+p1[0]+" "+p1[1]+',
  '" L "+q1[0]+" "+q1[1]+" A "+r+" "+r+" 0 "+large+" 0 "+q0[0]+" "+q0[1]+" Z";}',
  'function origin(){',
  'return {',
  'x:parseFloat(getComputedStyle(document.documentElement).getPropertyValue("--cx"))||window.innerWidth/2,',
  'y:parseFloat(getComputedStyle(document.documentElement).getPropertyValue("--cy"))||window.innerHeight/2};}',
  'function angleAt(x,y){',
  'var o=origin(),dx=x-o.x,dy=y-o.y,dist=Math.sqrt(dx*dx+dy*dy);',
  'var deg=(Math.atan2(dy,dx)*180/Math.PI)+90;if(deg<0)deg+=360;return {deg:deg,dist:dist};}',
  'function norm(d){return ((d%360)+360)%360;}',
  'function inWedge(deg,a0,a1){var d=norm(deg),s=norm(a0),e=norm(a1);return s<=e?(d>=s&&d<e):(d>=s||d<e);}',
  'function pickAt(x,y){',
  'var items=childrenOf(current()),hit=angleAt(x,y);',
  'if(hit.dist<r*0.78)return {kind:"center",dist:hit.dist};',
  'if(!items.length||hit.dist>R+60)return {kind:"outside",dist:hit.dist};',
  'var angs=anglesFor(items);',
  'for(var i=0;i<items.length;i++){',
  'if(inWedge(hit.deg,angs[i].start,angs[i].end))return {kind:"item",item:items[i],dist:hit.dist};}',
  'return {kind:"outside",dist:hit.dist};}',
  'function crumbHtml(){',
  'var parts=[{t:root?root.label:"Menu",on:!stack.length}];',
  'for(var i=0;i<stack.length;i++)parts.push({t:stack[i].label,on:i===stack.length-1});',
  'return parts.map(function(p,i){',
  'return (i?"<i>/</i>":"")+(p.on?"<b>"+esc(p.t)+"</b>":esc(p.t));',
  '}).join("");}',
  'function render(bloom){',
  'var node=current(),items=childrenOf(node),angs=anglesFor(items),svg=document.getElementById("ring");',
  'svg.classList.remove("leaving");',
  'var html="",b=bloom?" bloom":"";',
  'items.forEach(function(it,i){',
  'var hot=hoverId===it.id,wcls="wedge"+(hot?" hot":"")+b;',
  'var delay=bloom?(0.04+i*0.035):0;',
  'html+="<path class=\\""+wcls+"\\" style=\\"animation-delay:"+delay+"s\\" d=\\""+wedgePath(angs[i].start,angs[i].end)+"\\"></path>";',
  '});',
  'html+="<g class=\\"center"+b+"\\"><circle cx=\\""+CX+"\\" cy=\\""+CY+"\\" r=\\""+(r-2)+"\\"></circle>";',
  'html+="<text class=\\"lab lab-c\\" x=\\""+CX+"\\" y=\\""+CY+"\\">"+esc(stack.length?"返回":(node&&node.label)||"Menu")+"</text></g>";',
  'items.forEach(function(it,i){',
  'var p=polar(angs[i].mid,R),hot=hoverId===it.id;',
  'var ncls="node"+(it.kind==="submenu"?" sub":"")+(hot?" hot":"")+b;',
  'var delay=bloom?(0.06+i*0.04):0;',
  'html+="<g class=\\""+ncls+"\\" style=\\"animation-delay:"+delay+"s\\" transform=\\"translate("+p[0]+","+p[1]+")\\">";',
  'html+="<circle r=\\"30\\"></circle>";',
  'html+="<text class=\\"lab lab-ico\\" y=\\"-4\\">"+esc(it.icon||it.label.slice(0,2))+"</text>";',
  'html+="<text class=\\"lab lab-name\\" y=\\"14\\">"+esc(it.label)+"</text></g>";',
  '});',
  'svg.innerHTML=html;',
  'document.getElementById("crumb").innerHTML=crumbHtml();',
  '}',
  'function bloomTo(nextFn){',
  'if(busy)return;',
  'busy=true;',
  'var svg=document.getElementById("ring");',
  'svg.classList.add("leaving");',
  'setTimeout(function(){',
  'nextFn();hoverId=null;render(true);',
  'setTimeout(function(){busy=false;},120);',
  '},150);',
  '}',
  'function enterSub(item){',
  'if(!item||item.kind!=="submenu"||!item.children||!item.children.length)return false;',
  'if(Date.now()-lastEnterAt<110)return false;',
  'lastEnterAt=Date.now();',
  'bloomTo(function(){stack.push(item);});',
  'return true;',
  '}',
  'async function fireLeaf(item){',
  'if(!item||item.kind==="submenu")return;',
  'var r=await call("activate",[item.id]);',
  'var ef=r.ok?r.result:null;',
  'var pid=(ef&&ef.pluginId)||item.pluginId;',
  'if(item.kind==="openPlugin"||(ef&&ef.effect==="openPlugin")){',
  'if(pid&&window.wh&&window.wh.openPlugin)await window.wh.openPlugin(pid);',
  'closeWin();return;}',
  'closeWin();',
  '}',
  'function goBack(){',
  'if(stack.length)bloomTo(function(){stack.pop();});',
  'else closeWin();',
  '}',
  'function onMove(e){',
  'if(busy)return;',
  'var p=pickAt(e.clientX,e.clientY);',
  'var nid=p.kind==="item"?p.item.id:null;',
  'if(nid!==hoverId){hoverId=nid;render(false);}',
  'if(!marking)return;',
  'if(p.kind==="item"&&p.item.kind==="submenu"&&p.dist>=ENTER_R)enterSub(p.item);',
  '}',
  'function onDown(e){if(e.button!==0)return;marking=true;e.preventDefault();onMove(e);}',
  'async function onUp(e){',
  'if(e.button!==0||!marking)return;marking=false;',
  'if(busy)return;',
  'var grace=Date.now()-openedAt<200;',
  'var p=pickAt(e.clientX,e.clientY);',
  'if(p.kind==="center"){goBack();return;}',
  'if(p.kind==="item"){',
  'if(p.item.kind==="submenu"){enterSub(p.item);return;}',
  'await fireLeaf(p.item);return;}',
  'if(!grace)closeWin();',
  '}',
  'async function boot(){',
  'openedAt=Date.now();window.__piePlace();',
  'var r=await call("snapshot");',
  'root=(r.ok&&r.result&&r.result.root)?r.result.root:FALLBACK;',
  'stack=[];hoverId=null;render(true);',
  '}',
  'document.addEventListener("pointermove",onMove);',
  'document.addEventListener("pointerdown",onDown);',
  'document.addEventListener("pointerup",onUp);',
  'document.addEventListener("keydown",function(e){if(e.key==="Escape")goBack();});',
  'window.addEventListener("resize",function(){window.__piePlace();render(false);});',
  'boot();',
  '</script></body></html>',
].join('');
