export const PRIMITIVE_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  'html,body{height:100%;margin:0;overflow:hidden}',
  'body{display:flex;flex-direction:column;background:#101018;color:#e6e6ef;',
  'font:13px/1.45 system-ui,"Segoe UI","Microsoft YaHei",sans-serif}',
  '.bar{flex:none;padding:10px 14px 8px;border-bottom:1px solid #262634;background:#151522;',
  'display:flex;align-items:flex-start;justify-content:space-between;gap:12px}',
  'h1{font:650 14px system-ui;margin:0 0 2px}',
  '.desc{margin:0;font-size:11px;color:#8b949e;max-width:520px}',
  '.tabs{display:flex;gap:6px;flex:none}',
  '.tabs button{appearance:none;border:1px solid #33334a;background:#21262d;color:#a8a8bd;',
  'border-radius:8px;padding:5px 10px;font-size:12px;cursor:pointer}',
  '.tabs button.on{color:#7ee787;border-color:rgba(126,231,135,.45);background:rgba(126,231,135,.1)}',
  '.sub{flex:none;display:flex;align-items:center;gap:8px;padding:8px 14px;border-bottom:1px solid #262634}',
  '.chips{display:flex;flex-wrap:wrap;gap:6px;flex:1}',
  '.chip{border:1px solid #30363d;background:#21262d;color:#a8a8bd;border-radius:999px;',
  'padding:2px 9px;font-size:11px;cursor:pointer}',
  '.chip.on{color:#7ee787;border-color:rgba(126,231,135,.4);background:rgba(126,231,135,.08)}',
  '.chip.ok{color:#7ee787;border-color:rgba(126,231,135,.45);background:rgba(126,231,135,.08)}',
  '.chip.ok.on{background:rgba(126,231,135,.18)}',
  'input[type=search],input[type=text]{background:#161622;border:1px solid #2c2c3e;color:#e6e6ef;',
  'border-radius:8px;padding:5px 8px;font:12px system-ui;min-width:140px}',
  '.layout{flex:1;min-height:0;display:grid;grid-template-columns:280px 1fr}',
  '.list{overflow:auto;border-right:1px solid #262634}',
  '.row{padding:5px 10px;cursor:pointer;display:flex;gap:6px;align-items:flex-start}',
  '.row:hover{background:#1b1b28}.row.sel{background:rgba(74,106,160,.18)}',
  '.branch{flex:none;width:52px;color:#4b5563;font:11px/1.4 ui-monospace,Consolas,monospace;white-space:pre}',
  '.name{font-weight:650;font-size:13px}.sum{color:#8b949e;font-size:11px;margin-top:1px}',
  '.route{flex:1;min-height:0;overflow:auto;padding:12px 14px}',
  '.kind{font-size:10px;letter-spacing:.08em;text-transform:uppercase;color:#79c0ff}',
  '.crumb{font-size:11px;color:#8b949e;margin:0 0 6px}',
  '.crumb button{appearance:none;border:0;background:none;color:#79c0ff;cursor:pointer;font:inherit;padding:0}',
  '.body{margin-top:10px;padding:10px;border-radius:8px;background:#161622;border:1px solid #2c2c3e;',
  'white-space:pre-wrap;font:12px/1.55 ui-monospace,Consolas,monospace}',
  '.tag{display:inline-block;margin:4px 4px 0 0;padding:1px 7px;border-radius:999px;',
  'border:1px solid #33334a;font-size:10px;color:#d2a8ff}',
  '.tag.ok{color:#7ee787;border-color:rgba(126,231,135,.45);background:rgba(126,231,135,.08)}',
  '.rel{margin-top:12px}.rel h3{margin:0 0 6px;font-size:11px;color:#8b949e;font-weight:600}',
  '.nav{display:block;width:100%;text-align:left;margin:0 0 4px;padding:5px 8px;border-radius:8px;',
  'border:1px solid #2c2c3e;background:#161622;color:#e6e6ef;font:12px system-ui;cursor:pointer}',
  '.nav:hover{border-color:#4a6aa0}.nav .d{color:#8b949e;font-size:10px;margin-right:6px}',
  '.empty{color:#8b949e;padding:16px}',
  '.lane{font-size:10px;padding:0 5px;border-radius:6px;border:1px solid #333;margin-left:6px;color:#8b949e}',
  '.lane.guide{color:#7ee787;border-color:rgba(126,231,135,.35)}',
  '.lane.evaluate{color:#e3b341;border-color:rgba(227,179,65,.4)}',
  '.lane.behavior{color:#79c0ff;border-color:rgba(121,192,255,.4)}',
  '.graph{position:relative;min-height:280px;background:#12121a;border:1px solid #2c2c3e;border-radius:10px;margin-top:10px}',
  '.gnode{position:absolute;width:150px;padding:7px 8px;border-radius:8px;background:#1b1b28;border:1px solid #33334a;',
  'cursor:pointer;font-size:12px}',
  '.gnode.sel{border-color:#79c0ff}',
  '.gnode .ord{font-size:10px;color:#8b949e}',
  '.toolbar{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-bottom:8px}',
  '.go{appearance:none;border:1px solid rgba(126,231,135,.4);background:rgba(126,231,135,.1);color:#7ee787;',
  'border-radius:8px;padding:5px 10px;cursor:pointer;font-size:12px}',
  '.algo{font-size:11px;color:#8b949e;margin:0 0 8px}',
  '.step{font-size:12px;padding:6px 8px;border-left:3px solid #333;margin:4px 0;background:#161622}',
  '.hide{display:none!important}',
  '</style></head><body>',
  '<div class="bar"><div><h1>Primitive 仓库</h1>',
  '<p class="desc">树分解 · 双向链 · 内部路由只编排「怎么想」，不注入 prompt-context。</p></div>',
  '<div class="tabs">',
  '<button type="button" class="on" data-tab="store" id="tab-store">仓库</button>',
  '<button type="button" data-tab="route" id="tab-route">路由</button>',
  '</div></div>',
  '<div id="pane-store" style="flex:1;min-height:0;display:flex;flex-direction:column">',
  '<div class="sub"><div class="chips" id="chips"></div>',
  '<input type="search" id="q" placeholder="搜索名称 / id" /></div>',
  '<div class="layout"><div class="list" id="list"></div><div class="detail" id="detail"></div></div></div>',
  '<div id="pane-route" class="route hide">',
  '<div class="toolbar">',
  '<input type="text" id="hint" placeholder="线索：证据 / 分岔 / 影子…" />',
  '<button type="button" class="go" id="run">试跑路由</button>',
  '<span class="algo" id="loadlab"></span></div>',
  '<p class="algo" id="algo"></p>',
  '<div class="graph" id="graph"><svg id="wires" style="position:absolute;inset:0;width:100%;height:100%"></svg></div>',
  '<div id="steps"></div></div>',
  '<script>',
  'var tagFilter="",selId="",q="",tab="store",more=false,route=null;',
  'var snap={primitives:[],tags:[],approvedTags:[],tree:[],links:[]};',
  'function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;");}',
  'function approvedSet(){var s={};(snap.approvedTags||[]).forEach(function(t){s[t]=true;});return s;}',
  'function isApproved(tag){return !!approvedSet()[tag];}',
  'function byId(id){return (snap.primitives||[]).find(function(p){return p.id===id;});}',
  'async function call(m,a){var r=await window.wh.call("primitive",m,a||[]);if(!r.ok)throw new Error(r.error||"失败");return r.result;}',
  'function tagMatch(p){if(!tagFilter)return true;return (p.tags||[]).indexOf(tagFilter)>=0||p.thinkKind===tagFilter;}',
  'function textMatch(p){if(!q)return true;var h=(p.id+" "+p.name+" "+(p.summary||"")).toLowerCase();return h.indexOf(q.toLowerCase())>=0;}',
  'function visibleIds(){',
  '  var vis={};',
  '  (snap.primitives||[]).forEach(function(p){if(tagMatch(p)&&textMatch(p))vis[p.id]=true;});',
  '  Object.keys(vis).forEach(function(id){var n=byId(id);while(n&&n.parentId){vis[n.parentId]=true;n=byId(n.parentId);}});',
  '  return vis;',
  '}',
  'function filterTree(nodes, vis){',
  '  return (nodes||[]).map(function(n){var kids=filterTree(n.children||[], vis);',
  '    if(vis[n.id]||kids.length)return {id:n.id,name:n.name,children:kids};return null;}).filter(Boolean);',
  '}',
  'function renderChips(){',
  '  var ok=approvedSet();',
  '  var html=\'<button type="button" class="chip\'+(tagFilter?"":" on")+\'" data-tag="">全部 \'+snap.primitives.length+"</button>";',
  '  (snap.approvedTags||[]).forEach(function(tag){',
  '    var n=0;(snap.tags||[]).forEach(function(t){if(t.tag===tag)n=t.count;});',
  '    html+=\'<button type="button" class="chip ok\'+(tagFilter===tag?" on":"")+\'" data-tag="\'+esc(tag)+\'">\'+esc(tag)+" "+n+"</button>";',
  '  });',
  '  var rest=(snap.tags||[]).filter(function(t){return !ok[t.tag];});',
  '  html+=\'<button type="button" class="chip" id="morebtn">\'+(more?"收起标签":"其它标签 "+rest.length)+"</button>";',
  '  if(more)rest.forEach(function(t){html+=\'<button type="button" class="chip\'+(tagFilter===t.tag?" on":"")+\'" data-tag="\'+esc(t.tag)+\'">\'+esc(t.tag)+" "+t.count+"</button>";});',
  '  document.getElementById("chips").innerHTML=html;',
  '  document.querySelectorAll("#chips .chip").forEach(function(btn){',
  '    if(btn.id==="morebtn"){btn.onclick=function(){more=!more;renderChips();};return;}',
  '    btn.onclick=function(){tagFilter=btn.getAttribute("data-tag")||"";selId="";renderStore();};',
  '  });',
  '}',
  'function treeHtml(nodes, prefix){',
  '  return (nodes||[]).map(function(n,i){',
  '    var last=i===(nodes.length-1);',
  '    var p=byId(n.id)||n;',
  '    var br=prefix.map(function(open){return open?"│ ":"  ";}).join("")+(prefix.length?(last?"└ ":"├ "):"");',
  '    var row=\'<div class="row\'+(selId===n.id?" sel":"")+\'" data-id="\'+esc(n.id)+\'"><div class="branch">\'+esc(br)+"</div><div>"',
  '      +\'<div class="name">\'+esc(p.name||n.name)+"</div>"',
  '      +(p.summary?\'<div class="sum">\'+esc(p.summary)+"</div>":"")+"</div></div>";',
  '    return row+treeHtml(n.children||[], prefix.concat(!last));',
  '  }).join("");',
  '}',
  'function renderList(){',
  '  var nodes=filterTree(snap.tree||[], visibleIds());',
  '  var el=document.getElementById("list");',
  '  if(!nodes.length){el.innerHTML=\'<div class="empty">无匹配</div>\';return;}',
  '  el.innerHTML=treeHtml(nodes,[]);',
  '  el.querySelectorAll(".row").forEach(function(row){row.onclick=function(){selId=row.getAttribute("data-id")||"";renderList();renderDetail();};});',
  '}',
  'function crumbs(id){',
  '  var chain=[],n=byId(id);',
  '  while(n){chain.unshift(n);n=n.parentId?byId(n.parentId):null;}',
  '  return chain.map(function(p,i){',
  '    return i<chain.length-1?\'<button type="button" class="navc" data-id="\'+esc(p.id)+\'">\'+esc(p.name)+"</button> / ":esc(p.name);',
  '  }).join("");',
  '}',
  'function navBtn(id,label,extra){return \'<button type="button" class="nav" data-id="\'+esc(id)+\'"><span class="d">\'+esc(extra||"")+"</span>"+esc(label)+"</button>";}',
  'function bindJump(el){el.querySelectorAll("[data-id]").forEach(function(btn){if(btn.classList.contains("row"))return;btn.onclick=function(){selId=btn.getAttribute("data-id")||"";renderList();renderDetail();};});}',
  'async function renderDetail(){',
  '  var el=document.getElementById("detail");',
  '  if(!selId){el.innerHTML=\'<div class="empty">点左侧一条。树看分解，链看两端。</div>\';return;}',
  '  var p=await call("get",[selId]);',
  '  if(!p){el.innerHTML=\'<div class="empty">不存在</div>\';return;}',
  '  var nb=await call("neighbors",[selId]);',
  '  var html=\'<div class="crumb">\'+crumbs(p.id)+"</div>"',
  '    +\'<div class="kind">\'+esc(p.thinkKind||"primitive")+" · "+esc(p.id)+"</div>"',
  '    +"<h2 style=\\"margin:4px 0 4px;font-size:18px\\">"+esc(p.name)+"</h2>"',
  '    +\'<div class="sum">\'+esc(p.summary)+"</div>"',
  '    +(p.tags||[]).map(function(t){return \'<span class="tag\'+(isApproved(t)?" ok":"")+\'">\'+esc(t)+"</span>";}).join("")',
  '    +\'<div class="body">\'+esc(p.body)+"</div>";',
  '  var parents=nb.filter(function(n){return n.relation==="parent";});',
  '  var children=nb.filter(function(n){return n.relation==="child";});',
  '  var linked=nb.filter(function(n){return n.relation==="link";});',
  '  if(parents.length){html+=\'<div class="rel"><h3>树 · 父</h3>\';parents.forEach(function(n){html+=navBtn(n.id,n.name,"↑");});html+="</div>";}',
  '  if(children.length){html+=\'<div class="rel"><h3>树 · 子</h3>\';children.forEach(function(n){html+=navBtn(n.id,n.name,"↓");});html+="</div>";}',
  '  if(linked.length){html+=\'<div class="rel"><h3>双向链</h3>\';linked.forEach(function(n){html+=navBtn(n.id,n.name,(n.dir==="out"?"→ ":"← ")+(n.kind||"link"));});html+="</div>";}',
  '  html+=\'<div class="rel"><button type="button" class="go" id="to-route">用此条试跑路由</button></div>\';',
  '  el.innerHTML=html;bindJump(el);',
  '  var tr=document.getElementById("to-route");if(tr)tr.onclick=function(){switchTab("route");runRoute({startId:selId});};',
  '}',
  'function renderStore(){renderChips();renderList();renderDetail();}',
  'function switchTab(next){',
  '  tab=next;',
  '  document.getElementById("tab-store").classList.toggle("on",tab==="store");',
  '  document.getElementById("tab-route").classList.toggle("on",tab==="route");',
  '  document.getElementById("pane-store").classList.toggle("hide",tab!=="store");',
  '  document.getElementById("pane-route").classList.toggle("hide",tab!=="route");',
  '  if(tab==="route"&&!route)runRoute({});',
  '}',
  'async function runRoute(opts){',
  '  var hint=document.getElementById("hint").value;',
  '  route=await call("route",[{hint:hint,startId:opts&&opts.startId,tag:tagFilter||undefined,limit:5}]);',
  '  renderRoute();',
  '}',
  'function renderRoute(){',
  '  if(!route)return;',
  '  document.getElementById("algo").textContent=route.algorithm||"";',
  '  document.getElementById("loadlab").textContent="负荷 "+route.load+" / "+route.loadCap;',
  '  var steps=document.getElementById("steps");',
  '  steps.innerHTML=(route.steps||[]).map(function(s){',
  '    return \'<div class="step"><b>\'+s.order+". "+esc(s.name)+\'</b><span class="lane \'+esc(s.lane)+\'">\'+esc(s.lane)+"</span>"',
  '      +\'<div class="sum">\'+esc(s.via)+" · "+esc(s.reason)+"</div></div>";',
  '  }).join("")||\'<div class="empty">没有命中。换线索或从仓库点一条再试跑。</div>\';',
  '  drawGraph(route);',
  '}',
  'function drawGraph(rt){',
  '  var box=document.getElementById("graph");',
  '  var svg=document.getElementById("wires");',
  '  Array.from(box.querySelectorAll(".gnode")).forEach(function(n){n.remove();});',
  '  var cols={guide:0,evaluate:1,behavior:2,other:1};',
  '  var buckets={0:[],1:[],2:[]};',
  '  (rt.steps||[]).forEach(function(s){var c=cols[s.lane];if(c==null)c=1;(buckets[c]||buckets[1]).push(s);});',
  '  var pos={};var max=1;',
  '  [0,1,2].forEach(function(c){',
  '    (buckets[c]||[]).forEach(function(s,i){',
  '      var x=24+c*210,y=16+i*72;pos[s.id]={x:x,y:y,w:150,h:48};if(i+1>max)max=i+1;',
  '      var el=document.createElement("div");el.className="gnode"+(selId===s.id?" sel":"");',
  '      el.style.left=x+"px";el.style.top=y+"px";',
  '      el.innerHTML=\'<div class="ord">\'+s.order+" · "+esc(s.lane)+"</div><div>"+esc(s.name)+"</div>";',
  '      el.onclick=function(){selId=s.id;switchTab("store");renderStore();};',
  '      box.appendChild(el);',
  '    });',
  '  });',
  '  box.style.height=Math.max(280,max*72+24)+"px";',
  '  svg.innerHTML=(rt.edges||[]).map(function(e){',
  '    var a=pos[e.source],b=pos[e.target];if(!a||!b)return "";',
  '    var x1=a.x+a.w,y1=a.y+a.h/2,x2=b.x,y2=b.y+b.h/2;',
  '    return \'<line x1="\'+x1+\'" y1="\'+y1+\'" x2="\'+x2+\'" y2="\'+y2+\'" stroke="#4a4a66" stroke-width="1.4" marker-end="url(#m)"/>\';',
  '  }).join("");',
  '  svg.innerHTML=\'<defs><marker id="m" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="#4a4a66"/></marker></defs>\'+svg.innerHTML;',
  '}',
  'document.getElementById("tab-store").onclick=function(){switchTab("store");};',
  'document.getElementById("tab-route").onclick=function(){switchTab("route");};',
  'document.getElementById("run").onclick=function(){runRoute({});};',
  'document.getElementById("hint").addEventListener("keydown",function(e){if(e.key==="Enter")runRoute({});});',
  'document.getElementById("q").addEventListener("input",function(e){q=e.target.value||"";renderList();});',
  'call("snapshot").then(function(s){snap=s;if(!snap.tree)snap.tree=[];renderStore();}).catch(function(e){',
  '  document.getElementById("detail").innerHTML=\'<div class="empty">\'+esc(e.message||e)+"</div>";});',
  '</script></body></html>',
].join('');
