export const QUERY_LOOP_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  'body{margin:0;font-family:system-ui,"Microsoft YaHei",sans-serif;background:#16161e;color:#e6e6ef}',
  '.card{padding:18px 22px;overflow:auto;height:100%;box-sizing:border-box}',
  'h1{font-size:16px;margin:0 0 6px}',
  '.desc{margin:0 0 12px;font-size:13px;color:#a8a8bd;line-height:1.6}',
  '.meta{font:12px ui-monospace,Consolas,monospace;color:#79c0ff;margin:0 0 12px}',
  'textarea,button{font:12px/1.5 system-ui,"Microsoft YaHei",sans-serif}',
  'textarea{width:100%;box-sizing:border-box;background:#101018;color:#e6e6ef;border:1px solid #2c2c3e;border-radius:8px;padding:8px}',
  'button{margin-top:8px;background:rgba(126,231,135,.14);border:1px solid rgba(126,231,135,.35);color:#7ee787;border-radius:8px;padding:6px 12px;cursor:pointer}',
  'pre{white-space:pre-wrap;font-size:12px;color:#d7d7e4}',
  '</style></head><body><div class="card">',
  '<h1>Query 循环</h1>',
  '<p class="desc">assemble → model → tools → 再 assemble，直到没有 tool_use。兼容 agentLoop.run / cancel。旧 agent-loop 已在组合里禁用。</p>',
  '<p class="meta" id="meta">…</p>',
  '<textarea id="p" rows="3">echo hi</textarea>',
  '<button id="go">运行</button>',
  '<pre id="out"></pre>',
  '<script>',
  'async function meta(){',
  'const el=document.getElementById("meta");',
  'if(!window.wh||!window.wh.call){el.textContent="无 RPC";return;}',
  'const r=await window.wh.call("queryLoop","inspect",[]);',
  'if(!r.ok){el.textContent=r.error||"失败";return;}',
  'el.textContent="paradigm "+r.result.paradigm+" · maxSteps "+r.result.maxSteps+" · hooks "+((r.result.hooks||[]).join(",")||"(none)");',
  '}',
  'document.getElementById("go").onclick=async()=>{',
  'const out=document.getElementById("out"); out.textContent="…";',
  'try{ const r=await window.wh.call("agentLoop","run",[{prompt:document.getElementById("p").value,maxSteps:4}]);',
  'out.textContent=r.ok?JSON.stringify(r.result,null,2):(r.error||"失败"); }catch(e){ out.textContent=String(e); }',
  '};',
  'meta();',
  '</script>',
  '</div></body></html>',
].join('');
