export const FILE_MANAGER_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  '*{box-sizing:border-box}',
  'body{margin:0;font-family:system-ui,"Microsoft YaHei",sans-serif;background:#16161e;color:#e6e6ef;height:100vh;display:flex;flex-direction:column}',
  '.bar{flex:none;display:flex;align-items:center;gap:8px;padding:10px 12px;border-bottom:1px solid #262634;background:#1b1b24}',
  '.root{font:11px ui-monospace,Consolas,monospace;color:#79c0ff;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1}',
  '.btn{background:rgba(121,192,255,.12);border:1px solid rgba(121,192,255,.35);color:#79c0ff;border-radius:6px;padding:4px 10px;cursor:pointer;font-size:12px}',
  '.btn:hover{background:rgba(121,192,255,.2)}',
  '.crumb{font:12px ui-monospace,Consolas,monospace;color:#a8a8bd;padding:8px 12px;border-bottom:1px solid #262634;flex:none}',
  '.crumb button{background:none;border:none;color:#79c0ff;cursor:pointer;font:inherit;padding:0}',
  '.crumb button:hover{text-decoration:underline}',
  '.list{flex:1;overflow:auto;margin:0;padding:6px 0;list-style:none}',
  '.row{display:flex;align-items:center;gap:8px;padding:6px 14px;cursor:pointer;font:12px ui-monospace,Consolas,monospace}',
  '.row:hover{background:rgba(255,255,255,.05)}',
  '.k{color:#8b949e;width:28px;flex:none}',
  '.name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.err{padding:12px;color:#ff7b72;font-size:12px}',
  '</style></head><body>',
  '<div class="bar"><span class="root" id="root">…</span><button type="button" class="btn" id="up">上级</button><button type="button" class="btn" id="ref">刷新</button></div>',
  '<div class="crumb" id="crumb"></div>',
  '<ul class="list" id="list"></ul>',
  '<div class="err" id="err" style="display:none"></div>',
  '<script>',
  'var cwd=".";',
  'function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;");}',
  'function norm(p){return String(p||".").replace(/\\\\/g,"/").replace(/^\\/+|\\/+$/g,"")||".";}',
  'function parentOf(p){if(p==="."||!p)return null;var parts=norm(p).split("/");parts.pop();return parts.length?parts.join("/"):".";}',
  'function renderCrumb(){',
  'var el=document.getElementById("crumb"),parts=norm(cwd)==="."?[]:norm(cwd).split("/"),acc="",html=\'<button type="button" data-p=".">根</button>\';',
  'parts.forEach(function(seg){acc=acc?acc+"/"+seg:seg;html+=\' / <button type="button" data-p="\'+esc(acc)+\'">\'+esc(seg)+"</button>";});',
  'el.innerHTML=html;el.querySelectorAll("button").forEach(function(b){b.onclick=function(){load(b.getAttribute("data-p"));};});',
  '}',
  'async function load(rel){',
  'cwd=norm(rel||".");',
  'var err=document.getElementById("err"),list=document.getElementById("list");err.style.display="none";',
  'if(!window.wh||!window.wh.call){err.textContent="无 RPC";err.style.display="block";return;}',
  'var l=await window.wh.call("fileManager","list",[cwd]);',
  'if(!l.ok){err.textContent=l.error||"list 失败";err.style.display="block";list.innerHTML="";return;}',
  'renderCrumb();list.innerHTML="";',
  '(l.result.entries||[]).forEach(function(e){',
  'var li=document.createElement("li");li.className="row";',
  'li.innerHTML=\'<span class="k">\'+(e.kind==="dir"?"📁":"📄")+\'</span><span class="name">\'+esc(e.name)+"</span>";',
  'li.onclick=function(){',
  'var next=cwd==="."?e.name:(cwd+"/"+e.name);',
  'if(e.kind==="dir")load(next);',
  'else if(window.wh.openCodeBrowser)window.wh.openCodeBrowser(next);',
  '};list.appendChild(li);',
  '});',
  'if(!(l.result.entries||[]).length)list.innerHTML=\'<li class="row"><span class="k"></span><span class="name dim">（空）</span></li>\';',
  '}',
  'async function boot(){',
  'if(!window.wh||!window.wh.call)return;',
  'var i=await window.wh.call("fileManager","info",[]);',
  'if(i.ok)document.getElementById("root").textContent=i.result.root;',
  'document.getElementById("up").onclick=function(){var p=parentOf(cwd);if(p!=null)load(p);};',
  'document.getElementById("ref").onclick=function(){load(cwd);};',
  'load(".");',
  '}',
  'boot();',
  '</script></body></html>',
].join('');
