export interface EditorPageParts {
  chromeCss: string;
  contextMenuCss: string;
  syntaxCss: string;
  contextMenuHtml: string;
  syntaxJs: string;
  contextMenuJs: string;
  fileSyncJs: string;
}

export function CODE_EDITOR_HTML(parts: EditorPageParts): string {
  return [
    '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
    parts.chromeCss,
    parts.contextMenuCss,
    parts.syntaxCss,
    '.editor-stack pre.hl,.editor-stack textarea{position:absolute;inset:0;margin:0;padding:10px 12px;overflow:auto;',
    'font:12px/1.5 ui-monospace,Consolas,"Cascadia Code",monospace;tab-size:2;white-space:pre;word-wrap:normal}',
    '</style></head><body>',
    '<div class="bar"><span class="path" id="path">（未打开文件）</span><span class="meta" id="meta"></span>',
    '<button type="button" class="btn" id="reload">重载</button><button type="button" class="btn primary" id="save" disabled>保存</button></div>',
    '<div class="edit-wrap workspace" id="wrap" style="display:none"><pre class="gutter" id="gutter"></pre>',
    '<div class="editor-stack"><pre class="hl code-pane code-scroll" id="hl" aria-hidden="true"><code id="hlInner"></code></pre>',
    '<textarea class="code-scroll" id="ta" spellcheck="false" autocomplete="off" autocorrect="off" autocapitalize="off"></textarea></div></div>',
    '<div class="err" id="err"></div>',
    parts.contextMenuHtml,
    '<div class="status" id="status">就绪 · Ctrl+S 保存</div>',
    '<script>',
    parts.syntaxJs,
    parts.contextMenuJs,
    parts.fileSyncJs,
    'var curPath="",curFull="",dirty=false,root="",sliceMode=null,gutterFrom=1,lastSelfChange=0;',
    'function syncGutter(){',
    'var ta=document.getElementById("ta"),g=document.getElementById("gutter");',
    'var n=(ta.value.match(/\\n/g)||[]).length+1,lines=[];',
    'for(var i=0;i<n;i++)lines.push(gutterFrom+i);g.textContent=lines.join("\\n");g.scrollTop=ta.scrollTop;}',
    'function syncHighlight(){',
    'var ta=document.getElementById("ta"),hl=document.getElementById("hlInner");',
    'paintHighlight(hl,ta.value,curPath);var pre=document.getElementById("hl");',
    'pre.scrollTop=ta.scrollTop;pre.scrollLeft=ta.scrollLeft;}',
    'function setDirty(v){dirty=v;document.getElementById("save").disabled=!curPath||!dirty;',
    'document.getElementById("status").textContent=dirty?"未保存":(sliceMode?"局部已同步":"已同步");}',
    'function sliceText(full,start,end){return full.split("\\n").slice(start-1,end).join("\\n");}',
    'async function openFile(rel,slice){',
    'if(!window.wh||!window.wh.call)return;',
    'var err=document.getElementById("err"),wrap=document.getElementById("wrap");',
    'err.textContent="";sliceMode=null;gutterFrom=1;',
    'var r=await window.wh.call("codeEditor","read",[rel]);',
    'if(!r.ok){wrap.style.display="none";err.textContent=r.error||"读取失败";return;}',
    'curPath=r.result.path;curFull=r.result.content;',
    'var view=curFull;',
    'if(slice&&slice.startLine&&slice.endLine){sliceMode={startLine:slice.startLine,endLine:slice.endLine};',
    'gutterFrom=slice.startLine;view=sliceText(curFull,slice.startLine,slice.endLine);}',
    'document.getElementById("path").textContent=curPath+(sliceMode?" · L"+sliceMode.startLine+"-"+sliceMode.endLine:"");',
    'document.getElementById("meta").textContent=view.split("\\n").length+" 行"+(sliceMode?" · 局部":" · 全文");',
    'document.getElementById("ta").value=view;wrap.style.display="flex";syncGutter();syncHighlight();setDirty(false);',
    '}',
    'async function refreshFromDisk(){',
    'if(!curPath||dirty)return;',
    'var r=await window.wh.call("codeEditor","read",[curPath]);',
    'if(!r.ok)return;curFull=r.result.content;',
    'var view=sliceMode?sliceText(curFull,sliceMode.startLine,sliceMode.endLine):curFull;',
    'var ta=document.getElementById("ta");if(ta.value===view)return;',
    'var scroll=ta.scrollTop;ta.value=view;syncGutter();syncHighlight();ta.scrollTop=scroll;setDirty(false);',
    '}',
    'async function saveFile(){',
    'if(!curPath||!window.wh||!window.wh.call)return;',
    'var content=document.getElementById("ta").value,r;',
    'if(sliceMode){r=await window.wh.call("codeEditor","patch",[curPath,sliceMode.startLine,sliceMode.endLine,content]);',
    'if(r.ok){var full=await window.wh.call("codeEditor","read",[curPath]);if(full.ok)curFull=full.result.content;}}',
    'else r=await window.wh.call("codeEditor","write",[curPath,content]);',
    'if(!r.ok){document.getElementById("err").textContent=r.error||"保存失败";return;}',
    'if(!sliceMode)curFull=content;document.getElementById("err").textContent="";setDirty(false);lastSelfChange=Date.now();',
    '}',
    'async function boot(){',
    'if(!window.wh||!window.wh.call)return;',
    'var i=await window.wh.call("codeEditor","info",[]);',
    'if(i.ok){root=i.result.root;document.getElementById("status").textContent="root: "+root;}',
    'var ta=document.getElementById("ta");',
    'ta.addEventListener("input",function(){syncGutter();syncHighlight();setDirty(true);});',
    'ta.addEventListener("scroll",function(){syncGutter();syncHighlight();});',
    'document.getElementById("save").onclick=saveFile;',
    'document.getElementById("reload").onclick=function(){if(curPath)openFile(curPath,sliceMode);};',
    'document.addEventListener("keydown",function(e){if((e.ctrlKey||e.metaKey)&&e.key==="s"){e.preventDefault();saveFile();}});',
    'startFileSync(function(payload){',
    'if(normPath(payload.path)!==normPath(curPath))return;',
    'if(Date.now()-lastSelfChange<800)return;',
    'if(dirty){document.getElementById("status").textContent="磁盘已更新 · 有未保存修改";return;}',
    'refreshFromDisk();});',
    'var pending=await window.wh.call("codeEditor","takePendingOpen",[]);',
    'if(pending.ok&&pending.result){',
    'var t=pending.result;if(typeof t==="string")await openFile(t);else await openFile(t.path,t);}',
    '}',
    'window.__whOpenFile=function(rel){return openFile(rel);};',
    'window.__whOpenTarget=function(t){if(typeof t==="string")return openFile(t);return openFile(t.path,t);};',
    'boot();',
    '</script></body></html>',
  ].join('');
}
