import { SYNTAX_CSS, SYNTAX_JS } from './syntax.js';

export const CODE_EDITOR_HTML = [
  '<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>',
  '*{box-sizing:border-box}',
  'body{margin:0;font-family:system-ui,"Microsoft YaHei",sans-serif;background:#16161e;color:#e6e6ef;height:100vh;display:flex;flex-direction:column}',
  '.bar{flex:none;display:flex;align-items:center;gap:8px;padding:8px 12px;border-bottom:1px solid #262634;background:#1b1b24}',
  '.path{font:12px ui-monospace,Consolas,monospace;color:#79c0ff;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.meta{font:11px;color:#8b949e;flex:none}',
  '.btn{background:rgba(121,192,255,.12);border:1px solid rgba(121,192,255,.35);color:#79c0ff;border-radius:6px;padding:4px 12px;cursor:pointer;font-size:12px}',
  '.btn.primary{background:rgba(46,160,67,.25);border-color:rgba(46,160,67,.5);color:#7ee787}',
  '.btn:disabled{opacity:.45;cursor:default}',
  '.edit-wrap{flex:1;min-height:0;display:flex;overflow:hidden}',
  '.gutter{flex:none;width:44px;overflow:hidden;background:#14141e;border-right:1px solid #262634;padding:8px 6px 8px 0;text-align:right;',
  'font:12px/1.45 ui-monospace,Consolas,monospace;color:#6e7681;user-select:none}',
  '.editor-stack{position:relative;flex:1;min-width:0;min-height:0}',
  '.editor-stack pre.hl,.editor-stack textarea{position:absolute;inset:0;margin:0;padding:8px 10px;overflow:auto;',
  'font:12px/1.45 ui-monospace,Consolas,monospace;tab-size:2;white-space:pre;word-wrap:normal;border:none;outline:none}',
  '.editor-stack pre.hl{color:#e6e6ef;background:#16161e;pointer-events:none;z-index:0}',
  '.editor-stack textarea{color:transparent;caret-color:#e6e6ef;background:transparent;resize:none;z-index:1}',
  SYNTAX_CSS,
  '.status{flex:none;padding:6px 12px;font-size:11px;color:#8b949e;border-top:1px solid #262634}',
  '.err{color:#ff7b72;padding:12px;font-size:12px}',
  '</style></head><body>',
  '<div class="bar"><span class="path" id="path">（未打开文件）</span><span class="meta" id="meta"></span>',
  '<button type="button" class="btn" id="reload">重载</button><button type="button" class="btn primary" id="save" disabled>保存</button></div>',
  '<div class="edit-wrap" id="wrap" style="display:none"><pre class="gutter" id="gutter"></pre>',
  '<div class="editor-stack"><pre class="hl" id="hl" aria-hidden="true"><code id="hlInner"></code></pre>',
  '<textarea id="ta" spellcheck="false" autocomplete="off" autocorrect="off" autocapitalize="off"></textarea></div></div>',
  '<div class="err" id="err"></div>',
  '<div class="status" id="status">就绪</div>',
  '<script>',
  SYNTAX_JS,
  'var curPath="",dirty=false,root="";',
  'function syncGutter(){',
  'var ta=document.getElementById("ta"),g=document.getElementById("gutter");',
  'var n=(ta.value.match(/\\n/g)||[]).length+1,lines=[];for(var i=1;i<=n;i++)lines.push(i);',
  'g.textContent=lines.join("\\n");g.scrollTop=ta.scrollTop;',
  '}',
  'function syncHighlight(){',
  'var ta=document.getElementById("ta"),hl=document.getElementById("hlInner");',
  'paintHighlight(hl,ta.value,curPath);hl.parentElement.scrollTop=ta.scrollTop;hl.parentElement.scrollLeft=ta.scrollLeft;',
  '}',
  'function setDirty(v){dirty=v;document.getElementById("save").disabled=!curPath||!dirty;document.getElementById("status").textContent=dirty?"未保存":"已同步";}',
  'async function openFile(rel){',
  'if(!window.wh||!window.wh.call)return;',
  'var err=document.getElementById("err"),wrap=document.getElementById("wrap");',
  'err.textContent="";',
  'var r=await window.wh.call("codeEditor","read",[rel]);',
  'if(!r.ok){wrap.style.display="none";err.textContent=r.error||"读取失败";return;}',
  'curPath=r.result.path;document.getElementById("path").textContent=curPath;',
  'document.getElementById("meta").textContent=r.result.lines+" 行";',
  'document.getElementById("ta").value=r.result.content;wrap.style.display="flex";syncGutter();syncHighlight();setDirty(false);',
  '}',
  'async function saveFile(){',
  'if(!curPath||!window.wh||!window.wh.call)return;',
  'var content=document.getElementById("ta").value;',
  'var r=await window.wh.call("codeEditor","write",[curPath,content]);',
  'if(!r.ok){document.getElementById("err").textContent=r.error||"保存失败";return;}',
  'document.getElementById("err").textContent="";setDirty(false);',
  '}',
  'async function boot(){',
  'if(!window.wh||!window.wh.call)return;',
  'var i=await window.wh.call("codeEditor","info",[]);',
  'if(i.ok){root=i.result.root;document.getElementById("status").textContent="root: "+root;}',
  'var pending=await window.wh.call("codeEditor","takePendingOpen",[]);',
  'if(pending.ok&&pending.result)await openFile(pending.result);',
  'var ta=document.getElementById("ta");',
  'ta.addEventListener("input",function(){syncGutter();syncHighlight();setDirty(true);});',
  'ta.addEventListener("scroll",function(){syncGutter();syncHighlight();});',
  'document.getElementById("save").onclick=saveFile;',
  'document.getElementById("reload").onclick=function(){if(curPath)openFile(curPath);};',
  'document.addEventListener("keydown",function(e){if((e.ctrlKey||e.metaKey)&&e.key==="s"){e.preventDefault();saveFile();}});',
  '}',
  'window.__whOpenFile=openFile;',
  'boot();',
  '</script></body></html>',
].join('');
