/** 与 code-browser/src/syntax.ts 保持同步 */
export const SYNTAX_CSS = [
  '.hl-kw{color:#ff7b72}',
  '.hl-str{color:#a5d6ff}',
  '.hl-cmt{color:#8b949e;font-style:italic}',
  '.hl-num{color:#79c0ff}',
  '.hl-key{color:#ffa657}',
  '.hl-fn{color:#d2a8ff}',
  '.hl-type{color:#ffa657}',
  '.hl-tag{color:#7ee787}',
  '.hl-bool{color:#ff7b72}',
  'pre.code code{display:block}',
].join('');

export const SYNTAX_JS = [
  'function escHtml(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}',
  'function langOf(path){var m=String(path||"").match(/\\.([^.]+)$/);if(!m)return"plain";',
  'var e=m[1].toLowerCase();if(e==="ts"||e==="tsx")return"ts";if(e==="js"||e==="jsx"||e==="mjs"||e==="cjs")return"js";',
  'if(e==="json")return"json";if(e==="css"||e==="scss")return"css";if(e==="html"||e==="htm")return"html";',
  'if(e==="md"||e==="markdown")return"md";return"plain";}',
  'var HL_KW="abstract async await break case catch class const continue debugger default delete do else enum export extends false finally for from function get if implements import in infer instanceof interface let module namespace new null of package private protected public return set static super switch this throw true try type typeof undefined var void while with yield".split(" ");',
  'function hlKw(word,lang){if(lang==="json"||lang==="css"||lang==="html"||lang==="md"||lang==="plain")return false;return HL_KW.indexOf(word)>=0;}',
  'function highlightSource(code,path){',
  'var lang=langOf(path),s=escHtml(String(code||"")),ph=[];',
  'function stash(html){var id=ph.length;ph.push(html);return"\\uE000"+String.fromCharCode(0xF000+id)+"\\uE001";}',
  'function unwrap(){ph.forEach(function(h,idx){s=s.split("\\uE000"+String.fromCharCode(0xF000+idx)+"\\uE001").join(h);});return s;}',
  'if(lang==="plain"||lang==="md")return s;',
  'if(lang==="json"){',
  's=s.replace(/"([^"\\\\]|\\\\.)*"(\\s*:)/g,function(m,p1,p2){return stash(\'<span class="hl-key">\'+m.slice(0,m.length-p2.length)+"</span>")+p2;});',
  's=s.replace(/"([^"\\\\]|\\\\.)*"/g,function(m){return stash(\'<span class="hl-str">\'+m+"</span>");});',
  's=s.replace(/\\b(true|false|null)\\b/g,function(m){return stash(\'<span class="hl-bool">\'+m+"</span>");});',
  's=s.replace(/\\b-?\\d+\\.?\\d*\\b/g,function(m){return stash(\'<span class="hl-num">\'+m+"</span>");});return unwrap();}',
  'if(lang==="css"){',
  's=s.replace(/\\/\\*[\\s\\S]*?\\*\\//g,function(m){return stash(\'<span class="hl-cmt">\'+m+"</span>");});',
  's=s.replace(/"([^"\\\\]|\\\\.)*"|\'([^\'\\\\]|\\\\.)*\'/g,function(m){return stash(\'<span class="hl-str">\'+m+"</span>");});',
  's=s.replace(/#[0-9a-fA-F]{3,8}\\b/g,function(m){return stash(\'<span class="hl-num">\'+m+"</span>");});',
  's=s.replace(/\\b\\d+\\.?\\d*(?:px|em|rem|%|s|ms)?\\b/g,function(m){return stash(\'<span class="hl-num">\'+m+"</span>");});return unwrap();}',
  'if(lang==="html"){',
  's=s.replace(/&lt;!--[\\s\\S]*?--&gt;/g,function(m){return stash(\'<span class="hl-cmt">\'+m+"</span>");});',
  's=s.replace(/&lt;\\/?[a-zA-Z][^&]*?&gt;/g,function(m){return stash(\'<span class="hl-tag">\'+m+"</span>");});return unwrap();}',
  's=s.replace(/\\/\\/[^\\n]*/g,function(m){return stash(\'<span class="hl-cmt">\'+m+"</span>");});',
  's=s.replace(/\\/\\*[\\s\\S]*?\\*\\//g,function(m){return stash(\'<span class="hl-cmt">\'+m+"</span>");});',
  's=s.replace(/"(?:\\\\.|[^"\\\\])*"|\'(?:\\\\.|[^\'\\\\])*\'|`(?:\\\\.|[^`\\\\])*`/g,function(m){return stash(\'<span class="hl-str">\'+m+"</span>");});',
  's=s.replace(/\\b[A-Za-z_$][\\w$]*(?=\\s*\\()/g,function(m){return stash(\'<span class="hl-fn">\'+m+"</span>");});',
  's=s.replace(/\\b[A-Z][a-zA-Z0-9_]*\\b/g,function(m){return stash(\'<span class="hl-type">\'+m+"</span>");});',
  's=s.replace(/\\b-?\\d+\\.?\\d*\\b/g,function(m){return stash(\'<span class="hl-num">\'+m+"</span>");});',
  's=s.replace(/\\b[A-Za-z_$][\\w$]*\\b/g,function(m){if(hlKw(m,lang))return stash(\'<span class="hl-kw">\'+m+"</span>");return m;});',
  'return unwrap();}',
  'function paintHighlight(el,code,path){if(!el)return;el.innerHTML=highlightSource(code,path);}',
].join('');
